### ISSUE TITLE
Images in markdown

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1014]
## Description
As a user of the platform I want to easily attach images to my updates, cards, etc. As a user with a visual impairment I'd like to know what's on the images people use.

## Initiative / goal
Allow for easy ways to copy images into a text and store

### Hypothesis
A link is for many too difficult

## Acceptance criteria and must have scope
- [x] Upload an image in the markdown editor
- [ ] Drag & drop image into the markdown editor
- [ ] Add alternative text to images in the markdown editor
