### ISSUE TITLE
Journey refresh: Space level additional functionality

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1018]
## Description
In the latest UI refresh, we used the labels on the top left to help the user navigate through the Hub, challenges, opportunities. Still, users feel lost when they dive into the deeper levels. 

Also on the Hub level, users want to directly navigate to / see the rest of the content as well as activities in the Hub without having to search / click through all the pages / levels.

## Initiative / goal
Final improvements for the Hub level to improve navigation, visualization and engagement

### Hypothesis
More visual differentiation and clearer navigation will improve the user experience and engagement

### Hypothesis
After completing this set of issues, the Hub level has improved to a level that it is really useful / easier to explain

## Acceptance criteria and must have scope
- [x] Navigation block on Hub dashboard
- [x] Activity of Challenges visible in the Hub activity feed + activity of Opportunity visible in Challenge activity feed
- [x] Tab menu to stick to the top of the page when a user scrolls down. TBD: include small hub title or something?
- [x] Challenges block to show tags to filter on

## Stakeholders
All communities

## Timeline
??

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
