### ISSUE TITLE
Generation of URLs for client-web

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1020]
## Description
As the platform and its functionalities keep growing, so will the urls. For example, an card in an Callout in an Opportunity has the following url 

https://alkem.io/challengecentric/challenges/enabling/opportunities/journeystructure-6338/contribute/callouts/userflows-3638/aspects/employeeofpublice-5830/dashboard

## Initiative / goal
Maintainability
Stability

### Hypothesis
Having a single way to obtain the URL to view an entity will cut down on both errors and code complexity, as well as making adjustments to URL definitions easier in the future (flexibility of code base).

## Acceptance criteria and must have scope
- [ ] Ability to obtain the url from any Profile entity that would then be usable to to view the entity containing the Profile in the client-web application
- [ ] Client-web updated to create URLs using the profile.url field for creation of URLs
- [ ] Notifications service updated to use the profile.url field for creating links in emails, including updating payloads to not contain the full journey hierarchy but instead pass over the relevant profileID

## Stakeholders
development 
product

## Timeline
asap, needed for updated storage bucket approach
