### ISSUE TITLE
Simple Challenge version

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1023]
## Description
There can be situations where people want to work on a Challenge, but this is a smaller Challenge question or a 'design sprint' of only a week or a few hours. Setting up a new Challenge can be a lot and not all functionalities (such as the settings, recommendations, updates etc.) make sense for these smaller questions. 

## Initiative / goal
Explore the option of a Challenge with less functionalities, but with the possibility of an innovation flow, description, contributors, and callouts. But, with the option to convert it to a 'normal challenge'. 

### Hypothesis
There is currently no way for these smaller questions, but they can be a powerful way to engage the community and offer them a standardized process. 

## Acceptance criteria and must have scope
- [ ] Ability for members to add such a Challenge question via the Hub
- [ ] Challenge page with only the dashboard, collaboration space and an about dialog
- [ ] Ability for Hub leads to track the process of these Challenges
- [ ] Ability for the members to easily find their Challenges

Tbd
- [ ] scalability? Will they be archived / become knowledge after completing?
- [ ] Visibility? Private? 
- [ ] How to include a standard template for the innovation flow + callouts in all these Challenges

## Stakeholders
Uwv

## Timeline
..

## Design
https://www.figma.com/file/WyPKMvHxYdzquEXi2yfmA6/Challenge-lite?node-id=0%3A1&t=jbaVImkrQDEqBUHd-1
