### ISSUE TITLE
Innovation Flow usage in Challenges

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1026]
## Description
The key functionality for each Challenge, and where the real action and collaboration happens, is the Innovation Flow. We see the needed for a guided flow, and a tool that can facilitate that, more and more in each conversation with the user. This is leading in the Challenge and should have a more prominent place.

## Initiative / goal
Innovation Flow to be leading and visible on the contribute tab

### Hypothesis
By giving the innovation flow a more direct place on the Challenge it will distinct more from the Space and be used more

## Acceptance criteria and must have scope
- [ ] Innovation flow entity expanded
- [ ] Innovation flow template expanded / XState machine definition : where we store what states are visible and order

- [ ] Contribute tab includes the Innovation Flow states as tags
- [ ] Callouts are linked to a state and can be filtered by state
- [ ] innovation flow / callout settings
- [ ] Mobile design
- [ ] Visual display + description on the left

## Stakeholders
Users 

## Timeline
Q3

## Design
https://www.figma.com/file/BZR4ozFba6KLI0RvfBstDV/Challenges-refresh?type=design&node-id=0%3A1&t=DOYXW4Lw7N4GRd5Q-1
