### ISSUE TITLE
Community Building support / focus

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1029]
## Description
Alkemio is at its heart a combination of change and community. The focus when creating Hubs is all about the change, and very little about the community. This needs to be much more balanced

## Initiative / goal
Growing the community

### Hypothesis
Giving more focus to community definition and building will help communities working on change be more effective.

## Acceptance criteria and must have scope
- [ ] Review of Hub creation flow and first suggested steps to see how to bring more focus on the community definition: who should be involved! We have this field but barely use it.
- [ ] Look at UX design to see how to make the community target profile more visible.
- [ ] Add additional content to Innovation Library to make it easier to define + grow your community
...

## Stakeholders
Community builders

## Timeline
tbd

## Design
Figma file:
