### ISSUE TITLE
Signing up to join a specific Hub

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1031]
## Description
A smooth sign up flow for users that are interested in a particular Hub

## Initiative / goal
Onboarding the community

### Hypothesis
The sign up flow should be as simple as possible, while still secure. Otherwise new users get confused. 

## Acceptance criteria and must have scope
- [ ] After signing up the user should be brought back to where they were
- [ ] After confirming their email address (via clicking on link) the user should be already logged in
- [ ] After confirming their email address, the user should be brought back to the location that they came from when they signed up
- [ ] Able to set the language to display in on the client via URL parameter

## Stakeholders
VNG

## Timeline
Mid April

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
