### ISSUE TITLE
Forum: notifications, sharing

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1035]
## Description
As a user I want to be notified when someone replies to a question I posted
As a  community manager I want to be notified when new entries are posted in the forum

## Initiative / goal
Community building

### Hypothesis
Timely responses to questions raised on the forum is important for overall community engagement
Getting users to come back to their questions and seeing replies gives them value

## Acceptance criteria
- [ ] Create new role: global support
- [ ] Each discussion has a unique URL (discussions are nameable)

- [ ] Notifications for new comments on my discussion > Global support, Discussion creator (default on)
- [ ] Notifications for mentions in a discussion > Person who is mentioned (default on)
- [ ] Notifications for new discussion created > Global support (default on), all users (default off)

- [ ] Notification preferences added to user profiles (Global support on platform admin section)

- [ ] Notification emails include link to discussion

- [ ] Share button

## Stakeholders
tbd

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
