### ISSUE TITLE
Community Terms: phase 2

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1038]
## Description
Expanding on the work donw in phase 1 with additional functionality and scope.

## Initiative / goal
Den Haag project related to Innovation Agreement Templates

### Hypothesis
What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit.

## Acceptance criteria and must have scope
- [ ] Explicitly track that people have accepted the terms, regarded of how they have become a member
- [ ] Server to allow each Hub to specify a set of terms that users agree to abide by when they Apply for / Join a Hub
- [ ] If terms are set, then the client should make those terms available to the User as part of the Apply / Join UI
- [ ] Rules should have the following sections: behavior, content, ...
- [ ] Content license should be chosen from a pre-defined list
- [ ] Content license should be visible / shown in multiple places e.g. on callout, footer bar of space etc?

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by larssondenise** [comment]
Terminology update: "Hub" → "Space" throughout. No change to scope.
