### ISSUE TITLE
Innovation Library for users

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1042]
## Description
The content in the innovation library is growing and they are one of our key assets on the platform. However, it is currently hidden in the administration or if you open a whiteboard and browse for additional templates. Also for demonstration purposes, it is very valuable but more difficult to explain since it is so hidden. 

## Initiative / goal
Allowing any user to browse through the contents of the Innovation Library

### Hypothesis
The content in the innovation library can really help users on their innovation journey and helps us in our sales.

## Acceptance criteria and must have scope
- [ ] Innovation Packs are visible and browsable
- [ ] Also the whiteboard, innovation flow and post templates separately
- [ ] For now only to see not to directly import or add new templates
- [ ] Innovation pack profile page added

## Additional information
example: itk.mitre.org

## Stakeholders
DSIH
Digicampus
...

## Timeline
Q2

## Design
Figma file:
https://www.figma.com/file/EJFZQmkQ6ZxQTLkF0h9UES/Innovation-Library?type=design&node-id=0%3A1&t=b4g8lTFd2oSRdmj2-1

**Comment by larssondenise** [comment]
@techsmyth @SimoneZaza I have added an issue for the innovation pack profile & one for the innovation library platform page. Something that is missing?
