### ISSUE TITLE
Analytics + monitoring: Dedicated elastic cluster

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1044]
## Description
Moving to a longer term monitoring setup whereby the monitoring is isolated from the production environment

## Initiative / goal
Operational Monitoring

### Hypothesis
By having the operational monitoring separated from the platform cluster that it is more maintainable + robust

## Acceptance criteria and must have scope
- [ ] Alkemio elastic cluster for production, with the following indexes: APM, Op monitoring, alanytics
- [ ] Moving indexes over
- [ ] Ensuring agents are pointed to the new cluster / index location

tbd 
- [ ] Alkemio to use a platinum subscription from Elastic, either purchased or via a startup programme

## Stakeholders
Alkemio devops admin
Hub admins

## Timeline
tbd

## Additial information
Currently the production indexes are in mulitiple places: 
- Op mon in prod cluster
- apm, analytics in acc cluster

This puts both a dependence on Acc cluster for analytics

it also means that elastic resource consumption can impct production cluster performance
