### ISSUE TITLE
Licensing: Quota / resource management: Documents

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1050]
## Description
As the activity increases, so will the content / users / challenges within a Space. There will be a point that we need to decide on limiting this / letting people pay more if they want to grow

## Initiative / goal
Tying platform usage to subscriptions

## Acceptance criteria and must have scope
- [ ] Allow deletion of documents to free up space
- [ ] Allow management of document sizes per space
- [ ] Allow spaces to have different limits that are tied to licenses / other means of updating their limits that are accessible only to platform admins
- [ ] allow deletion of documents by space admins

## Design
Look at what platforms such as Wingback can provide.

Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
