### ISSUE TITLE
LinkedIn: connected accounts + usage for populating Alkemio profiles + messages

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1058]
## Description
As a user I want to be able to connect my LinkedIn profile to my Alkemio profile, and then to use this to populate my data (picture, title etc) as well as potentially post messages

## Initiative / goal
Network effect

### Hypothesis
Making it easier to integrate with existing social networks reduces barriers to adoption

## Acceptance criteria and must have scope
- [ ] Allow connecting LinkedIn profiles to the Alkemio profile
- [ ] Allow retrieving of profile information directly from LinkedIn profile
- [ ] Allow posting to Linkedin from Alkemio

## Stakeholders
DSIH

## Timeline
tbd
## Design
Figma file:
