### ISSUE TITLE
Community: Invite non-platform users to join a Space

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1070]
## Description
As an Space admin, I want to be able to invite users that are not yet on Alkemio users to join my community 

## Initiative / goal
Community Building

### Hypothesis
Providing the ability for space admins to invite users to their community is key to helping them make their community come onto Alkemio

## Acceptance criteria and must have scope
- [ ] Able to specify an email address, plus first + last name for a user to be invited to the Space
- [ ] Admins able to choose whether the new user to receive an email inviting them to join the Space, which will first involve them creating an Alkemio account
- [ ] Platform to create a new user profile with the provided information so that the invitation can be there for the user when they create an account
- [ ] Admins able to bulk upload user details from a spreadsheet

Note: relies on the invite existing users to platform epic for prompting users to join spaces they have invites to. 

TBD: it could be best near term that admins are able to bulk upload user details for membership to the space, but that they choose to make a custom email. The advantage is that they can then fully control the text that is sent. 

TBD: also create the account for the user on kratos?
 
## Stakeholders
VNG + Digital Twin 

## Timeline
asap

## Design
Figma file:
tbd

## Additional Context
https://github.com/ory/kratos/issues/2525

**Comment by techsmyth** [comment]
Closing as have taken this work into the invite users to space epic as very closely related now.
