### ISSUE TITLE
Client: Simplified logic via streamlined server api

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1073]
## Description
Reducing the complexity of the client code base, as well as the data loaded to display the pages to users, is key to a high quality user experience

## Initiative / goal
Team productivity
User experience

### Hypothesis
There are substantial set of improvements that we would can make on the client that will improve its overall maintainability

## Acceptance criteria and must have scope

- [ ] roles query to return full entities

Direct entity access:
- [ ] Allow direct access to the following entities under a top level "direct" entity: 
* Community
* Collaboration
* Context
* Profile
* Callout
* Post
* Whiteboard
* InnovationFlow
* WhiteboardTemplate
* InnovationFlowTemplate
- [ ] Remove top level queries for whiteboard, community, context, collaboration (replaced by above)
- [ ] Client code base updated to use direct access for components

Current user
- [ ] Allow direct access to all information needed for the current user via a refreshed "me" query
- authenticated: boolean (user logged in or not)
- userProfile: User
- hasProfile: boolean
- invitations: Invitation[]
- applications: Application[]
- spaceMemberships: Space[]
- [ ] Remove "meHasProfile" query
- [ ] Client updated to replace usage of userRoles for the current user

Queries tidied up:
- [ ] User query expanded to have the following filter parameters:
- IDs: just return the users for the provided IDs
- [ ] Remove userByIDs query
- [ ] Platform to have field resolvers to move the following top level queries to be there: metadata, configuration, authorization
- [ ] Client updated to use new way to query users by IDs, how field resolvers are accessed

## Stakeholders
Development

## Timeline
Q2

## Design
https://hackmd.io/fBJs8CgyTbKDJ1o-iO_o4Q

- usersByID
- usersWith Credential
