### ISSUE TITLE
Innovation Flow: Lifecycles v2

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#1077]
## Description
As an architect I want to have a clear design pattern lifecycles so that the logic is more encapsulated and flexible, with options to upgrade

## Acceptance criteria

- [ ] Design for next phase of lifecycles
- [ ] Lifecycles for challenge, opportunity and applications refactored to use the new approach
- [ ] Lifecycles properly initialized on creation
- [ ] Race condition removed
- [ ] Approach for adding / updating lifecycles via migrations

Note: do we drop the usage of mutation checks for privileges on events + just rely on the lifecycle definition to do this?

## Additional Context
Switch to using a factory for creating / upgrading lifecycles?
Upgrading to be done via custom code plugin that is triggered via migrations?

See also client-1779 for an example of what is happening.
