### ISSUE TITLE
Challenge/Opportunity refresh

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1082]
## Description
Simplifying the Challenge and Opportunity pages to make it more clear that they're in a Space/Challenge, have callouts in context for better interaction and the possibility to hide the opportunity tab on a Challenge page to be able to create a simple Challenge version

## Initiative / goal
User engagement, guidance for users, 

### Hypothesis
Challenges will be easier and nicer to use

## Acceptance criteria and must have scope
- [x] Banner update for Challenge and Opportunity
- [x] Callouts in context
- [x] About tab to become dialog (as in Space)
- [x] (no knowledge tab on Ch/Opp level, just Dashboard & Contribute)
- [ ] Possibility to hide the Opportunity tab on Challenges (option to be set in the Challenge settings)
- [ ] Update of settings tab
- [ ] All above to be mobile friendly
- [ ] Private opportunity

## Stakeholders
UWV, VNG, Velokonzept

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
https://www.figma.com/file/BZR4ozFba6KLI0RvfBstDV/Challenges-refresh?type=design&node-id=0%3A1&t=DOYXW4Lw7N4GRd5Q-1
