### ISSUE TITLE
Client: Optimize user responsiveness

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1091]
## Description
Optimizing the client load time for faster page loads and better responsiveness

Improving the build setup for the client so that the user has less data to download
Allowing code to be downloaded on demand
Improving developer productivity via build times

## Initiative / goal
User engagement

### Hypothesis
Downloading less code will allow the users to see and interact with the platform quicker
Slow response times reduce the usage of web platforms

## Acceptance criteria and must have scope
- [ ] Evaluate optimizing how the client package is created and how to reduce size by pruning
- [ ] Analyze the startup sequence of the client + what queries are blocking / loading too much data
- [ ] Analyze our usage of Apollo to see if we an load less data
- [ ] Investigate ability to download some of the packages on demand e.g. whiteboard
- [ ] Analyze the compute load on the client 
- [ ] Analyze how the responsiveness of the server changes depending on the number of credentials held by a user: 10, 50, 250 creds + page load times
- [ ] ...

Note that there are also tools that help with this kind of analysis, especially re JS packages. It may be that there are some quick wins re packages used in the client (e.g. use a much lighter version of XState, improve usage of webpack etc).

Note: Try the client on a much less powerful device e.g. on an old tablet the application was basically not usable.

## Stakeholders
Product

## Timeline
Q3 2023

**Comment by reactoholic** [comment]
## forewardRef:
Too many **forewardRef**s makes the code too complex, hard to maintain, scale and in some edge cases more memory consuming. Also, we are using **useImperativeHandle** in conjunction to the **ref**s which the React team itself suggest avoiding using. Basically, we relay too much on the **ref**s which are touching the DOM directly. This is a **React anti-pattern** and such implementation is not reactive, meaning too many manual handlings to update UI.

**Comment by reactoholic** [comment]
## Adding whole object in dependency arrays:

We must avoid adding entire objects in dependency arrays when in reality we are using just part of it. Example of what we should avoid:

<img width="1072" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0svQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a904e20fc0a2a67fca7239e842c2ef665e37705b/image.png" alt="image.png" />

We can and must add **only** the key from the object (in this case `user?.user.id`) which is really being used in the given hook.

**Comment by techsmyth** [comment]
> ## forewardRef:
> Too many **forewardRef**s makes the code too complex, hard to maintain, scale and in some edge cases more memory consuming. Also, we are using **useImperativeHandle** in conjunction to the **ref**s which the React team itself suggest avoiding using. Basically, we relay too much on the **ref**s which are touching the DOM directly. This is a **React anti-pattern** and such implementation is not reactive, meaning too many manual handlings to update UI.

Good point. There are indeed quite a few inside of the codebase. What is the suggested path forward, analyze each usage + decide if it is appropriate or are there some ones that should be removed near term?

**Comment by reactoholic** [comment]
> > ## forewardRef:
> > Too many **forewardRef**s makes the code too complex, hard to maintain, scale and in some edge cases more memory consuming. Also, we are using **useImperativeHandle** in conjunction to the **ref**s which the React team itself suggest avoiding using. Basically, we relay too much on the **ref**s which are touching the DOM directly. This is a **React anti-pattern** and such implementation is not reactive, meaning too many manual handlings to update UI.
> 
> Good point. There are indeed quite a few inside of the codebase. What is the suggested path forward, analyze each usage + decide if it is appropriate or are there some ones that should be removed near term?

Analyzing should be present for sure, because removing a **forewardRef** is a tricky thing to do because of the way it works. If you remove it, it might work fine in one place but break other components that were relying on it. When it comes to removing such thing refactor is inevitable, but it doesn't necessarily have to be a big one, so a dedicated ticket for analyzing and removing **forewardRef**s must be created in my opinion and we should work it soon because the more we use these ref components the more tech dept we're stacking up.
