### ISSUE TITLE
Client: Technical debt -  round 3

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1094]
## Description
Reducing the complexity of the client code base, as well as the data loaded to display the pages to users, is key to a high quality user experience
Tidying up the client code base means for better longer term productivity and maintainability

## Initiative / goal
Maintainability
Team productivity
User experience

### Hypothesis
Addressing technical debt is essential for long term platform health
There are substantial set of improvements that we would can make on the client that will improve its overall maintainability

## Acceptance criteria and must have scope
- [ ] Analysis of next tech debt to be addressed in the client

Hit list:
- [ ] Expanded usage of lookup to directly access entities
- [ ] roles query to return full entities
- [ ] tbd

## Stakeholders
Development

## Timeline
Q4

## Design
https://hackmd.io/fBJs8CgyTbKDJ1o-iO_o4Q
