### ISSUE TITLE
Reduce code download by users

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1095]
## Description
Improving the build setup for the client so that the user has less data to download
Allowing code to be downloaded on demand
Improving developer productivity via build times

## Initiative / goal
Usability

### Hypothesis
Downloading less code will allow the users to see and interact with the platform quicker

## Acceptance criteria and must have scope
- [ ] Analysis of our usage of webpack and packages
- [ ] Investigate ability to download some of the packages on demand e.g. whiteboard
- [ ] Investigate options to streamline our build process
- [ ] Identity into a separate package?

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by techsmyth** [comment]
Effort captured in another epic
