### ISSUE TITLE
Subspace invitations

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1100]
## Description
Polishing the functionality around invitations / applications
Stronger support for different policies on a community

## Initiative / goal
Making the invitation / application process as smooth as possible

### Hypothesis
Invitations / applications are the first steps users often have with Alkemio, so it has to be a smooth experience

## Acceptance criteria and must have scope
- [ ] New Space setting to allow Subspace admins to send space invites
- [ ] Invitation option on Subspace level
- [ ] If admin doesn't have Space invite rights: do not allow sending invites or make specific invites for this case? Or make very clear that you can only invite people within the space?
- [ ] Clarity in invitation (for both sides) that this is an invite for both Subspace and parent Space

## Stakeholders
S&D

## Design
Figma file V1, not yet per role: 
https://www.figma.com/file/y7EcC4ImZuFvbckKNdE1Vt/Invitations?type=design&node-id=1%3A2&mode=design&t=2n6WOLZLdmpYyjcb-1

Old:
Also consider
- [ ] Membership policy stronger supported, not just a set of overlapping preferences

**Comment by techsmyth** [comment]
@SimoneZaza worthwhile to also think this one through for orgs / VCs...

Also: is invite only for existing platform users or also for externals?
