### ISSUE TITLE
Guidance: beta testing with Alkemio community 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1101]
## Description
Allowing more of the Alkemio community to try out the guidance engine for helping with usage of the platform.

## Initiative / goal
Guidance on the platform

### Hypothesis
GenAI needs to be rolled out on the platform carefully

## Acceptance criteria and must have scope
- [ ] Update the data that is fed into guidance engine e.g. key messages document from Fintan
- [ ] Allow users to give thumbs up / down on each answer
- [ ] Write up of how this is safe / design choices made
- [ ] Monitor what questions / answers are arising
- [ ] Plan for how we are going to roll this out
- [ ] Feedback from key external supporters: what have we missed
- [ ] Risk analysis
- [ ] Example roll out scenario: enable for all users and have ops look at all questions + answers

## Stakeholders
Product
Partners

## Timeline
Q3

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
