### ISSUE TITLE
Richer and visible interactions in Space

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1103]
## Description
Users interact with Alkemio primarily through Callouts, and they make up the bulk of the displayed pages. There are several aspects of how they are displayed / how they are interacted with to be refined. 

## Initiative / goal
Usability

### Hypothesis
Improving callouts usability has a big effect on overall platform usability

## Acceptance criteria and must have scope
Scope: client only display changes. 
- [x] Allowing collection of links to be closed
- [ ] something to ensure the tags take less space
- [ ] Callouts that are closed with no comments to not display the messages "you cannot add content / this callout is closed"

Idea: callouts in draft to be expandable (for later) 

Visual refresh of collection of links
- [ ] Reference to have ReferenceType field, default to General
- [ ] Reference types: 
- General
- Image
- Video
- Document
- News
- Reference
- Diagram
- [ ] Adding a new reference the user can choose the type
- [ ] Each reference type has its own icon

## Stakeholders
Power users / admins
TIP

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by techsmyth** [comment]
Closing in favor of #1623
