### ISSUE TITLE
Notifications: Grouping + additional types

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1104]
## Description
Addition of links / calendar events are key community events that I want to be informed of

## Initiative / goal
Usage

### Hypothesis
Having users notified of calendar events and the addition of new links to a collection of links will trigger people to come back to the platform

## Acceptance criteria and must have scope
- [ ] Notification with associated preference for when a new link is added to a collection of links callout
- [ ] Subscription to real time update other clients when a new link is added
- [ ] Allow events to be published / in draft, with control over whether to publish it or not when making it visible
- user applications?
- comments on calendar events?

## Stakeholders
Power usres

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
