### ISSUE TITLE
NEEDED? Community Invitations: Allowing inviting many (external) users at once

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1105]
## Description
Allowing community managers to bring their community into Alkemio in bulk, via uploading many emails at once

## Initiative / goal
Engaging the community; usage

### Hypothesis
Making it easy to carry out many invitations at once makes it more likely community admins will invite their whole community

## Acceptance criteria and must have scope
- [ ] Allow admins to upload a list of users to be invited. tbd: spreadsheet
- [ ] Provide feedback for each email address whether the invitation succeeded or not?
- [ ] Server to be smart in recognizing if an email address is already registered + then doing an existing user invitation

## Stakeholders
VNG
Data Autonomy

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by techsmyth** [comment]
@larssondenise @hoyterutteman is this not already done?
