### ISSUE TITLE
Subspace Templates: Usage + management of platform templates

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1120]
## Description
The platform is most valuable when you set it up in a powerful way. The basic tools for co-creation and other usages are there, but the outcome depends on how one uses these tools. Making the setup of a Challenge (or subSpace) templatable will unlock huge value since the outcome will less depend on the individual skills, time, and effort put in by the admin/lead, and it will drastically improve the efficiency for the Alkemio team members that need to prepare Spaces and Challenges for demonstration purposes. 

## Initiative / goal
Sharing of best practices. Content on the platform.

### Hypothesis
Innovation flows are a major addition with a lot of added value for wider users to see how to use the platform effectively. 

## Acceptance criteria and must have scope
Note: only covers combination of innovation flow + callouts, not the context / community. 

- [ ] Allow saving a subspace setup as a collaboration template
- [ ] Innovation library extended to display them. Preview to re-use existing UX components. 
- [ ] Option to choose from template when you create a subspace
- [ ] Allow management of platform level collaboration flows directly on the platform (so not hard coded in the server repo)
- [ ] No more creation of Innovation Flow Templates
- [ ] Innovation Flow template test suits converted to be Collaboration Template test suits

Other:
- [ ] Add context/description
- [ ] Creating a template by "save as template"
- Keep it simple
- Expandable content
- Real-life previews that can be checked? eg in welcome space, add link in description, only for our templates
- [ ] Check when you apply a new template: do you want to remove all existing callouts?
- [ ] Keep in consideration that we'll most likely have space templates on our wish list for later as well
- [ ] Can you edit a template? No
- [ ] Option to choose where you want to store this template when saving as template
- [ ] Currently we control visibility on the template pack level, but shouldn't a user be able to control this per template? Not for now. 
- [ ] "Copy this subspace" vs "templates" 
- I'm creating a subspace and want to copy it a couple of times 
- [ ] Visuals and images in descriptions need to be copied to the new storage bucket
- [ ] When a subspace is already created, you can still apply a new template:
- Existing callouts remain
- Flow is changed to the template flow
- template callouts are added

Content of the Collaboration template:
- Innovation flow
- Default Callouts in- and outside of flow
- TBD: Opportunities/sub/sub spaces???

## Stakeholders
UWV, TIP, VNG, ...

## Design
The update flow will still be rough for collaboration templates after this epic: The current route is to 
a) create a subspace from a collaboration template
b) edit the collaboration flow including callouts on the subspace
c) save the collaboration flow as a collaboration template

**Comment by techsmyth** [comment]
@SimoneZaza can you please split this epic into two, one as a bucket to catch all open issues on templates + one for the actual subspace template client work? In terms of scope to get this through I would suggest we keep to "save-as" for creating the template, and do not allow editing of the actual collaboration flow / callouts in the templates mgmt for now.

**Comment by SimoneZaza** [comment]
@techsmyth I had a look and could actually close most of them (moved 1). They were no longer relevant with the new Innovation flow in place. Regarding the other point, I fully agree on using just the 'save as', that's indeed how I imagined it as well. Not even sure if we should go for a full edit flow later on, since this will be quite challenging UI wise + for people to understand. I would prefer another approach, eg where a subspace "knows" that it is used as a template, and the template can be updated by changing that subspace and clicking an "update template" button or something like that. But that would be for way later of course.
