### ISSUE TITLE
Journey settings v2: Space platform info, membership

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1123]
## Description
Although an admin can do _way_ more on the platform than ~ a year ago, the settings tab is still sort of the same. New settings were added within the tabs and we added a few tabs since then, but a proper update of the settings page hasn't been done for a long time. This caused the settings page to be a bit unstructured and difficult to navigate, making it harder for (new) admins to shape their journey pages as they seem fit.

## Initiative / goal
Updating the admin settings will ease the flow of setting up a Journey, improving the early experience for new admins with the platfom. 

### Hypothesis
Simplifying the admin of spaces / challenges makes for more usage

## Acceptance criteria and must have scope
- [x] Simplified setup of Space 
- [x] Simplified community management + roles for each Member
- [x] Platform level settings for a Space separated out
- [x] Space admins no longer able to directly add members to a space. 

## Stakeholders
Support team

## Timeline
Q2

## Design

Figma file:
https://www.figma.com/file/t3XQACWEsDa3r8YPyihmsp/Settings---refresh-Q2%2F3-2023?type=design&node-id=0%3A1&t=xgrnA3AifjMFwzDK-1

**Comment by techsmyth** [comment]
Closing as have created a separate epic for challenge settings / membership policy work that is remaining (split the epic)
