### ISSUE TITLE
Multiple user editing of posts

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1126]
## Description
Allowing multiple users to work in real time on a shared document (markdown)

## Initiative / goal
Collaboration, allowing users to get work done on the platform

### Hypothesis
Allowing users to create content together, for example take notes in a meeting or brainstorm, is important for people working together. 

## Acceptance criteria and must have scope
Step 1: Multi-user, not simultaneously
- [ ] Add "Who can edit" concept that is currently there for whiteboards to callouts and posts
- [ ] Add label for last edit (timestamp+who)
- [ ] Clicking on/near the label opens list for history
- No need to be able to revert changes
Step 2: Real time collaborative editing
- [ ] ...
- [ ] 

Old:
- [ ] Document concept added to the platform, which then can be worked on in a similar way to realtime whiteboards
- [ ] ...

## Stakeholders
TIP

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by SimoneZaza** [comment]
duplicate #1552
