### ISSUE TITLE
Platform Updates / News

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1128]
## Description
Allowing platform admins to share updates to all users e.g. new releases

## Initiative / goal
Community engagement

### Hypothesis
Providing users with more information about platform news

## Acceptance criteria and must have scope
- [ ] Creating new updates via platform admin similar to "update from the leads" on spaces
- [ ] When a user logs in the person sees the last update, and can click it away while specifying "do not show again"
- [ ] Client to save what was the last update shown and clicked away
- [ ] User able to see all updates
- [ ] Popup to notify users of the update / news

Duration?
Protected under additional rights? Draft ==> Publish?
Ability to notify particular groups of users with an update? E.g. tell space / challenge admins that there is new functionality they can use.
Email or not?
Content translatable?

## Stakeholders
platform administrations

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by larssondenise** [comment]
Terminology update: "space / challenge admins" → "Space/Subspace admins". No change to scope.
