### ISSUE TITLE
I: Alkemio Plugin Architecture

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1129]
## Description
Enabling plugins to Alkemio is critical to realising the full potential: we cannot build it all
Allowing for easier integrations is a first step. 

The sooner we start designing for plugins the better our understanding builds up and the easier it is to roll this out widely in the platform.

## Initiative / goal
Allowing wider usage of Alkemio in different custom use cases
Allowing integrations into other tooling

### Hypothesis
As communities of users and organizations start to depend on Alkemio, they will need to be able to have custom extensions.

## Acceptance criteria and must have scope
- [ ] Roadmap strategy covering the following aspects:
- API management
- Developer summort
- Accreditation + evaluation of plugins re deploying in plugin store
- management + deployment, especially around security e.g. signing of packages, where plugins are deployed (e.g. container, remote hosting vs local)
- componentisation implications on client-web
- extension points supported / what is the api that plugins are allowed to access?
- notification of events
- creating a plugin store
- [ ] Evaluate other platforms plugin architectures
- Consider: client-server platforms, protocol platforms, open source communities
- Examples: Elastic-Kibana, Element (Matrix protocol), Ocean (SLB), Salesforce, Apollo, Miro, ...
- [ ] Evaluate usage of webhooks or similar e.g. WASM for deployment of functionality

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
