### ISSUE TITLE
Welcome page v1 + foundation site 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1131]
## Description
Creation of a landing page that has much richer information, and that can be extended without dedicated development effort. 

## Initiative / goal
Productisation

### Hypothesis
A good landing page is critical to generate new leads and sales
The ability to rapidly update the landing page is important to allow the marketing and sales team to get the right messages to the market

## Acceptance criteria and must have scope
- [ ] Content specific to Alkemio platform removed from alkemio.org site and hosted on website dedicated to the platform
- [ ] Ability to see and track user interactions both within the landing page and where they land in the platform
- [ ] UX design for the layout of the landing page created
- [ ] Clarity on where the landing page can be hosted, both in terms of content serving as well as what URL it can use
- [ ] Support for multiple languages: EN, NL, DE

Non-functional:
- [ ] Ability to leverage Content Delivery Networks (CDNs) for rapid load time anywhere in the world
- [ ] Ability to load very fast
- [ ] Ability to detect if a user is logged into Alkemio or not?

Notes from offsite: https://alkem.io/building-alkemio-org/challenges/teamoffsiteseptemb-9083/collaboration/landingpage-1733

## Stakeholders
Sales + Marketing
Investors

## Timeline
asap

## Design
Figma file:
