### ISSUE TITLE
Multi-user whiteboard: production beta

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1132]
## Description
Taking the capability developed for the technical demonstrator through to production so that it is available on the platform to all users (if they have the appropriate subscription)

## Initiative / goal
Collaboration

### Hypothesis
That multi-user white boards are a key value add for the platform. 

## Acceptance criteria and must have scope
Depends on storage epic for handling of images: Content not stored within the relational database 

Scope:
- [ ] Additional controls around who can edit / view a whiteboard

Later / part of collaboration service:
- [ ] Whiteboards are saved automatically 
- [ ] Usage of shared state across containers (e.g. redis) as an alternative to the current broadcast mechanism
- [ ] Usage of y.js protocol for conflict resolution (better scalability)
- [ ] Creation of collaboration setup that can also be re-used for document editing (markdown / hocuspocus)

## Stakeholders
Process guides
Product

## Timeline
End October

## Design
tbd
