### ISSUE TITLE
QA: Test suite user authentication flows

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1133]
## Description
A test suite covering expected user interaction scenarios

## Initiative / goal
Quality experience for users

### Hypothesis
A robust test suite covering user identity related flows is critical to avoid any issues with users being able to login

## Acceptance criteria and must have scope
- [ ] Defined scenarios for user authentication and redirects, including a) bringing the user back to where they started b) interaction with custom home pages c) interaction with landing page
- [ ] Test scenarios automated via the browser (to discuss what this means)
- [ ] Test scenarios executable in the following builds: tbd

## Stakeholders
Product

## Timeline
tbd

## Design
tbd
