### ISSUE TITLE
Kratos 1.0

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1142]
## Description
Ory Kratos has reached 1.0, with several nice enhancements and security improvements to adopt

## Initiative / goal
Security
Maintenance

### Hypothesis
Being on recent versions of Kratos is important for securing the platform

## Acceptance criteria and must have scope
- [ ] Evaluate implications of moving to Kratos 1.0
- [ ] Deploy Kratos 1.0 in production
- [ ] Spike enabling of authentication flow to allow also using non-interactive logins with Microsoft identities

## Stakeholders
DevOps

## Timeline
tbd
