### ISSUE TITLE
Storage per entity, whiteboard images

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1144]
## Description
Allowing storage and management per entity e.g. whiteboard, callout etc

## Initiative / goal
Whiteboard RT / scalability

### Hypothesis
Content (images etc) need to be stored within the scope of a profile, so within the scope of an entity

## Acceptance criteria and must have scope
- [ ] Each profile to have a storage bucket
- [ ] Each profile storage bucket reports to a StorageAggregator
- [ ] The StorageAggregator is able to display the list of entities that it is managing data for, with links to each entity
- [ ] api service to allow looking up the URL for a given profile ID
- [ ] When a profile is deleted, it should take care to delete all the documents in its storage bucket
- [ ] Whiteboards converted to storing images in documents for new image uploads
- [ ] Whiteboards can be converted to move images out of an existing whiteboard + store a documents
- [ ] Whiteboards in production are converted using the mutation to move images out of a whiteboard content
- [ ] refreshed storage admin interface for spaces / challenges to leverage the new StorageAggregator entity

## Stakeholders
Sys admin
Power users

## Timeline
asap - there are multiple server errors showing that the storage of documents away from the entity is causing issues

## Design
Figma file:
