### ISSUE TITLE
Tracking: refresh of contributions monitoring

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1149]
## Description
Expand the set of activity event types
Time based activity tracking

Areas:
- logging of activity
- display of recent contributions
- analysis of north star metric

Note: the time based way of tracking editing likely means the client also needs to be able to trigger activity log entries etc

## Initiative / goal
Understanding what is happening on the platform

### Hypothesis
Admins expect to be able to see on-going activity

## Acceptance criteria and must have scope
- [ ] Description of what contributions are (north star metrics), as markdown file in alkemio repo
- [ ] Extend activity tracking to have additional entry types 
- [ ] Time based submission of activity
- [ ] Only display one event when there are multiple activity log entries registered
- [ ] ...

Events that need to be added:
- updating of content e.g. vision
- adding of links to a collection of links
- updating of whiteboards
- ...

## Stakeholders
Investors

## Timeline
tbd

## Design
Figma file:
