### ISSUE TITLE
Search: callouts

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1155]
## Description
More and more content in the platform is in form of callouts, but the framing of a callout is not currently searched

## Initiative / goal
Usability

### Hypothesis
Allowing users to find callouts easier will help with getting people to the right content

## Acceptance criteria and must have scope
- [ ] Search query results to include Callouts as a type, both globally and within a specified Space
- [ ] UX design for how to display the callouts
- [ ] Client updated to display Callout search results

## Stakeholders
All users

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by techsmyth** [comment]
Moved remainder into search performance epic
