### ISSUE TITLE
Design System: across UX + development

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1156]
## Description
When creating designs in Figma, too much time is spent on looking or recreating the right components, finding the right icons, etc. 

## Initiative / goal
Updating the Design system to include all the icons we use, and basic components that can be easily adjusted, all with proper styling and use of auto-layout so that tweaking these components will be very fast.

### Hypothesis
By upgrading the design system the team will be more efficient when creating new designs. 

## Acceptance criteria and must have scope
- [ ] All icons that we use on the platform to be included, with easy to find names
- [ ] Buttons checked to all be properly created (with correct font style, auto-layout, etc)
- [ ] All blocks to be frames with auto-layout properly implemented on multiple levels, so it becomes very easy to adjust content
- [ ] Latest designs to be added to the Design system (Powered by, homepage, new callout flow, header blocks, etc)

## Stakeholders
UX team, Communications team

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by ayoolafelix** [comment]
Is this repository open-source? I would like to help

**Comment by SimoneZaza** [comment]
hi @ayoolafelix, good to hear! Can you send me an email at simone@alkem.io so we can have a chat on what you would like to do and how you can help? 😊
