### ISSUE TITLE
Homepage / Dashboard: Private workspace

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1157]
## Description
Allowing users to have their own private workspace, to explore functionality such as whiteboards, posts

## Initiative / goal
Home page

### Hypothesis
Allowing users to have their own private whitespace / access to other collaboration capabilities is important to get them started on the platform

## Acceptance criteria and must have scope
- [ ] Users able to create and work with their own whiteboards
- [ ] Users able to pin content such as favorite journeys, key users etc
- [ ] Users able to save links / upload documents
- [ ] Users able to save the callouts they created as templates in their personal space as well

## Stakeholders
Process guides

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by larssondenise** [comment]
Terminology update: "favorite journeys" → "favorite Spaces" (Journey was the old umbrella term for Hub/Challenge/Opportunity). No change to scope.
