### ISSUE TITLE
Callout Templates: Spaces

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1158]
## Description
Adding support for callout templates, and a more scalable structure for callouts that is used in templates

## Initiative / goal
Guidance for users

## Description
Allowing for callouts templates to be exposed in the UI

## Initiative / goal
Sharing of best practices. Content on the platform.

### Hypothesis
Most of the content that would really help the community is actually callouts, rather than post templates.

This epic provides the base for callout templates usage, and also innovation flow templates. 

## Acceptance criteria and must have scope
- [ ] Use the callout templates api and updated callout api to engage users with callout templates
- [ ] Callout templates supported for Spaces
- [ ] Allow users with rights to create callout templates in the Space from callouts
- [ ] Allow having the ability to create callout templates from callouts to be enabled / disabled at Space level
- [ ] Allow users to select from callout templates at the points where they are adding new callouts on the platform

## Stakeholders
UWV, TIP, VNG, ...

## Timeline
tbd

## Design

Logical domain model envisaged:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWswIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74b9e5e7fcadcd8b5850cc1dda8b23a4766b5c1d/image.png)
