### ISSUE TITLE
Digicampus challenge promotion

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1159]
## Description
Promotion of the proactive dienstverlening to be a space

## Initiative / goal
Engagement

### Hypothesis
Having this challenge as a space is the right thing, so the community can develop

## Acceptance criteria and must have scope
- [ ] Conversion service updated
- [ ] Storage aggregator on opportunity
- [ ] Vallidated with copy of production data

## Stakeholders
Digicampus

## Timeline
End Oct
