### ISSUE TITLE
Reporting: Passive usage

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1162]
## Description
Providing additional insights into platform usage for sharing with investors
- As a team member, I want to know how many people stop using the platform. I do not really care about people deleting their account, it is more about people signing up and not using the platform anymore.

## Initiative / goal
Funding, understanding platform usage

### Hypothesis
A lot more can be learned about how the platform is used + key trends

## Acceptance criteria and must have scope
- [ ] See how many unauthenticated users are on the platform per day (hour?)
- [ ] See how many authenticated users are on the platform per day (hour?)
- [ ] Slice data per global page
- [ ] Slice data per Space
- [ ] Slice above data per feature (not per page):
  - [ ] Whiteboards 
  - [ ] "Spaces" (all grouped together)
  - [ ] "Subspaces" (all grouped together)
- [ ] See how often the same (authenticated) user visited the platform in the last 6 months (to measure if users are returning or not)
- [ ] Also for website (product team)
- [ ] Decent setup, fast enough

## Stakeholders
Product team, Investors
