### ISSUE TITLE
Refresh Spaces page (former Challenges page)

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1166]
## Description
Currently, we don't have a clear page where Spaces "live". This makes the structure of Alkemio for a user difficult to understand. Also, the Challenges page is difficult to understand and to navigate at the moment.
Spaces are a core concept of Alkemio, they need a clear place to be explored.

## Initiative / goal
To create a go-to place for the exploration of all Spaces on the platform and their Challenges

## Acceptance criteria and must have scope
- [ ] Understand the needs of users when visiting this page
- [ ] Give a clear overview of all Spaces with the possibility to filter on tags and search keywords
- [ ] Show Challenges in a way where it's clear to which space they belong and whether they're public or private

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
