### ISSUE TITLE
All whiteboards are RT

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1167]
## Initiative / goal
Kill the single-user whiteboard and migrate the old ones to multi-user

### Hypothesis
What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit.

### Platform functionality
- [ ] Remove single-user (#5400 / #3548)
- [ ] Migrate whiteboards (#3411 / #3542)
-----
- [ ] Change Whiteboard RT flag to set the amount of people who can edit at a time 1 or 10 (#3556)
- [ ] After 2 hours of inactivity, go from contributor to viewer status (design needed, refresh page/step out step in) (#3557 / #5433)
-----
- [x] Default settings: creator + admin can edit
- [ ] Designs for how many users are in vs how many are allowed, what happens when you try to join when it's full, etc, etc need to come in as well. Add note: this space currently doesnt support, contact sales to.. etc. (### follow asap)
- [ ] All labels+translations that now state WhiteboardRT should be just Whiteboard (# follows)

### Communicating
- [ ] Release notification on platform
- [ ] Enable for Spaces that have a Premium subscription
- [ ] Email to all paying partners informing about the change (COMM)
- [ ] Updating help section website: how to use WB (#236)
- [ ] Updating help section website: MUCollab / Why can't I edit / etc (#236)

### Discussion / maybe later / good to keep in mind
- [ ] Flag on callout to make single-user on the collection of whiteboards (maybe second iteration)
- [ ] Setting to select amount of users to collaborate (Active as a contributor) at a time per space, in GA -Space settings (1/5/50?TBD)

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
