### ISSUE TITLE
Infrastructure: Domain per environment

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1171]
## Description
Improving the way domains (DNS) are created and managed on Alkemio

## Initiative / goal
Stability, security

### Hypothesis
Managing the domains via scripts will improve platform robustness and documentation of what was done
Splitting the domains between the different environments will improve security

## Acceptance criteria and must have scope
- [ ] DNS domains provisioned from code
- [ ] Each environment to have a separate domain
- [ ] Certificates automatically renewed for each domain

## Stakeholders
DevOps lead

## Timeline
Q4
