### ISSUE TITLE
Templates: Interaction Space library and platform library

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1175]
## Description
Organization X creates a template in Space A, but also want to use it afterwards in their Space B. This is currently not a smooth process. They need to create a post with whiteboard, then go to their org profile, go to the template pack, add a post, copy everything, then create, then go to Space B and use the template.

## Goal
Super smooth experience for facilitators in using the templates across Spaces with no dead ends.

### Hypothesis
Currently the power of the templates is somewhat downplayed by the not-great ux around them. If we would improve the experience > more usage of templates by our power users > users get more value out of the platform.

## Acceptance Criteria P1
- [ ] **Direct Template Pack Addition from Space**
- As a facilitator, I want to easily use templates across Spaces
 
Optional solutions:
- As a facilitator, I want to add posts directly to my organization's template pack without leaving my current context, so I can build my template packs easily as well as reuse them across Spaces.
- As a facilitator, I want to add a Subspace directly to my organization's template pack without leaving my current context, so I can build my template packs easily as well as reuse them across Spaces.

- [ ] **Full Template Pack Import to Space Library**
As a facilitator starting a new project, I want to easily import an entire methodology to my project, so I can quickly enable my stakeholders to use a curated set of templates without manually adding each one.

- [ ] **Whiteboards from post templates visible in whiteboard template library**
As a product owner, I want clean behavior around whiteboards and posts with whiteboards. I don't want users to create them twice.

**TBD template previews?**

## Stakeholders
SiR Intergov, Opschalingstickets, DSIH ....

## Additional Context
Also check all images in templates + authentication rights!

Inspiration in this Specs: https://github.com/alkem-io/client-web/blob/001-template-pack-ux/specs/001-template-pack-ux/spec.md 
Brainstorm on user flows in whiteboard: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/templates

**Comment by hoyterutteman** [comment]
Move open issues to 1734 @hoyterutteman

**Comment by hoyterutteman** [comment]
@larssondenise to check if saving to template pack from (sub)space is already on the board, otherwise add here

**Comment by hoyterutteman** [comment]
@larssondenise check if we have issue where you see all whiteboards from post templates in the whiteboard templates overview. Other option is to have all whiteboards that are part of a brainstorm methodology in posts (but still able to open just the whiteboard from the template, if you're having a whiteboard. You could still see the description first).
