### ISSUE TITLE
Storage: Improved handling of documents that are uploaded

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1177]
## Description
A set of improvements related to the storage and management of uploaded documents / images on the platform.

## Initiative / goal
Maintainability.
Trust. 

### Hypothesis
The handling of documents stored on the platform needs to be clean. 

## Acceptance criteria and must have scope
- [ ] Saving of new images to a visual removes old documents
- [ ] Creation of Documents during create process should result in the Documents being in the right storage bucket
- [ ] Deletion of documents should remove the underlying content (if not uploaded by someone else)
- [ ] Search in document management
- [ ] ...

## Stakeholders
Admins

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
