### ISSUE TITLE
Licence Framework (Licensing and quotas for subscriptions)

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1180]
## Description

An end to end license framework to enforce quotas on a limited set of functionality.

Establishing a clear framework for management of licenses, that is flexible and leverages known / team understood patterns.

## Initiative / goal

Licensing

### Hypothesis

Licence management encourages more users to pay for usage of the platform.

License management allows differentiated selling of the platform.

## Acceptance criteria and must have scope

- [ ] Enforcement of access to functionality on a per Space basis
- [ ] Enforce the following quotas: Whiteboard concurrent users, max challenges
- [ ] Allow multiple licenses to be held by a Space
- [ ] Central definition of what license types there are, and what quotas as assigned with a given License
- [ ] Allow assigning + removing of licenses from a Space via API
- [ ] Extend space platform management UI to allow adding / removing licenses
- [ ] Allow querying for quotas for a space via api (for each quota type what is the allowance), accessible to members
- [ ] Decorator to use the quota on mutations (applying the quota enforcement)
- [ ] Quota calculation for a given space to be cached for 1 hour
- [ ] Space admins able to see the licenses associated with the Space read only on the Space admin api
- [ ] Allow quotas to be enabled / disabled platform wide, with default being that they are not enabled
- [ ] Visibility to users on why they cannot access the whiteboard / create a new challenge
- [ ] Script ready to go after deployment on production to assign each space the appropriate license
- [ ] Test harness added
- [ ] Default license for new spaces

## Stakeholders

Sales

Space Admins

## Timeline

End Q1

## Design

Link to whiteboard in

Out of scope

- [ ] Payments / billing automated (later)
- [ ] Expanding the set of quotas that are enforced

## Description
The transition to subscriptions has many implications for the platform in terms of licensing / quotas. There will be restrictions based on whether you subscribe to the free, premium or plus version. 

## Initiative / goal
Put licensing and quotas in place to manage the subscription types

## Acceptance criteria and must have scope
- [ ] Quotas on Challenges, Members,
- [ ] Quotas on custom Templates for Innovation Flow, Callouts, and Whiteboards
- [ ] Ability to use community applications
- [ ] Visibility of leading organizations 
- [ ] .....

## Stakeholders
sales

## Additional Notes

**Terminology**: 
From Wingback: Entitlements
Entitlements refer to the rights and permissions that a user or organization has to access and use a particular software service. SaaS entitlements may include a variety of permissions, such as the number of users who are authorized to access the service, the specific features or functionality of the service that a user has access to. The level of access a user has to the data stored in the service, and the measures in place to ensure the security and compliance of the service.

**Comment by techsmyth** [comment]
Merging into other Space Priveleges epic
