### ISSUE TITLE
Welcome page v2

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1189]
## Description
A gathering of next level features to help users new to Alkemio understand the platform and how it can help them. 

## Initiative / goal
Usage

### Hypothesis
An understandable welcome page helps users quickly understand the Alkemio value proposition and be effective in using the platform. 

## Acceptance criteria and must have scope
- [ ] Products pages filled out
- [ ] All content migrated to new layout and tidied up
- [ ] Improved menu system
- [ ] NL language for welcome site

## Stakeholders
Product
Commercial

## Timeline
Q4 2023

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
