### ISSUE TITLE
Storage: Replace IPFS with local storage

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1196]
## Description
IPFS remains the highest risk in terms of reliability in the cluster. 

## Initiative / goal
Improve cluster maintainability, and code maintainability

### Hypothesis
We are not using the features of IPFS, so much better to swap it out

## Acceptance criteria and must have scope
- [ ] Server logic updated to store files on a mapped volume
- [ ] File storage using <storage-bucket-uuid>/<document-uuid> name?
- [ ] IPFS removed from local dev setup, and replaced with a mapped volume (in docker compose?)
- [ ] Cluster updated to work with mapped volumes
- [ ] Script to migrate files referenced from Document entities to follow the new location?
- [ ] IPFS containers removed from clusters
- [ ] Backup scripts updated to work with new setup
- [ ] Infra ops documentation updated to describe new setup
- [ ] ...

## Stakeholders
Dev Ops admin

## Timeline
tbd
