### ISSUE TITLE
Subscriptions: Challenges

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1202]
## Description
Moving towards subscriptions means that we have to put quotas in place as well as enabling or triggering users to upgrade 

## Initiative / goal
Ensuring the platform is ready to move to subscriptions by limiting the number of challenges

### Hypothesis
Users need to be informed about limitations but also be triggered to upgrade

## Acceptance criteria and must have scope
When max. number of Challenges is reached (member)
- [ ] Message when clicking Challenge create button

When max. number of Challenges is reached (admin)
- [ ] Message when clicking Challenge create button
- [ ] Create button Challenges page in Space settings
- [ ] Indication of Challenges left on this Challenges page in Space settings

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
