### ISSUE TITLE
Subscriptions: community

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1203]
## Description
Launching subscriptions means also implementing quotas on the platform 
For now: 

## Initiative / goal
Quotas implemented for number of members 

### Hypothesis
Informing users and triggering admins to upgrade

## Acceptance criteria and must have scope

Admins when space is full:
- [ ] Invitation button opens dialog with message
- [ ] Applications blocks opens dialog with message
- [ ] CTA to get a larger subscription
- [ ] Notification for the admin when there are 10 spots left

For members:l
- [ ] when applying: message that it is full + option to contact the lead
- [ ] Notification triggered for admin that someone wants to enter

When you want to invite more people but the space is full, you can withdraw invitations

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
