### ISSUE TITLE
Reporting: Active usage monitoring

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1213]
## Description
As a team member, I want to know how much the whiteboards and other tools on the platform are used. Whiteboards are a delicate feature, so when there is a bug, I want to know how many people are currently using the whiteboards so I can better estimate the priority.
As a team member, I also want to know realtime usage so I can decide to postpone a release when there is unexpected activity at a time we were planning to release.

## Acceptance criteria

- [ ] How many authenticated + unauthenticated users are currently online on the platform
- [ ] How many users are currently editing a whiteboard
- [ ] How many users are currently viewing a whiteboard
- [ ] Possible to check per user how long they have already been online for? (To filter out people who just didn't close)

## Additional Context
Screen shots / UX designs / data that are relevant.
