### ISSUE TITLE
Infrastructure: Drop usage AWS, Backups maintenance

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1216]
## Description
Improvements in operational mgmt of the cluster

## Initiative / goal
Stability, security

### Hypothesis
A clean operational setup will improve overall security + maintainability

## Acceptance criteria and must have scope
- [ ] Mail service moved from AWS to Azure
- [ ] Backups moved from AWS to another S3 provider, with security to a sufficient level (?)
- [ ] Backups production separated fully from other envs, ideally separate S3 service + separate credentials
- [ ] Decommission active usage of AWS + tidy up backups stored there
- [ ] Able to close the AWS Stichting Alkemio account

## Stakeholders
DevOps lead

## Timeline
Q4

**Comment by techsmyth** [comment]
Merged into production cluster optimization #1377
