### ISSUE TITLE
Process around Error logs

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1219]
## Description

At the moment errors being tracked by the logging tools we are using: Elastic and Sentry.

We need a clear process for addressing the issues proactively, even if the users didn't report them.

## Initiative / goal

By having a process for issues tracking / investigation / prioritization - we are going to have efficient way of addressing production issues that are experienced by users.

### Hypothesis

- Measure for success will be the following attributes:
- Fast investigation and less effort when a new issue appear
- Issues experienced by users addressed proactively
- For "elastics" logs apply alerting on new type of errors

## Acceptance criteria and must have scope

- [ ] Access: Whole dev team have access to and use the logs tools
- [ ] Add a unique identifier for each mutation, that is used:
- Client exceptions to have the unique identifier embedded in the text message
- Elastic error submission to have the error code included
- [ ] Identify what additional information needs to be logged (on-going) + raise issue s/ do it
- [ ] Defined the process regarding checking the logs
- After root cause/ reproduction steps are identified, bug / story is created
- Documented approach for different types of errors
- [ ] Only people in EU / EU national can access the raw data
- [ ] Time for 3 sprints to run the process + then evaluate

## Stakeholders

Development and Product team

## Timeline

Access to Elastics / Sentry / Prod env / Prod db

Timeline: Q1 20224

## Design

Figma file:

Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us

**Comment by SimoneZaza** [comment]
Merged with #1135
