### ISSUE TITLE
Epic: Client component library in Figma

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1220]
## Description

Documenting all components that we use to build our interface. The name of that document would be Component Library.

### Hypothesis

By introducing a component library we're going to speed up and increase quality of both creating the designs/mockups and writing client code.

This potentially will have 2 positive side effects on UX:

- our UI would become more consistent which will slightly improve user experience
- there will be less bugs because there will be less code repetition and in general less code

The component library would be complete when each component is easily identifiable from the design file.

## Acceptance criteria and must have scope

- [ ] Identify with product the key components to be included + agree a list (partial)
- [ ] Browsable gallery of UI components in Figma with those component
- [ ] Figma design files uses components for new designs
- [ ] New designs in Figma are composed from components
- [ ] For each component in the library there's a component in the code
- [ ] there's correspondence between the names of the components in the library and in the code
- [ ] Identify gap list to complete migration
- [ ] Refactor / merge duplicated components

Note: excluding admin UI components

## Stakeholders

Product, client dev, QA

## Timeline

Creating this library would require 2 steps:

- to go through either Figma or app UI, identify components and reimplement them as components in Figma
- review the code, rename components, implement missing components, remove the unneeded ones

## Design

Figma file: YES PLEASE

Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us

**Comment by SimoneZaza** [comment]
To have a look at (suggested by Valentin in the Challenge):
- https://medium.com/@copycatfigma/easiest-way-to-export-figma-to-material-ui-b162c75a6e96
- https://www.copycat.dev/
- One more library that can do that https://builder.io/
- A new framework, natively integrating react, vite, playwright, vitest, builder.io - https://qwik.builder.io/

**Comment by larssondenise** [comment]
@jeroentskui update / clean up. We'll use the platform as the 'source of truth' since we have the plugin to get designs. But we need a guide how to use it / where to components on the platform find for potential future designers.

AI tool to automate the flow?
