### ISSUE TITLE
Whiteboard: Robust connectivity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1231]
## Description
Connectivity to whiteboards to be independent of the the Alkemio server

## Initiative / goal
Real time collaboration experience

### Hypothesis
Having the whiteboard connectivity (web sockets) isolated from the Alkemio server means less disruptions to connections for users. 

Currently whiteboard connections are hosted in the same container as the server, which means that each time a server container restarts, either due a server issue or when a new feature is deployed, that all existing whiteboard connections are dropped - and users have to exit + re-enter the whiteboard to continue. 

This is a major issue as we look to move to more frequent server upgrades - especially as it is expected that server upgrades happen much more frequently than whiteboard collaboration functionality is upgraded.

Further, it is possible with our current usage levels that a single whiteboard collaboration container is sufficient - thereby allowing us in the case of a cluster issue to fall back to a single whiteboard collaboration container

## Acceptance criteria and must have scope
- [ ] Whiteboard collaboration container added to the cluster, responsible for establishing the collaboration rooms that clients connect to using web sockets
- [ ] Whiteboard end points removed from the server container
- [ ] Message bus approach added to allow the whiteboard collaboration service to query for a) authorization checks b) license checks

Note: authorization and license check logic to remain in the server container, but available via message bus responses so that this can easily be easily split out of the server container without impacting the whiteboard collaboration service.
## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
Feb 2024
