### ISSUE TITLE
Guided user onboarding (M)

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1233]
## Description
With a complex platform such as Alkemio, guiding users after they've signed up can bring massive value. A guided flow could help users to directly find the right space(s), whether they are independent new users or sign up for a specific Space. + of course many more opportunities here.

## Initiative / goal
Onboarding users is key to a good experience, and thus ensuring people stay on the paltform

### Hypothesis
90% of the users will need to use a few core functionalities (<20%)

## Acceptance criteria and must have scope
- [ ] Guided flows to some basic principles of the platform:gather insights, share, understand (PRODUCT DEFINITION!) -> e.g., how to add comments, contributions, edit a whiteboard, ...
- [ ] Must be easily adjusted after platform (UI or UX) updates
- [ ] Customizable tutorials for higher tier customers - provide as a service
- [ ] Metrics to know how useful these tutorials are, if people close them inmediately or if they repeat them
- [ ] Must be loaded on demand (lazy loaded)
- [ ] Must be easily closed and easy to trigger it again - maybe the same help icon representing the tutorial of certain areas?

## Stakeholders
TBD

## Timeline
TBD

## Inspiration

- shepherdjs.dev
- https://introjs.com/
- https://react-joyride.com/

<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0EvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54a03ab7719fc9c204531e7bc94022c0a1c58f0e/image.png" alt="image.png" />
<img width="1179" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0kvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87a86408e7a8f1427f60ff2b24528a50e3b0d51d/image.png" alt="image.png" />

https://luna.ai/

**Comment by larssondenise** [comment]
Additional context folded in from #557 ("Dynamic User On-boarding", 2022) — explicit tie-in this epic doesn't currently mention: integrating guided flows with existing help/documentation content, not just standalone tutorial overlays.
