### ISSUE TITLE
Authentication: Identity mgmt + flows with Kratos 1.2

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1240]
## Description
Extending and improving the wider set of authentication possibilities on Alkemio

## Initiative / goal
Allowing users to easily and more enjoyably authenticate to the platform

### Hypothesis
Authentication is a key user experience
Users want to re-use existing authentication mechanisms

## Acceptance criteria and must have scope
Kratos usage; Alkemio MFA; Logins from non-Alkemio M$ identities; ++
- [ ] Defined criteria / steps for allowing Microsoft identities from VNG, VU to be used
- [ ] Enabled authentication with Microsoft domain accounts from CLI
- [ ] Script to provide an overview of which authentication mechanism is used for every account

Later:
Disable authentication using email / password using @alkem.io email addresses i.e. only via Microsoft authentication provider
- [ ] ...

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
