### ISSUE TITLE
Innovation Flow: simple set of states

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1249]
## Description
The state machine definition for Innovation Flow is too heavy for the current usage scenario. 

To be replaced with a simple set of states with an order.

## Initiative / goal
Usability

### Hypothesis
The innovation flow is the core of Alkemio, and it needs to be usable

## Acceptance criteria and must have scope
- [ ] Add a set of states to the InnovationFlow entity
- [ ] Each state to have the following fields: a) displayName b) description c) sortOrder
- [ ] The default state is the first one in the list
- [ ] tbd - anything else?

### UI Changes
- [ ] Space settings: Challenges tab
- Add "Default Innovation flow" block to select the default flow from the Space templates. This will be the default for all new Challenges **and Opportunities**. Note that the global templates may be visible here if that is what we want, but that the user should first add it to the space templates to be able to select it as default.
- Show warning icon on tab when there is no default selected (eg when default template was deleted from templates section)
- [ ] Space: Create Challenge dialog (=create opportunity dialog)
- Just show set of states (we may already have a design for this?) + a design for when there is no default flow. 
- [ ] Challenge settings: Innovation flow tab (gone)
- [ ] Challenge contribute tab: Innovation flow settings dialog
- Possibility to add states, change the order, update names and descriptions. Redesign block on top.
- [ ] Challenge contribute tab: Description block + flow states 
- Settings wheel gone, edit button in description block?
- Descriptions per state, shown where now the sentence is about what state the challenge is currently in
- Add icon to current state so sentence can go
- [ ] Innovation library
- Create/edit template dialog (also visible in space library)

## Stakeholders
Community Manager

## Timeline
asap

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
