### ISSUE TITLE
Demo for end to end usage (developer) - no authentication

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#125]
## Description
As a new contributor to CT
I want to be able to quickly get a running instance of CT
So that I can see how the platform operates

## Scenario:
Build + deploy a new instance of CT
User launches a simple page
Platform displays a list of challenges known within the Ecoverse

Note: no authentication in this demo so it can be standalone.

## Acceptance criteria

- [ ] User checkouts out this repo, runs docker compose (+other instructions?) and is able to deploy the demo
- [ ] UI to enable the user to interact with the demo
- [ ] Simple demo data available within the repo and deployed as part of the building

## Runtime aspects:
Data model accessible via GraphQL
