### ISSUE TITLE
Spaces with subspaces: Account entity, api usage

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1261]
## Description
Spaces, Challenges + Opportunities are all very similar to each other. Having 3 different concepts is simply very confusing for our users, as well as bringing a lot of complexity into the platform. 

The intention is to have a single entity, Space, that can then have child spaces i.e. subspaces. Then the different ways in which spaces are used, at different levels, is controlled by a combination of templates and UX design. 

Longer term it may also be that we want to support more than the 3 we essentially now support. Also a lot of customers / usage right now is satisfied with 2 levels. 

In essence this is about creating a general Space concept, which can then be adapted to support multiple types of usage / methodologies via the template that is applied. Currently the platform enforces a hierarchy with structure that is often not relevant / right: it needs to be more flexible. 

This epic is about doing the server + client preparation work.

## Initiative / goal
Simplifying the platform, both for end users and in terms of functionality to be maintained. 

### Hypothesis
Space, Challenge and Opportunity can be represented by a single concept i.e. Space
The term subspace is much easier for users to comprehend when using the platform as they have already internalized the concept of space.
Space as a concept together with templates is rich enough to make a "challenge subspace", "goal subspace", "opportunity subspace"

## Acceptance criteria and must have scope
Preparation work:
- [x] InnovationFlow moved to Collaboration, so a Space also has one
- [x] Move StorageCollaborator onto ChallengeBase entity
- [ ] Create new "Account" entity that repaces the "spaceID" field on Challenge / Opportunity, and that holds the Library, Defaults + License
- [ ] Client code to avoid usage of nameID based lookups 
- [ ] Client code to retrieve URLs from the server rather than do it in the client

- [ ] Test suites updated for above changes

## Stakeholders
Product / engineering
