### ISSUE TITLE
Compliance: Tracking + cookie handling on client

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1264]
## Description

As a user I want to be able to disable certain behaviors depending on my cookie choices
As a steward I need to be compliant with data handling rules

## Acceptance criteria

- [ ] Cookie policy on client to allow the user to have different levels of cookie usage
- [ ] Able to have and potentially disable hubspot tracking (generic tracking)
- [ ] Ability to remove Kratos accounts that are not used (script?)
