### ISSUE TITLE
Client: fast page loading with feedback

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1273]
## Description

As a user I want that the key pages on Alkemio load fast

## Acceptance criteria
- [ ] To cover the following pages: Home page, Hub page, challenge page, opportunity page
- [ ] Visual feedback while pages are loading
- [ ] optimise the data loading phases
- [ ] MD file to discuss options
