### ISSUE TITLE
Subspaces: api convergence

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1286]
## Description
The server api to be brought back to a single concept: Space (dropping Challenge + Opportunity as entities)

## Initiative / goal
Simplifying the platform, both for end users and in terms of functionality to be maintained.

### Hypothesis
Space, Challenge and Opportunity can be represented by a single concept i.e. **Space**
The term subspace is much easier for users to comprehend when using the platform as they have already internalized the concept of space.
Space as a concept together with templates is rich enough to make a "challenge subspace", "goal subspace", "opportunity subspace"

## Must have scope
- [ ] Server api to have a more generic Space entity, which can have subspaces
- [ ] Client code base updated to work with new api
- [ ] Notifications to work with new api
- [ ] Domain model cleaned up: Project / Agreements, relations removed from domain model
- [ ] Test suites passing

## Stakeholders
QA
Development
