### ISSUE TITLE
Subspaces: Technical Debt

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1287]
## Description
The server api to be brought back to a single concept: Space (dropping Challenge + Opportunity as entities)

## Initiative / goal
Simplifying the platform, both for end users and in terms of functionality to be maintained.

### Hypothesis
Space, Challenge and Opportunity can be represented by a single concept i.e. **Space**
The term subspace is much easier for users to comprehend when using the platform as they have already internalized the concept of space.
Space as a concept together with templates is rich enough to make a "challenge subspace", "goal subspace", "opportunity subspace"

## Must have scope
- [ ] Client code base cleaned up for new conceptual setup
- [ ] Search / roles api cleaned up?
- [ ] Activity logs migrated + with new types
- [ ] Northstar / usage reports migrated + updated

## Stakeholders
QA
Development
