### ISSUE TITLE
Client observability: setup to improve user experience

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1291]
## Description
Focusing on reducing the client errors

## Goal
Improving the end user experience

## Hypothesis
Users are not getting the best user experience

## Must have scope
- [ ] Review of Sentry functionality
- [ ] Setup of Sentry to give better insights
- [ ] Structure the process around client observability
- [ ] Analysis of the issues being experienced, with recommendation of issues to be addressed
- [ ] Capacity reserved to address first set of issues
- [ ] Next epic planned in with heavier issues

## Stakeholders
Product owner

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by bobbykolev** [comment]
Closing as duplicate of https://github.com/alkem-io/alkemio/issues/1293
