### ISSUE TITLE
Virtual persona: demonstrator

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Coordination#1294]
## Description
End to end integration and interaction with Virtual persona.
The interaction should be limited to question - answer inside a post. 

## Goal
Make the first VC available for spaces with a setting on a space level.

## Hypothesis
Integration of an AI virtual contributor would increase the activity and productivity inside the communities. 

## Must have scope
The space admin should be able to add and remove a virtual persona inside a space.
The persona should respond in posts' comments.
The persona should have the context of the post, its thread, and the space / subspace context. 

We need:
- Ability to mention virtual contributor (trigger response);
- Indication of the virtual created content (comments);

## Acceptance criteria

- [ ] Virtual contributor available in mentions (client);
- [ ] Virtual contributor available in community administration (client);
- [ ] Indication that the content author is a VC (client);
- [ ] Indication that the contributor is a VC (client);
- [ ] The logic for matching the VC mentions is on the server;
- [ ] Filter contributors so the VCs are available only where explicitly enabled* 

#### Out of scope
Marketplace / library
UI settings (configurations)
Auto-generated content
Alkemio vector DB

## Stakeholders
 @renehonig @valentinyanakiev @StefanAlkemio @techsmyth
