### ISSUE TITLE
File serving scalable

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1295]
## Description
The number of files served by Alkemio is growing, and each file load potentially is a request to the cluster. 
At the moment all these requests are served by the server container, which means that the file loads have the potential to overwhelm the server / impact it. 

## Initiative / goal
Improved whiteboard experience

### Hypothesis
Having the file loading in a separate container allows us to monitor and scale better the serving of files from the cluster

## Acceptance criteria and must have scope
- [ ] Document server container added to the cluster, responsible for serving files from rest apis
- [ ] Document serving removed from server container
TBD:
- [ ] Message bus approach added to allow the whiteboard collaboration service to query for a) authorization checks b) license checks

Note: authorization check logic to remain in the server container, but available via message bus responses so that this can easily be easily split out of the server container without impacting the new service

## Stakeholders
DevOps
