### ISSUE TITLE
Virtual Contributors: MVP

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1298]
## Description
End-end use case

Setting the stage:
- Users can create a single space when they come onto the platform. Free space, with one month trial for Plus to allow creating a VC
- In that space they have materials to guide them, and a subspace already ready to guide them in creating a VC
- When the user has populated some data in the VC subspace, he can "create his VC"

VC creation:
- body of knowledge is only graphql data in first phase, but to go live will need to upload pdfs
- usage context: profile, context
- no options to select personality, types of response etc

Interaction:
- user can interact with the VC within their own space
- the VC will also be visible to other users on the platform (what is on the profile?), and invitable only by Alkemio Support

## Goal
Allowing users to experiment with VCs on Alkemio

## Hypothesis
VCs are the attraction force that will drive usage of the platform

## Must have scope
- [ ] Space content available as a body of knowledge, with ingestion triggerable on demand (not live / automatic)
- [ ] Space simple profile is available to provide context for a VC when it is a member and interacting in a Space
- [ ] Repositories clearly names with release builds
- [ ] End-end deployment into all clusters, including production
- [ ] VCs associated with Account entity, and governed by License for that Account
- [ ] Per account, it is possible to create a VC with the Body of Knowledge based on one of the spaces in the Account
- [ ] ...

## Stakeholders
Sales
Prod Mgmt
