### ISSUE TITLE
Organizations: Flexibility/Less formal + Simplify Unverified profiles

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1306]
## Description
The current usage of organizations causes a lot of confusion:
- Profiles suggest huge organizations are partnering with Alkemio, when actually there are just very specific teams or departments working on Alkemio
- Unclarity about who is 'behind' an organization profile
- Organization profiles used to affiliate organizations with a specific challenge are a kind of 'dead' profiles, but it still seems like you can send them an email etc

There are a couple of needs when in comes to organization profiles:
- Clarity on who is 'behind' it
- See where this org is participating in
- See if it is 'real' and alive.
 
The envisioned solution is to make a clear split between Verified and Unverified organizations, plus splitting the Organization name from the Department/team etc, in which the Department/team gets the profile page, and the organization is simply a sort of tag on this profile. Clicking on this tag would then allow the user to see all profiles associated to this organization, and all the spaces these profiles are participating in.

Verified organizations
- Team/Department name
- Organization
- Bio, full profile, like it is now
- Contact person
- Send a message
- Profile visible outside of the Spaces, eg on Contributors page, later maybe in Recommended sections

Unverified organization
- Team/Department name
- Organization
- No additional profile info
- No contact person
- Not able to send a message
- Profile card only visible from within the Space/Search
- Clear indication that this profile is not 'verified' (maybe use different name), plus button to verify

## Goal
Clarity for users, proper way of indicating affiliated organizations when they are not actually active on the platform

## Hypothesis
Better usage of organization profiles, overall richer impression when exploring, less frustration of users,

## Must have scope
- [ ] 'Name' of former org profile to be more specific
- [ ] New name for Organization profile? Maybe something like Team profile?
- [ ] Organization to be more of a label/tag, not a profile
- [ ] Page to see all profiles + journeys related to an organization
- [ ] Unverified profiles to have a completely stripped down version, see details in description above

## Stakeholders
S&D

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by techsmyth** [comment]
When looking at this topic we also need to consider the roles defined within the European Business Wallet standard
