### ISSUE TITLE
Create a Space yourself

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1312]
## Description
Currently, Spaces can only be created by G(S)A's on the platform. This limits the exploration options for people on the platform, they cannot simply 'try it out'. With the VCs coming in and the campaign(s) that will follow, we want people to be able to directly explore the Spaces on their own. With this functionality, people will be able to click on a button on their dashboard to create a space. In the first version, we'll use the current functionality and UI where possible, and only extend functionality when really needed so that we can bring this live asap.

## Goal
Allowing authenticated users to create a Space

## Hypothesis
Enthusiasm since there's nothing blocking people from trying out the platform, easier to sell since people can try it out for themselves, scaling the capacity of the S&D team since they no longer always have to create Spaces for others, etc.

## Must have scope
- [ ] Dialog for first step of the space creation, with the slightly adapted content of the current first step of the space creation
- [ ] Host to be the user, or an organization that the user is owner of
- [ ] Limit to 1 free space per user
- [ ] Dedicated area on dashboard for spaces that you own
- [ ] Option to delete the Space from the Space (profile) settings
- [ ] Default callouts with explanation
- [ ] Guided flows in Arcade, linked to/embedded in the default callouts

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Create Flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/freespacesforall-829
<img width="1540" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd08rQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--051fd92196073eca79621a2d3f4b5d0d79b64cf3/image.png" alt="image.png" />

Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
