### ISSUE TITLE
VCs: Data freshness

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1318]
## Description
Ensuring that the data used by VCs is up to date

## Goal
Allowing for near real time data freshness (i.e. latest data) 

## Hypothesis
Users expect to have the latest data available

## Must have scope
- [ ] Ability to incrementally update embeddings when the source data changes
- [ ] Ability to trigger full re-ingestion
- [ ] Showing / updating the last "data update date" on the ingested data

## Stakeholders
AI lead

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
