### ISSUE TITLE
VCs: Multiple context types

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1319]
## Description
Allowing the person inviting a VC into the space to be able to see multiple levels of data

## Goal
Ensure users feel safe inviting VCs into their spaces

## Hypothesis
Different VCs will need different types of contextual data to be effective

## Must have scope
- [ ] Support multiple types of context data ingestion as embeddings (e.g. no context, public profile, all data etc)
- [ ] Allow users to choose the type of context provided to the VC when inviting / later?
- [ ] Allow VCs to specify the type of context they require to be efffective

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
