### ISSUE TITLE
VCs: Usage controls

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1325]
## Description
As a provider of a VC, I want to be able to control where it is used

## Goal
Ensuring users feel safe in creating + providing VCs on Alkemio

## Hypothesis
Being able to control who uses your VC is critical to users creating them on the platform. 

## Must have scope
- [ ] A provider of a VC can control if the VC is globally listed
- [ ] Add simple concept of a store, and if a VC is public it is visible in the store
- [ ] Publish modes: inactive, private (within account), public
- [ ] It is possible to invite public VCs to join a Space. Either via finding in the store, or having a direct link to the VC profile. 
- [ ] Provider of VCs are able to see + then accept / reject invitations
- [ ] VC provider can choose to leave a space membership
- [ ] When a VC is added as a member to a space, the VC provider receives a notification
- [ ] When a VC is invited to a space, the VC provider receives a notification
- [ ] If visibility is turned back from public then any memberships stay
- [ ] If a VC is inactive there should be an indication (visual, automatic reply etc)

Note: make clear that the interaction with a VC is only visible within the space where the VC is a member. 

## Stakeholders
S&D

## Design
User flow invitations: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/invitingvcs
<img width="1852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b0306245e5e69fd625de98b1e0960f4087c9328/image.png" alt="image.png" />
