### ISSUE TITLE
VCs: Monitoring + operations

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1326]
## Description
As a platform admin / campaign manager I want to understand the usage of VCs

## Goal
Ensuring safe usage of VCs on Alkemio

## Hypothesis
Being able to control who uses your VC and how they use it is critical to users creating them on the platform. 

## Must have scope
- [ ] Dashboards on VCs usage for sales & delivery team, on kibana, - starting a conversation with VC, creating VCs, adding VCs to community (of which type, by account, external), VC statistics (N of questions  / answers and threads per VC, VC quality (upvote / downvotes))
- [ ] Up / downvote answers
- [ ] Report button for inappropriate questions that are flagged to admins

For separate epic
- [ ] For discussion: sentiment analysis of the replies

## Stakeholders
Operations
S&D

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
