### ISSUE TITLE
VC: External community activity summary service

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1334]
## Description
Creating an "external" AI service, to demonstrate and path find the usage of external AI services as the engines of VCs. 

## Goal
Allowing external AI services to be integrated into Alkemio.
Allow for a "what happened this week" summary contributor to your space

## Hypothesis
We will want near term to integrate externally offered AI services into Alkemio.
Having a "what happened last week" AI service that then emails the members is a powerful community engagement addition. 

## Must have scope
- [x] Create an AI service that is "external" to the platform
- [x] Enable interacting with this AI service via configuration
- [x] Allow this service to interact as a contributor on the platform

## Stakeholders
AI Champion
Partners

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by SimoneZaza** [comment]
what's remaining in this epic description is similar to #1339
