### ISSUE TITLE
Stability: Atomic creation of key entities 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1340]
## Description
Currently is the creation of an entity fails, then there are often partial entities left over - causing both orphaned data and instability in the server.

## Goal
Creation of entities should be done in memory, with only a single save at the end.

## Hypothesis
Having atomic creation of entities will 
- improve production server stability 
- reduce data without the proper relations set
- improve developer effectiveness (less resetting of the database)

## Must have scope
- [x] alkem-io/server#4102
- [x] alkem-io/server#4103
- [x] alkem-io/server#4104
- [x] alkem-io/server#4105
- [x] alkem-io/server#4106

## Stakeholders
Development
QA

## Design
To be build up from lower level entities.
Spike can go last to derisk the rest of the work.

**Comment by techsmyth** [comment]
@hero101 can you please add any other points you think are needed above?
