### ISSUE TITLE
Create your own space: GA

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1341]
## Description
Currently, we allow selected users to create their own space. However there are additional product gaps to be addressed before this is fully opened up.
## Goal
Allowing any authenticated users to create a Space

## Hypothesis
Enthusiasm since there's nothing blocking people from trying out the platform, easier to sell since people can try it out for themselves, scaling the capacity of the S&D team since they no longer always have to create Spaces for others, etc.

## Must have scope
- [ ] Flow for verifying users before turning a space public
- [ ] Ability to invite users to a particular role on the platform
- [ ] Allowing organizations to invite a user to join an organization
- [ ] Remove directly adding users to org
- [ ] Allowing community admins to invite an org to join a community
- [ ] Remove directly adding org to space community
- [ ] Public profile for spaces properly controlled so that not visible if not public
- [ ] Allow spaces to be created in private mode, with explicit step to make public so that others can find you

tbd: add account for user / org where they see their account, not tied to the root space?

tbd: monitoring for bad behavior / content?

## Stakeholders
product

**Comment by techsmyth** [comment]
@SimoneZaza please have a think through the above points. These are I think most of the key ones we would have to address before putting the ability to create your own space available to any new user of the platform.

**Comment by techsmyth** [comment]
Closing as converted this to a milestone with multiple epics
