### ISSUE TITLE
QA: Nightly Builds

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1343]
## Description
Having a stable QA base is critical to a quality service

## Goal
Having a stable nightly is key to having a quality release

## Hypothesis
Having robust test suites are essential to a quality service

## Must have scope
- [x] Client authentication test suite is running
- [x] API test suites stable to be executed as part of nightly build
- [ ] Nightly build to send a notification all dev team if nightly fails
