### ISSUE TITLE
Observability: Probes, alerting, logs

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1344]
## Description
More informed and actionable information about what happens in the service, both for reactive + preactive work

## Goal
More stable + reliable service

## Hypothesis
Better observability leads to a better service

## Must have scope
- [x] alkem-io/infrastructure-operations#1355
- [x] alkem-io/infrastructure-operations#1356
- [x] alkem-io/infrastructure-operations#1357
- [x] alkem-io/infrastructure-operations#1358
- [ ] alkem-io/alkemio#1361
- [x] alkem-io/infrastructure-operations#1359
- [x] alkem-io/alkemio#1358
