### ISSUE TITLE
Alkemio Expert Personas: allow creation + management

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1363]
## Description
The creation of AI Expert Personas should be logically separated from the collaboration platform domain model

## Goal
Allowing clear separation between VC + AI Personas, to enable also external AI Personas to be created

## Hypothesis
To be able to effectively work also with external AI personas, we should start by making the Alkemio AI Personas logically separated from the collaboration platform domain model

## Must have scope
- [ ] Microservice to allow the creation of new "AI Expert Personas", giving each an identifier and mapping to a body of knowledge
- [ ] Providing graphql api to allow interaction
- [ ] TBD: Sharing the Alkemio authentication framework. 
- [ ] TBD: also authorization?
- [ ] TBD: externally visible api or in first pass internal only?

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
