### ISSUE TITLE
VC: Threaded interactions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1366]
## Description
Allowing threaded interactions with the expert / help engine

## Goal
Usability of VCs

## Hypothesis
Users expect to be able to have a conversation with the VC, not just ask standalone questions

## Must have scope
- [ ] Design for the end to end data flow, captured as MD in alkemio repo
- [ ] Expert engine to allow conversations with each AI Persona Service instance
- [ ] Server to detect when a reply is in a thread that is with a VC and trigger new questions to the VC

Note: each message in a Matrix room already has a threadID, so we can likely use that for the threaded interaction with the AI services.

## Stakeholders
S&D

## Design
https://alkem.io/building-alkemio/challenges/virtualcontributor-4405/collaboration/vcsthreadedinteraction
