### ISSUE TITLE
Ecoverse read only web client

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#137]
To enable the navigation of the content of an ecoverse in a read-only manner on a desktop web browser and using available query api.

## Acceptance criteria
- [ ] Clean handling of not being able authenticate, and not being able to connect to the server
- [ ] Cherrytwist logo visible, including favicon (browser tab)
- [ ] Ability to see an overview of the ecoverse: context, challenges, community (groups) logos for the host (picked up from reference links? avatars?), community (groups)
- [ ] Ability to navigate into a challenge and see an overview of the challenge: context, community, projects (placeholder)
- [ ] Placeholders for finding community members
- [ ] Developer level branding (vague for now)

Updated: https://xd.adobe.com/view/eb6c3fc0-8873-44b6-9f63-01b020d4a8dc-be3f/?fullscreen
