### ISSUE TITLE
VC: Expert engine space data retrieval + loading

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1374]
## Description
Additional controls on the type of data that is ingested
Additional improvements in response insights
Allowing additional information about the sources on which the answers from a VC are generated

## Goal
Uptake of VCs

## Hypothesis
The quality of the data ingestion and how the answers are created are key factors to build trust in usage

## Must have scope
- [ ] Optimize the management of embeddings
- [ ] Call for posts
- [ ] Ignore draft callouts
- [ ] Provide the additional data source meta information to the server
- [ ] Design for how to display this to the user
- [ ] Client updated

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
