### ISSUE TITLE
QA: Test Suites extensions Q1 2026

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1376]
## Description
Improving the overall coverage of test suites in Alkemio is key to delivering confidently new releases + functionality quickly

## Goal
Quality platform

## Hypothesis
_What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit._

## Must have scope
- [ ] Agreed + prioritized code quality + maintainability improvements for the test suites 
- [ ] Analysis + roadmap agreed for next test suites to be created
- [ ] API test suites split into many parts: stable, ???
- [ ] Code quality in test suites repo increased: checkin rules, naming cleaned up, structure cleaned up
- [ ] Authorization reset test suite added
- [ ] Overview of what test suites are not covered from the nightly + tests planned in

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
