### ISSUE TITLE
Production cluster optimization

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1377]
## Description
Ensuring the production cluster is fit for purpose

## Goal
Performant and robust service

## Hypothesis
Our production cluster is in need of attention

## Must have scope
- [ ] k8s upgraded to a supported version
- [ ] upgrade of nodes to more powerful machine
- [ ] Mail service moved from AWS to Azure
- [ ] Backups moved from AWS to another S3 provider, with security to a sufficient level (?)
- [ ] Backups production separated fully from other envs, ideally separate S3 service + separate credentials
- [ ] Decommission active usage of AWS + tidy up backups stored there
- [ ] Able to close the AWS Stichting Alkemio account

## Stakeholders
Sys admin
CTO

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
