### ISSUE TITLE
API usage performance / monitoring / audit trail

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1379]
## Description
Insights into the usage of the api is important for providing a quality service, and tracking down issues in produciton

## Goal
Quality of service

## Hypothesis
When issues hit production it is important to know what api usage is happening

## Must have scope
- [ ] Capture of all query and mutation interactions
- [ ] Timing information?
- [ ] Ability to visualize / dive down into the data?

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Description
Allowing full auditability of all queries and mutations to the server, providing a second level audit trail of all interactions with the platform.

## Initiative / goal
Platform management
Security

### Hypothesis
As platform usage grows, we must have extended capabilities for tracking down events that occur

## Acceptance criteria and must have scope
- [ ] All interactions with the cluster at graphql / http level captured in a reporting warehouse
- [ ] Reports created to be able to narrow down interactions per space / context
