### ISSUE TITLE
Accounts for managing resources

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1383]
## Description
The current process for new users to engage with the platform is overly complex, involving creating profiles, spaces, and managing resources like innovation packs and hubs.
The proposed solution involves establishing a more straightforward model where each user and organization has an "account." This account will manage all associated resources, such as spaces, virtual contributors, and innovation packs.

As a user/organization, I want to get an overview of all Spaces, VCs, Innovation packs and custom homepages that I am hosting.

## Goal
Easier on-boarding

## Hypothesis
The current conceptual model is way too complex, hard for both team members and community to understand. It needs to be much simpler and more familiar

## Must have scope
- [ ] InnovationPacks, InnovationHubs, VCs created + updated from an Account
- [ ] An Account can have multiple L0 spaces (i.e. spaces with no parents)
- [ ] All users and organizations on the platform have an account
- [ ] Accounts can no longer be moved from one host to another
- [ ] Client displays the entities being managed in the account on the account tab
- [ ] Users / organizations with multiple accounts have those accounts combined

For later discussion:
* Simplification of the creation + management of organizations
* Consolidating the library associated with L0 spaces with the InnovationPacks held within the Account

## Stakeholders
Product
Partners

## Design
https://alkem.io/building-alkemio/challenges/technicaldesigns-9455/collaboration/accountforuserorg
