### ISSUE TITLE
Memberships: consistency, organization

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1385]
## Description
We have memberships and similar concepts on:
- Platform
- Spaces
- Organizations
For simplicity in our mental model, the UI of the platform, and the code it would be great if we can make this consistent with Contributors and Roles

## Goal
Making the administration on the platform easy to do and understand. 
Allow for flexibility in the types of roles / user assocations within a community

## Hypothesis
Managing a community is core to Alkemio

## Must have scope
- [ ] Able to manage user associations to organizations
- [ ] Able to manage platform level roles
- [ ] Consistent UI on
- Platform administration: Contributors
- Space settings: Community
- Organization settings: Associates
- [ ] Consistent UX on
- Inviting
- Updating roles
- ...?
- [ ] Removing gaps+bugs in lifecycle, eg being able to remove an application 

## Design
Whiteboard with concepts:
https://alkem.io/building-alkemio/challenges/technicaldesigns-9455/collaboration/membershipmodule

**Comment by larssondenise** [comment]
Closing as a duplicate of #1179 (Roles: Flexible & Templatable community roles). Added context and moved its 9 open sub-issues there directly.
