### ISSUE TITLE
Temporary Storage

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1389]
## Description
Allowing for uploading of files / images etc before the entity that they are for is fully created

## Goal
Improve user experience
Improve code maintainability by not having create + delete cycles
Improve platform stability by not having entities being created / deleted that are not needed

## Hypothesis
Supporting temporary storage will make the client easier to work with, and the platform more robust

## Must have scope
- [ ] Allow uploading of files / images as temporary Documents
- [ ] When the entity is created, the Documents that are used in its creation + marked as temporary should be moved to the local storage bucket for the entity
- [ ] *All temporary creation of entities to get a storage bucket on the client are removed*

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
