### ISSUE TITLE
Test harness around Graphql api

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#139]
As a developer I want a set of tests that run against the graphql api so that I can be confident in making changes. 

## Acceptance criteria

Infrastructure
- [ ] Identify and choose a set of libraries / tooling to be used for creating and executing the tests against the api
- [ ] Tests automatically executed on CI builds
- [ ] All tests to go against the graphql api
- [ ] Clear locations / mgmt of test suites + associated data
- [ ] Initial exploratory testing of the solution

Test coverage
- [ ] Test suite for each role
- [ ] Each test suite to have a test to validate each query / mutation that is relevant; both negative + positive tests 

Non-functional testing
- [ ] Identify set of load testing scenarios, security testing, ...
TO DO: split into separate epic

Misc
- [ ] Raise cards for items that are out of scope

##
