### ISSUE TITLE
Account Mgmt v2: bucket (orgs, verification. ...)

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1393]
## Description
Improving the management of accounts

## Goal
Ensuring admins are able to manage and work with the resources under their account

## Hypothesis
Effective management of account resources will help uptake, and reduce the work for the support team

## Must have scope

Scope to be brainstormed, but wish list includes:
- [ ] Org creation + management flows?
- [ ] Verification flows + who gets access to what when
- [ ] Renaming of Innovationpack to Collaboration Pack?
- [ ] Renaming of InnovationHub to CollaborationHub?
- [ ] ...

## Stakeholders
Support team

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
