### ISSUE TITLE
Stability: Client error tracing + reproduction

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1400]
## Description
Being able to track effectively errors / exceptions end-end in the platform

As a QA I want to have the ability to replay the issues that happen on PROD environments and the ability to test against different configurations (OS, Browser).

As a User I want to have robust client experience.

## Goal
Stability
Usage via quality user experience

## Hypothesis
There needs to be better information captured / tracked to enable effective tracking down + reporting of errors.
Errors lead to users being dissatisfied with the platform

## Must have scope
- [ ] Distributed stack trace
- [ ] Additional information in exceptions
- [ ] Understand how to do replays on client side errors
- [ ] Testing strategy against different environment configurations 
- [ ] ...

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._
