### ISSUE TITLE
Calendar events: flexible time + subspaces

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1415]
## Description
We receive quite some feedback from our users, willing to use the calendar but it doesn't fulfill all their needs yet. This epic is about the most occurring feedback.

## Goal
_Describe how this Epic impacts an initiative the business is working on._

## Hypothesis
_What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit._

## Must have scope
- [ ] Flexible time (15 min steps)
- [ ] Multi-day + all day events
- [ ] Option to show an event from the subspace in the parent Space

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Figma file:
https://www.figma.com/design/rddyv3LBg0sbm1b7Yny9ze/Calendar-V3?node-id=35-221&t=2aa1t6J1plondLpk-1
