### ISSUE TITLE
Improving UX for "read only space"

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1424]
## Description
Our Spaces offer a wide range of functionalities, but sometimes simplicity enhances user experience. We are currently developing a “Playground for Working with AI” Space, designed to educate users about AI and provide an interactive environment to explore our VCs. To optimize the user experience in this and other Spaces, we need to implement several minor adjustments. This Epic will consolidate all related tasks to ensure a cohesive and improved experience.

## Goal
A straightforward experience without confusion

## Hypothesis
Hiding unused functionality and allowing for more customization will reduce confusion for new users

## Must have scope
- [x] Remove activity block in Community page and add the events to the general activity block dialog
- [x] List of tools in Knowledge base to not have dash + no state, and when there are no comments, no (0)
- [ ] When there's no need to become a member of a Subspace to contribute, don't show the banner (do something else to ask if you want to follow?)
- [ ] Subspace menu: don't show subspaces/events icon to members when there are none and members cannot add themselves
- [ ] Allow admins to change the content in the description blocks on the dashboard / community / knowledge base / subspace dashboard
- [x] (bug) allow Community Guidelines to be saved without content
- [x] "List view" in Subspaces: 
  - Rename to Index
  - Add filter/search, like in the index
  - Only show when there are more than 3
  - Use avatars instead of icons
- [ ] TBD Show tags on subspace cards in collapsed version

## Stakeholders
Product team, sales

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
