### ISSUE TITLE
Space templates with hierarchy

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1430]
## Description
Allowing for full templating of spaces
Wouldn't it be great? Your Space, fully set up from the start. With the right Subspaces, the right collaboration tools, the right settings.. And maybe even adding some more differentiation, like having a different tab menu for various templates.

## Goal
Spaces setup to support particular use cases
Management defaults

## Hypothesis
Allowing for all aspects of a Space to be stored in a template makes for a richer customization of the platform. In particular related to a) settings and b) community setup

## Must have scope
- [ ] Allowing Spaces to be stored as part of Template entity
- [ ] Creation of an entity to hold level zero spaces, and taking care of TemplatesManager
- [ ] Space authorization to inherit from whatever parent it is getting the authorization from (currently it is aware of its own parent authorization to allow for private spaces)
- [ ] Without Space Library

TBD
- [ ] Still support collaboration on Templates?
- [ ] ....

## Stakeholders
Product

## Design
Figma file:
