### ISSUE TITLE
Test suites: maintainability

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1431]
## Description
As a developer or QA I want to be able to effectively work with test suites used in Alkemio

## Goal
Significantly improved ability to create, update and extend the test harnesses used in Alkemio

## Hypothesis
Easier creation + updating of test harnesses will lead to more robust QA test harness and ultimately to higher overall platform quality

## Must have scope
- [ ] Client test suite separated from server-api test suite
- [ ] Shared code in a tests-lib package
- [ ] Versions up to date
- [ ] Ability to compile all code
- [ ] Check for code quality (e.g. no unused vars etc) before checking in
- [ ] ...
