### ISSUE TITLE
License management using Wingback

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1434]
## Description
Allowing the management of customer entitlements at the Account level using Wingback service

## Goal
Customer support
Commercial product

## Hypothesis
We need a billing path for subscriptions

## Must have scope
- [ ] Ability to integrate with Wingback for customer account information
- [ ] Ability to manage entitlements at the Account level, 
- [ ] Ability to manage entitlements at the Space level
- [ ] Ability for updates to the subscriptions in Wingback to reflect in the updated entitlements in the platform
- [ ] Entitlements to be checked and managed independently of Authorization

## Stakeholders
Customer Success team

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
