### ISSUE TITLE
Bucket: Open Source Integrations

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1436]
## Description
There are more and more open source tools out there, we should have a bucket to capture them 

## Goal
Gather potential open source integrations

## Hypothesis
We can expand our tools/functionalities with open source integrations

## Must have scope
- [ ] Document Editing: Collabora https://github.com/CollaboraOnline
- [ ] Videoconference: https://galene.org/
- [ ] Interactive content: https://h5p.org/

## Stakeholders
Dev team

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by Henapraise** [comment]
Hello there.
My name is Praise Hena, and I am a UI/UX Designer who is interested in contributing to this project. How do I get started?

**Comment by valentinyanakiev** [comment]
> Hello there. My name is Praise Hena, and I am a UI/UX Designer who is interested in contributing to this project. How do I get started?

Hello @Henapraise - I am the engineering lead of Alkemio.  You should contact simone@alkem.io. Simone is our product lead and UI / UX capability is in her remit.

**Comment by Henapraise** [comment]
Thank you, I will do that.
