### ISSUE TITLE
Whiteboard: stability

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1442]
## Description
Ensuring that the whiteboards, with the new server side reconciliation, are stable

## Goal
Platform reliability

## Hypothesis
It is simply a must that the whiteboards are reliable and protect the content

## Must have scope
- [ ] Excalidraw updated to 0.17.6
- [ ] All whiteboards that have embedded images have the images stored as documents 
- [ ] Uploading from files is possible, with the content added to the current whiteboard (not replacing)

## Stakeholders
Product

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
