### ISSUE TITLE
Reporting: User flows

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1446]
## Description
At the moment, we have no data on how users move through the platform. Simple example: we don't know whether they start at the homepage, or have a space bookmarked in their browser. Having this data will help us identifying problems, and focus areas on the platform. 

## Goal
The ability to make product decisions based on data-driven usage insights

## Hypothesis
_What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit._

## Must have scope
- [ ] On what page do people enter the platform
  - [ ] Exact page
  - [ ] Ability to group per type (Custom homepage/Space/Subspace/..)
- [ ] On what page do people leave the platform
  - [ ] Exact page
  - [ ] Ability to group per type (Custom homepage/Space/Subspace/..)
- [ ] How many pages do users visit during a session
- [ ] How many users get from the welcome site to the platform?
- [ ] Which pages (grouped) do users visit during a session and in what order (this is probably next level 🙃)
  - Eg. My Homepage > Space > Subspace > My Homepage > Forum > Exit    

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
