### ISSUE TITLE
QA Management Tooling + Plan (M)

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1449]
## Description
Putting in place tools and processes around how we do QA on the platform, so that we can make better overall decisions around the investment that is needed per release and in terms of QA capability.

Capture the contextual knowledge about doing QA in Alkemio.

Improve our ability to scale the bandwidth that is available for QA.

## Goal
Having a better overall grip and understanding of the QA that is in place around Alkemio.

Improving our ability to plan the tests that are executed (both automated + manual).

Mitigating the single person dependency that is Evgeni.

## Hypothesis
It is time to systematize our ability to manage QA efforts.

Show in one location test cases.

Structure test plans with to features, stories bugs.

## Must have scope
- [ ] Evaluate tools and make a recommendation for a tool for managing test suites + test plans
- [ ] Data is populated in the tool
- [ ] Knowledge sharing with Product and the development team
- [ ] Capture of key QA gaps, with a prioritized list to be addressed
---- From Offsite Sep 25
- [ ] Having an overview of all our QA efforts
- [ ] Definition of test suites?
- [ ] Specify per release what test suites are executed
- [ ] Ability to specify placeholders for the test suites that we would like to have?
- [ ] Each test to classified in terms of automated, manual, area, etc
- [ ] Key manual testing that is done on each release is formalized and shareable

Questions:
- Able to run the test suites from the test mgmt tooling?
- Integration with builds?
- Integration with Github?

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
