### ISSUE TITLE
Ecoverse user community administration support in web client

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#147]
As an ecoverse administrator I want to have a web client that is non-developer ready to allow the management of the community and information within the ecoverse. 

To allow the management of the ecoverse community.

Note: it can be "developer" quality UX experience.

## Acceptance critiera
- [ ] Ability to add new users into the ecoverse, and remove users from the ecoverse.
- [ ] The ability to carry out the user mgmt restricted to certain roles
- [ ] Web UI for assigning + removing users from  groups
- [ ] Ability to navigate the user community at ecoverse + challenge levels  and update groups as needed

Out of scope:
- approval process after request by a user for some membership
