### ISSUE TITLE
Notifications Beta tester Improvements

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1474]
## Description
This epic is here for the second phase in the notifications: incremental improvements on the version that is out for beta testers. Individual stories from this epic can be released independently to build up the functionality for beta testers.

## Goal
Notifications on the platform

## Hypothesis
Doing incremental updates to the notifications functionality for beta testers allows us to quickly iterate to get to the full functionality for all users asap/agap

## Must have scope
- [ ] More event types (critical list will be provided)
- [ ] Findings being addressed
- [ ] Pagination
- [ ] Scalability
- [ ] Retention Policy: we store 200 events per user
- [ ] Operational + System management

## Stakeholders
Product team

## Design
Notifications excel: https://stichtingcherrytwist.sharepoint.com/:x:/r/sites/Product/Shared%20Documents/5.%20Platform%20Content%20and%20Information/Notifications%20overview%20-%203%20-%20Copy.xlsx?d=w7a04d1d7f6b049269bc45e9e75ab4843&csf=1&web=1&e=7cDE0R
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
