### ISSUE TITLE
Organization: Inviting users to associate

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1479]
## Description
Currently, an admin can only add people to an organization, not invite them. This must be fixed to allow wider usage of the platform as currently as an org admin I can add any user to my org, without their acceptance

## Goal
Proper usage of organizations, clear user-org relation

## Hypothesis
The association of users to organization must be done with an invitation + acceptance like on a space community

## Must have scope
- [ ] Update org community settings page to resemble the community settings page on spaces
- [ ] Add invitations from org to user + the option to accept
- [ ] Users to see open invitations for organizations + distinguish them from space invitations

To discuss:
- [ ] Platform user management page also refreshed
- [ ] Ability for users to apply to be associated with an organization
- [ ] Usage of contributor policies in the assignment of the page e.g. cannot remove last owner on an org: the userPolicy on the role definition for Owner has minimum number of users set at 1
- [ ] Allow inviting people to be beta testers / vc campaign on the platform level
- [ ]...

## Stakeholders
Product, Sales & Funding

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by larssondenise** [comment]
One to add: switch to automatically add to org > should become automatically send invite for org

**Comment by jeroentskui** [comment]
another thing i added in the design for this one is the ability for user to apply to join an org via the org profile page (similar to spaces) 

this was discussed with @SimoneZaza

**Comment by larssondenise** [comment]
Closing as duplicate — merged into #1433, which now covers both org→Space invitations and user→org association under one epic. Scope, sub-issues (#4830, #7268, #4829, #2165), and the design work here have all been carried over to #1433.
