### ISSUE TITLE
QA: Test suites: validate database content

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1483]
## Description
Ensuring that the data in the database can be included in the expected outcomes from running tests

## Goal
More robust QA test harness e.g. validating no authorization policies without credential rules

## Hypothesis
Access to database content, via a strongly typed setup, would enable a lot more testing to be automated

## Must have scope
- [ ] Ability to do database queries using strong typing (so not raw sql or raw query builder)
- [ ] Ability to customize the database to connect to
- [ ] Definition and implementation of the first QA tests to be carried out in this way
- [ ] utilities to support added to tests-lib package
