### ISSUE TITLE
Visibility: clean, clear, and consistent

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1484]
## Description
This epic establishes clear rules for what is visible to whom, and where across the platform. It aims to clarify visibility for user profiles, contributions, innovation packs, and venture capital (VC) details, both in public and private spaces.

Our assumptions are:
- Admins who set their Space to publicly visible are aware that all users in their Space are visible for unauthenticated users
- Users may not always be aware, especially if it changes

Key considerations:
- Public vs. Private Spaces: Define visibility rules for content based on space type (public or private).
- Visibility Transitions: Notify users when a space changes from private to public to ensure transparency.
- Unauthenticated Access: Review and update visibility for unauthenticated users, such as access to forums and other features.
- Platform-Wide Consistency: Establish a unified approach to visibility that applies across all sections of the platform.
- User Awareness: Make these rules and changes easily accessible for users to read and understand.
- Legal considerations? Check Terms of Service

## Goal
Consistency in how users appear for unauthenticated users and how this is communicated to other users

## Hypothesis
_What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit._

## Must have scope
- [ ] Visibility of user information for unauthenticated users consistent in Spaces
- [ ] Visibility of user information for unauthenticated users consistent on platform pages (forum, library, explore)
- [ ] Clarity about visibility when entering a Space/organization
- [ ] Notifications on changes for admins/members
- [ ] ...

## Design
Whiteboard: https://alkem.io/studiosimone/challenges/denisesimone/collaboration/visibility/whiteboards/whiteboard
