### ISSUE TITLE
Client library package for interacting with server

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#150]
As a user of CT I want it to be easy to interact with a CT server for uploading data, reseting the state of dev servers etc. 

## Acceptance criteria
- [ ] Separate repository for building the client library package
- [ ] Demo repo updated to use the new client library package
- [ ] Client library package available from npm via the "cherrytwist-lib" package name
- [ ] Semantic versioning in place for the packages
- [ ] ...
