### ISSUE TITLE
Authorisation (role based access control) for platform mgmt

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#154]
As a customer of CT, I want that access to the data and functionality within CT is clearly managed so that I can know who has access to and can update what data.

Note: given AAD groups are a paid feature it is likely that roles will need to be managed by the CT server.

## Acceptance Criteria
- [ ] Detailed list of roles that come with the platform: global-admin, admin, user
- [ ] Roles that are supported on each challenge: admin, user
- [ ] For each such platform & challenge role it is clearly defined what they can and cannot do 
- [ ] Authorisation enforced at the graphql api. Note: not all of the graphql api not subject to authentication
- [ ] DB access only inside k8s (lock it down)
- [ ] Server to allow a user to retrieve the set of assigned roles
- [ ] Clients such as Momentum to pass through the authorisation of the end user, not escalate

Note: look at how the notion of scopes fit into above roles. 

-global-admin - has full permissions on both AAD and API level
-db-admin - has permissions on the data management API

=======

Roles for ecoverse management:
- anonymous: able to access non-authenticated elements of the **query** api. To include ecoverse name/context, list of challenges + for each challenge the context of the challenge. Never be able to access any mutations, nor read access to any details of users / user groups. 
- ecoverse-members: able access to the full **query** api. Able to see details of the challenges that the user is a member of.  Able to edit their own user profile.
- community-admin: able  to add users, add /remove users to groups
- ecoverse-admin: reset ecoverse?, delete users, create/delete groups, create/delete challenge, able to fill any roles for each challenge

For each challenge:
- anonymous: Read only access to name, context. No access to community (groups + users)
- challenge-member: Able to see the full challene community (later: interact with the community) and projects.
- challenge-community-admin: able  to add users, add /remove users to groups within the challenge
