### ISSUE TITLE
api: mutations to take DTOs (not parameters) and cleaned up

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#157]
As a user of CT I want a clean and performant api that will remain stable 

## Acceptance criteria
- [ ] Usage of a single unique input DTO for mutations that have more than a single argument. Not inherited. 
- [ ] use delete if removing an entity, and remove if removing a removing a reference / link
- [ ] reverse operation of remove is assign e.g. assignUserToGroup
- [ ] context / profile to no longer have create/update references list (to be separately done)
- [x] all removals to return the removed entity
- [ ] descriptions updated + consistent
- [ ] add api guidelines to developer docs

Decision:
- one to many are not nested in mutations
- one to one can be nested inside mutations

Note: angel still has doubts re references + one-many
