### ISSUE TITLE
Simple search service for ecoverse data

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#162]
As a user I want to be able to effectively find relevant users and groups.

## Acceptance criteria

- [x] Able to search on a set of terms 
- [x] Able to filter the entity types that are returned
- [x] searchresult to have a union type for User|UserGroup
- [x] Sample queries to show how to search the ecoverse
- [x] Clear definition of what is searched 
- [ ] Expand fields that are searched for users
- [ ] Ecoverse able to mark some groups as searchable and some not-searchable
- [ ] Able to search within tagsets whose name I provide
- [ ] Returned results to have a score 
- [ ] Able to limit the set of results that are returned, with score used to determine which ones are returned

Later:
- [ ] Able to restrict the search to within one or more challenge(s)
Note: the client is responsible for sorting / displaying the resulting data.

Note: this first version will be very basic and will be non-optimised.

## Open items
* allowed set of entity types to be an enum (as opposed to strings)
* extend domain model to mark groups as being searchable
* efficient querying of the database
* expand the fields on users + groups that are searched for matches
* allow expanding of search scope to include named tagsets
* score the results
* limit the set of search results returned
* documentation
* performance analysis of search compute load with a fully populated ecoverse
