### ISSUE TITLE
Application Monitoring

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#165]
As a CT DevOps consultant, I want to be able to monitor / analyse what is happening on an applicaiton level so that I can track down issues outside of development environments quickly

## Acceptance criteria
- [ ] Info, Trace, Error, Debug levels of application logging with different messages
- [ ] ELK stack deployed in k8s with Kibana for log aggregation and visualisation (not traefik ingress monitoring)
- [ ] All logs should be visible from the internet with a proper user account (role)
