### ISSUE TITLE
Web: Community search and connecting

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#186]
As a user of CT I want to be able to connect to the right users and teams within the ecoverse

## Acceptance criteria
- [ ] only available to users that are logged in and that are a member
- [ ] able to search and find the right users / groups / challenges
- [ ] able to see details of the right users / groups / challenges
