### ISSUE TITLE
Server Security Production Readiness

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#195]
## Description
As a CT owner I would like to have a secure production instance.

## Acceptance criteria

 - [ ] CORS should be configurable for CT Server deployments
   - [ ] Origin
   - [ ] Headers
   - [ ] Methods
 - [ ] CSFR should not be possible
 - [ ] Rate limiting for brute force attacks
 - [x] Tokens should be managed from a production-class IDP
 - [x] Server authentication errors should throw AuthenticationError
 - [x] Server authorization errors should throw UnauthorizedException
 - [x] User not being in a role should throw custom exception (e.g. GrapqhlUnauthorizedException)
 - [x] Log contexts should be the following
    - [x] AUTH_TOKEN for all token operations
    - [x] AUTH for the rest of the  authentication & authorization issues
 - [x] We have test suites for all plausible security scenarios. (Ideally automated).

## Additional Context
https://docs.nestjs.com/techniques/security
