### ISSUE TITLE
Demo Authentication Provider service (Web2 Identity Provider) 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#198]
As a deployer of CT, I want to be easily able to login and use the application

## Acceptance criteria
- [ ] Separate container providing a simple authentication provider service that provides username / password authentication
- [ ] demo + server docker-compose updated to used this new service
- [ ] Users able to self-register i.e. anyone can register
- [ ] Default single global admin, configured in both simple auth service + server
- [ ] Stores its data in the same db server but in a different schema: ct_auth_provider
- [ ] Token validity window configurable, default to 24 hours
- [ ] Platform documentation updated, including limitations / demo focus for this service

Management
- [ ] Roles: admin & user. 
- [ ] Admin role able to reset passwords and delete accounts
- [ ] Admin role can assign other users to admin roles
- [ ] Admin role able to create user accounts 

## Notes
No UI, just a simple set of rest end points
No email verification, no MFA etc.
No recptcha for now. 
No awareness of Cherytwist platform
No refresh token flow
