### ISSUE TITLE
Updating opportunity and challenge

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#202]
As an admin I want to be able to edit the opportunity and challenge page.

Note: at the moment restricted to ecoverse admin role

## Acceptance criteria
- [x] Able to edit context at opportunity and challenge level (same popup, different mutations invoked)
- [ ] Able to edit  the actor cards, and to add additional actor cards to the two supported groups
- [ ] Able to remove relations (not edit)
- [ ] Able to update existing solution aspects
- [ ] Able to add additional solution aspects 

Note: the set of additional solution aspects ideally should be data driven i.e. from Opportunity in the Template object - but for a first instance can be hard coded.
