### ISSUE TITLE
Packages for working with ecoverse e.g. Client.Lib ++

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#203]
## Story
As a QA / admin, I want to be easily able to interact with a CT server through the api

## Acceptance criteria
- [ ] Manage the interaction with a CT server
- [ ] Provide ability to login to a CT server from the command line
- [ ] Manage the set of graphql files that act are used for queries to the server
- [ ] Demo project updated to remove functionality that is moved to Client.Lib
- [ ] Sample functions, potentially split over multiple files but access through common object, for executing updates on the server

## Additional context
It helps QA by allowing both authenticated interaction with a CT server, as well as a set of functionality that the test harnesses can use. 

It helps admins who need to manage a production CT server so that they can easily execute updates to a server

It helps team maintenance load by having sample graphql files in one place. 

Note: for now about refactoring what we have built up from ecoverse populator, current client.lib and demo project; later look at making the interaction even easier / the set of mutations supported more extensive

Note: there is code for authenticating to a CT server that needs to be migrated over and made to work end to end.
