### ISSUE TITLE
SSI Demonstrator: Authorization

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#204]
As an architect I want to have a clean design for how to integrate SSI into the CT design + architecture

## Acceptance criteria
- [ ] Assigning dids to users and challenges;
- [ ] Defining and supporting VC to assign to a user that enables the user to make changes to the "state" of the challenge. The VC is specific to a particular Challenge.
- [ ] new mutation to authorise a user to make state updates to a Challenge (so has both a user id + a challenge id), which results in the user being assigned the state update credential to the user
- [ ] update mutation for a challenge to check that the user has the needed credential, and that the update is rejected if they do not have the credential
