### ISSUE TITLE
Improved Error Handling: Authentication, Forbidden, BadInput + server catchall

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#205]
## Acceptance criteria Server
- [ ] AuthenticationError: when a user can't authenticate
- [ ] ForbiddenError: when a user is not authorised to access a particular api
- [ ] BadInput specific error type consistently on the api
- [ ] Server to not pass all exceptions directly through to the client

## Acceptance criteria Client
- [ ] AuthenticationError handling: try to refresh, or failing that re-authenticate
- [ ] ForbiddenError: gracefully inform the user that they do not have the full rights to access the data / carry out the mutation
- [ ] BadInput: inform the user that the request could not be accepted with the current data input + showing the message
