### ISSUE TITLE
Authorised api test harness: community admin role

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#206]
## Intro
The ability to have automated tests for the community admin role

## Acceptance criteria
- [ ] Able to login as part of api tests
- [ ] Defined set of accouts that are used for the test suit
- [ ] List of tests and implementation of those tests (to be expanded)
