### ISSUE TITLE
Config mgmt: Helm deployments for k8s

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#210]
Our infrastructure is becoming more complex with many dependencies and will benefit from Helm charts for deployments.
This should ease the CT adoption and deployment.

We are aiming for self-contained CT deployments.

## Acceptance criteria 
- [ ] Helm chart for deployment of the following components
   - [ ] CT Server
   - [ ] CT Web Client
   - [ ] Traefik
   - [ ] ELK
   - [ ] Sentry
   - [ ] mySQL
- [ ] All prerequisites (e.g. CRDs etc) should have automated installation as well
- [ ] All configuration variables should be parametrized

## Context
Also reduces load from DevOps
