### ISSUE TITLE
I: Search Expansion

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#211]
## Description
The current experience around search is not the most efficient one. This includes the search on platform level, but also on hub level or within messages. As the number of users and content on the platform grows, the search function becomes more important and thus key to focus on.

## Initiative / goal
Improve the search experience 

### Hypothesis
By improving the search experiences it will be easier for users to navigate to the most relevant content for them and possibly the place where they can and will contribute.

## Acceptance criteria and must have scope
- [ ] Platform level: search to include content as well
- [ ] Platform level: better search results, thus filter by whole word instead of string
- [ ] Set of classified or suggested tags to search on

## Design
Figma file:

## Additional context
Ideally the actual search should be done using an external service.

To include searching many more fields of data from within the platform
