### ISSUE TITLE
Code Cleanup - Server

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#214]
## Description
As a CT Engineering Manager 
I want to have clean and concise codebase
so that any change made introduces less risk and code is maintainable and extensible.

## Acceptance Criteria:
- [ ] Use for(thing of things) { thing... } instead of for(let i=0; i<things.length; i++)
- [ ] Caputre and rethrow only if you want to propagate specific exception type to the client or when you want to enrich the information
- [ ] Do not log verbose or warning or log level messages when error is caught and handled. An error is an error and needs to be treated as such
- [ ] Split AAD strategy in two strategies
- [ ] Add unit tests for key components
- [ ] One way of working with textID fields
- [ ] Make sure type casting is correct and we follow SOLID principles. We can't be casting ISomething to Something. Also, awaiting a method that returns ISomething makes casting the result (as ISomething) redundant.
- [ ] Configure BetterCodeHub to avoid false positives and false negatives

The resulting items should increase BetterCodeHub score to at least 8/10.

## Guidelines / later
- [ ] Modern JS and TS is used
- [ ] Increase tests to be at least 50% LoC of the codebase
- [ ] Refactor repeating code into methods
- [ ] Refactor longer service methods into multiple methods to make code more readable
- [ ] Decrease fan in / out where possible
