### ISSUE TITLE
Code cleanup - Client

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#216]
## Acceptance criteria
- [ ] One way for fetching of data via query + consistent usage of cache
- [ ] Update to have two sets of ESLint rules: dev + prod. The prod version should set unused variables as error.

## Later
- [ ] Tidy up warnings on the console: fixed by having two sets of ESLint rules
- [ ] Tidy up routing
- [ ] Review of responsiveness of every component
