### ISSUE TITLE
Atomic Entity CRUD operations

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#217]
## Description
As a developer
I would like to update entities with their relationships atomicly
So that there is no data loss.

## Acceptance Criteria:
- [ ] Updates are cascaded to contained entities
- [ ] Only fields in the DTO are updated
- [ ] Fields not in a DTO / not used (undefined) are left unchanged in the updated entity
- [ ] Updates are done consistently across all entities (one approach for all)
- [ ] DTO -> Entity mapping is done automatically with AutoMapper (or similar)
- [ ] Updates are atomic - the update either succeeds for the whole tree or fails for the whole tree of relationships
