### ISSUE TITLE
Users: Avatar upload service

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#219]
As a deployer of CT, I want to be able to have uploading of images for avatars

## Acceptance criteria
- [ ] Images only for now in terms of what types of artifacts
- [ ] Able to upload and store avatars for users, groups, organisation
- [ ] Size limit of selected file 2mb, with the client resizing to 400x400 pixels before submitting to server
- [ ] Separate mutation that stores the image in IPFS + returns the url
- [ ] Client able to upload + store avatars for users
- [ ] Deployments (k8s, docker compose) + Traefik configuration updated

## Context
