### ISSUE TITLE
Demo Population

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#221]
As a potential partner, I would like to be able to understand how my data could look in a populated CT instance

## Acceptance criteria
- [ ] Populator able to load data from a local spreadsheet (no authentication / saving of tokens)
- [ ] Demo repo updated to use local file for data population
- [ ] Spreadsheet to reflect more closely the CT logical data model
