### ISSUE TITLE
User Account & Profile Privilege Management

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#225]
Currently, we have the following gaps that need fixing regarding user management:

- [ ] Lower privilege user can edit the rights / remove higher privilege user, e.g. community-admin can remove global-admin. That shouldn't be possible
- [ ] Community-admin / Ecoverse-admin can assign users to all groups, which leads to privilege escalation. That shouldn't happen.
- [ ] Assigning users to groups that allow user creation/removal should assign Directory Writers and User Administrator permissions to the AAD accounts
- [ ] If a user is removed from a parent group (e.g. challenge) and stays in a derived group (e.g. member of an opportunity of a challenge), the removal should be propagated to the derived entity.
