### ISSUE TITLE
User applications for Ecoverse membership: api support

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#227]
As a registered user of CT, I want to be able to apply to be a full ecoverse member.: api

As an admin of CT, I want that it is easy for users to apply to become an ecoverse member - in a way that is effective for me.

## Acceptance criteria
- [ ] New **Application** entity with the following information:
-  the identity of the user,
- the identity of the entity being applied (fixed to the ecoverse for now)
- free text rational 
- answers to a set of questions
- created / last modified dates 
- [ ] Lifecycle default for the Application
- [ ] Application questions supplied via configuration from api
