### ISSUE TITLE
Enhanced builds + reporting

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#229]
As a developer, I want a good builds and status with output clear re QA coverage

## Acceptance criteria
- [ ] E2e build, separate from CI build, to run the e2e tests
- [ ] Code coverage reporting from CI build and E2E build, visible from the actual build log
- [ ] Investigate options to get the code coverage results easier to access and analyse

## Out of scope
Infrastructure dashboard to show code coverage, build status + other statistics
Do not integrate with BCH
