### ISSUE TITLE
Authorisation: Context aware 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#234]
As a Ecoverse / Challenge sponsor, I want to be able to manage my Ecoverse / Challenges(s).

## Acceptance criteria
- [x] New credential types for Ecoverse Admin, Ecoverse Member, Challenge Admin, Challenge Member, UserSelfMgmt
- [x] Each entity that can be acted on via mutations / fields to have an AuthorizationDefinition, that controls who is allowed to carry out what actions on that entity
- [x] A set of AuthorizationPrivileges to distringuish between different types of actions
- [x] AuthorizationEngine as a separate service for validating the set of credentials held by a user to a set of  
- [x] Separate services for the assigning of AuthorizationDefinitions to child entities / managing the rules for each entity
- [x] All authorization to be based on credentials, including user self registration + global roles.
- [x] Rename UserInfo to be AgentInfo
- [ ] Client updated
