### ISSUE TITLE
Communications: Community Updates

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#236]
As a challenge / ecoverse admin I want to be able to message all members

## Acceptance criteria
- [x] Able to send messages to a community, and all users that a member of that community receive the messages
- [x] Migration to latest matrix client sdk
- [x] Integrate types library that may now be available
- [x] Investigate is Dendrite is a drop in replacement for Synapse from the point of view of the matrix client sdk
- [x] Expand admin UI to allow ecoverse / challenge admins to be able to send messages to their community
- [x] Update messages to be in markdown
- [x] Subscriptions: in memory and limited scalability
- [x] Ability to delete existing messages them
- [x] Synapse admin container integrated into server-dev cluster

## Additional Context
Read more about the investigation results [investigation](https://hackmd.io/sTqRU3M5S1uyCXO4npWWdA)

**Comment by FloriSpoelstra** [comment]
Not sure if this epic also contains e-mail notification of new community messages. Would be great to have that (and people should of course also be able to unsubscribe from e-mail notifications).
