### ISSUE TITLE
Lifecycle support for entities: api

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#237]
As a portfolio manager, I want to have explicit lifecycles on the challenges / opportunities.

## Acceptance criteria
- [x] Explicit lifecycle entity exposed through graphql api
- [x] Lifecycle entity used by Application
- [x] Design pattern proven for how to pass in XState options to the lifecycle being executed (e.g. addMember to Community) 
- [x] Lifecycle entity used by Challenge and Opportunity, replacing previous usage of state field
- [x] Update client-lib + populator
- [x] Mutations for events on Challenge + Opportunity
- [x] Lifecycle entity extended to allow the machine definition to be retrieved via the api

## Additional context
