### ISSUE TITLE
Admin Tidy up + expansion

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#238]
As an ecoverse admin I want the Admin panel to be intuitive and clear, and to offer the ability to create all entities

## Acceptance criteria
- [ ] "Ecoverse Groups" section with the following options: "New group", "Edit groups"
- [ ] "Challenges" section with the following options: "New challenge", "Edit challenges"
- [ ] Within a challenge, offer a "Opportunities" section with the options: "New opportunity", "Edit opportunities"

## Additional context
For Organisations - see Organisations epic.
