### ISSUE TITLE
Organisations in UX

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#239]
As an deployer of CT, I want to be able to properly manage and interact with Organisations.

## Acceptance criteria
- [ ] Admin section: "Organisations" section with the following options: "New organisation", "Edit organisations"
- [ ] Admin section =>  New Organisation: able to create a new organisation (profile section to be shared with that from User? see below).
- [ ] Admin section =>  Edit Organisations: able to edit existing organisations (profile section to be shared with that from User? see below).
- [ ] Admin section =>  Edit Organisations: able to remove existing organisations 
- [ ] Organisation info panel: Shown by clicking on logos for a challenge (Challenge Lead logo)
- [ ] Organisation info panel to show: name, profile information (description, references, tagsets), challenges the organisation is leading
- [ ] Search: Organisations returned as part of search queries, and clicking on an Org return value to show the organisation panel
- [ ] Challenge Edit: for ecoverse admins, as well as being able to edit the Challenge context, they shold be able to add and remove organisations as Challenge Leads

## Other
Both organisations and users share the same underlying "Profile" entity, so hopefully the UI for editing this information can be split into a re-usable component?
