### ISSUE TITLE
Authentication flows to a separate package

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#242]
## Acceptance criteria
- [ ] Separate library, which can be external to CT, that contains the authentication flows that are required for client.lib, server
- [ ] Client.lib updated to use the authencation flows package
- [ ] Server updated to use the authentication flows package, and remove the dependency on client.lib.
