### ISSUE TITLE
Notifications: Framework and initial 4 events

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#243]
The platform needs to be able to trigger notifications, via various channels, to various users (actors)

As a user I want to be able to receive out of band notifications of updates to communities I am a part of.
As a user I want to have multiple event types that I can register to receive notifications for

## Acceptance criteria
- [ ] Separate service for managing + sending notifications
- [ ] Supported events: COMMUNITY_APPLICATION_CREATED
- [ ] Service on the server to trigger notifications to subscribed users
- [ ] Supported channels: email

Event types expanded to cover the following: 
- [ ] New user registration: admin notification 
- [ ] New user registration: Welcome email after someone has completed sign up (so different than email verification)
- [ ] Communication: Updates sent to a community I am a member of
- [ ] Communication: New discussion created on a community I am a member of

Email contents:
- [ ] Ability to embed links for the following entities: User, Organization, Hub, Chalenge, Opportunity.

**Comment by FloriSpoelstra** [comment]
Yess, this would be really helpful! I think the most important ones right now are:
- Notification to admin when new application is made (on eco, challenge and opportunity level). It is now very hard to manage because I have to click through all opportunities and challenges to look for new applications.
- Notification to member when application is approved (on eco, challenge and opportunity level).
