### ISSUE TITLE
AWS Support

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#245]
As a platform agnostic offering, I want to be able to run services also on AWS.

## Acceptance criteria
- [ ] Demo  kubernetes environment servers and elastic on AWS
- [ ] Terraforming of AWS K8s environment
- [ ] Key dev team members also able to work with AWS
- [ ] Documentation updated where needed
