### ISSUE TITLE
Authenticated command line clients

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#247]
As an admin, I want to be able to interact with CT servers that have authentication enabled

## Acceptance criteria
- [ ] client-lib to be able to take a token as part of its instantiation
- [ ] client-lib to expose the authentication configuration from the server so that it can be used to authenticate e.g. using tokenator
- [ ] client-lib to give an example of using tokenator to obtain a token
- [ ] populator to be able to take a token as part of its setup and use that to setup client-lib
