### ISSUE TITLE
Update automation suite and documentation

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Coordination#250]
As a QA, I want to have the automation solution documentation updated and the code base to be optimized 

## Acceptance criteria

- [x] Document automation tests structure under "server" repository
- [x] Optimize mutations from test/utils, to utilize the data from test-data.service by id instead to be hardcoded
- [x] Review the test suites and optimize duplicated code
- [ ] Research and set a scope of additional configuration for integrstion, e2e and auth tests to be run against different environments

## Note
Move error handling scenarios in separate test suite per service

## Note
In case of missing mutations, to be added/updated/fixed as part of the Epic

**Comment by Comoque1** [comment]
Last point `Research and set a scope of additional configuration for integrstion, e2e and auth tests to be run against different environments` out of scope for this epic.
