### ISSUE TITLE
Authentication Provider Framework

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#252]
As a customer of CT I want to have the more than one type of authentication option

## Acceptance criteria
- [ ] Server to support authentication via OIDC
- [ ] Supported authentication providers: simple provider, AAD via OIDC
- [ ] Documentation for how to extend to support another authentication provider
- [ ] Server creates a basic user profile for the authenticated user if the profile does not already exist
- [ ] basic profile: email, name
