### ISSUE TITLE
User profile management 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#253]
As an ecoverse host I want that users can easily engage with my ecoverse and be empowered to manage their profiles

As a User I want to be able to manage my profile within the platform.
As a User I want to be able to create a new account that I can then use to have a profile on CT.

## Acceptance critieria
- [ ] All users presented with a new entry on the top right menu for "My profile", which then includes the option to edit their own profile data.
- [ ] Admin panel to show the Members group and then the set of users that are not members would be the options to add on the right hand side (for now)
- [ ] Users are presented with an option to "Register" on the Ecoverse. TBD: how to tie in with creating an account for authenticating?
- [ ] User registration results in users that have a profile, but that are not "members"of the ecoverse
- [ ] upon registering a user is shown a screen with a "welcome message" and are encouraged to update their profile and apply to join the ecoverse / challenges 

## Notes
Authentication is fully isolated from this process; a user must first be able to create an account before they can create a profile. 

Applications: The ability to apply to become an ecoverse member is separate.

Notifications: for now there are no notifications triggered from the process

**Comment by atstoyanov** [comment]
Some thoughts about the user creation:
- Instead of automatically creating the UPN, we can ask the user to provide username like:
![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/b20ce16d-2350-416d-825f-c875afa0b08a)
If is possible to create user like this. because the `#EXT` in the name is awful.
Then we will create new user with the provided username. We should be able to check if this use already exists in the AAD, shouldn't we? 
- The password, could be provided by the user, or could be automatically generated and send to user by email like **onetime password**!

**Comment by techsmyth** [comment]
Re username, Agree that we can do this, was for now leaving this out of scope as it means additional change - admins etc are used to the current upn format, would not want to introduce additional change until we allow full control over the selection of the user name

Re password, User would anyway need to choose yet another password due to our AAD policy if they chose one themselves, so would not help them that much. Note we do not have email at the moment...main benefit of sending the email would be to have the email address verified, but not sure we are ready to actually start tracking that emails are verified yet.
