### ISSUE TITLE
UX Enhancements

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#257]
As a user I want to have a rounded out experience

## Acceptance criteria
- [ ] Server able to be queried for the opportunities that a user is a member of
- [ ] User profile to display read only the opportunities that a user is a member of
- [ ] User pop up panel, e.g. on search results, to also show the opportunity membership
- [ ] Default tags for supported ecoverse tagsets to have defaults per tagset as part of the server template
- [ ] User profile / User Group / Organisation profile to pick up these defaults
