### ISSUE TITLE
User login + sign-up processes

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#260]
## Description

As a user, I would like to be able to login as easily as possible.

As a new user, I would like to be able to create a new identity and then login with that identity

## Acceptance criteria

- [ ] Login link visible on home page, that launches a separate page where users can choose between different authentication providers including the simple auth provider. This page also needs to provide a link to the register page. 
- [ ] Register link visible on home page that brings the users to a new page where they can create a new accounton the simple auth service. Information to be captured : first name, last name, email. This form then does two things: creates the account for the user and creates the profile for the user on the server.
- [ ] After registering, users are redirected to a welcome page where they are encouraged to (a) complete additional information on their profile (b) apply to be a member of the ecoverse (c) look around and see where they want to contribute
- [ ] UX components related to simple auth provider separated from the other UI components (potentially later in a separate repo for these components)

## Additional Context
Based largely on the spotify login experience

No notifications or email verification for now
