### ISSUE TITLE
Server arch v2

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#263]
As platform architect, I want to ensure that the server architecture can scale and is extensible.

## Acceptance criteria
- [ ] Design for plugins / extensibility
- [ ] Consistency in the code base with clear namings and locations for different elements of the stack.
- [ ] Caching in general
- [ ] Usage of XState, when + how to apply it
