### ISSUE TITLE
UX Refinements

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#264]
As a user I want an appealing and intuitive UX

## Acceptance criteria
- [ ] Review of all aspects of UX in light of additions since Momentum
- [ ] Client UX to only show users the edit options that they have access to i.e. only show the edit rights that a user has access to
- [ ] Design of user on-boarding flow
- [ ] Design of ecoverse setup flow
