### ISSUE TITLE
api: Global identifiers

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#266]
As an architect, I want to be able to share types across multiple entities so that I can reduce the maintenance overhead of the code base and also make the api more understandable

## Acceptance criteria
- [ ] All entities to have an identifier that is globally unique
- [ ] Performance implications to be understood and documented
- [ ] Migration path defined for existing deployments
- [ ] all IDs should be ID scalar type

## Notes
TypeORM supports "uuid" for generated identifiers
