### ISSUE TITLE
Canvas: standalone support with templates

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#277]
As a user, I want to be able to effectively collaborate with others in creating the shared understanding of the challenge.

## Acceptance criteria
- [ ] Able to create and delete Canvas entities
- [ ] Able to display a preview of Canvases
- [ ] Able to checkout a Canvas for editing, and then to pop this up into a modal window
- [ ] Able to save, as well as save + checkin the canvas
Note: the canvas should not continuously save but only do so on an explicity user action
- [ ] Ask the user when they try to navigate away with edits not yet saved
 - [ ] Allow a canvas to be set as a template, which then blocks if for further editing
- [ ] Allow selecting of templates when creating a new canvas, and then make a clone of it
 
To discuss:
- [ ] which templates should be displayed when creating a new canvas?

## Context
See https://miro.com/app/board/o9J_l7YON5o=/ for more details
