### ISSUE TITLE
Website migrated to static content from git

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#290]
As a maintainer, I want to have the website also maintained out of git so that all the development processes can be applied to it and a wide set of contributors can maintain it.

## Acceptance criteria
- [ ] new repo: website, which has a develop + main branch + standard restrictions on the contents (CLA etc)
- [ ] website contents stored within the repo, and the code for the website is buildable from the contents
- [ ] there is a github action to publish the content based on an action triggered by tagging a new release within the repo that publishes the website (similar to what we have for publishing to dockerhub on server / client-web)

## Context
As we are making updates to the content of the website, we are also looking into hosting both the source and site itself on Github. Current thinking is to use https://gohugo.io/, a well known and blazing fast static site generator.
Content is based on markdown language and by hosting it in a public Github repo, anybody can contribute, like our other code.
