### ISSUE TITLE
api: domain model extensions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#294]
As an architect, I want that the domain model is extended to be suitable for a hosted service.

Some elements of the domain model is basic, having being put together for Odyssey in October 2020. It needs a refresh and to be significantly expanded. 

Additional information: https://hackmd.io/KMdlPRS6SGCnwRoyyUkz5w

## Acceptance criteria
- [x] New Collaboration entity, that derives from a shared interface and that has Relations + Projects
- [x] Expanded Context implementations, with a base interface and modules
- [x] New Context entity: EcosystemModel, which has ActorGroups
- [x] Aspects held by Context
- [x] New Scalar type TextID+ that is used for all TextID fields on input DTOs
- [x] Migrate from Ecoverse / Challenge / Opportunity to having a single Challenge entity that has child Challenges
