### ISSUE TITLE
cli

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#295]
As a developer or admin I want to have a cli that I can use to interact with a Cherrytwist server / platform

## Acceptance criteria
- [ ] able to login to cherrytwist
- [ ] able to carryout commands within that authentication context
- [ ] key commands: tbd...
