### ISSUE TITLE
Governance: ensure data privacy 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#297]
As a host of challenges, I want to be sure that the data that is managed by the platform is compliant with regulations

## Acceptance critieria
- [ ] Document cookie usage on the client
- [ ] Choose and implement a package for managing users cookie preferences
- [ ] Understand how to make the IPFS cluster is setup as being a private cluster (i.e. data is not propagated)
....

# Notes
Worth doing a review to see what other potential leakages there could be.
