### ISSUE TITLE
Performance + scalability testing

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#298]
As an architect I want to know if any aspects of the platform fail to scale.

TBD: the scenarios below should be documented in a MD file that is referred to from this issue 

## Scenarios 
- [ ] The following scenarios must be performed:
  - [ ] Scenario A: 500 user profiles, 10 challenges, and 10 organisations, 50 opportunities
  - [ ] Scenario B: 2,000 user profiles, 30 challenges, and 30 organisations, 150 opportunities
- [ ] Once all data prepared the following api calls must be performed with this amount of users:10, 50, 100, 500
- [ ] Queries to be performed as part of the test
     - users {context {references{id}}}
     - groups
     - challenges {context {references{id}}}
     - opportunities {context {references{id}}}
     - projects {data}
     - search (for groups, users, organisations)

- [ ] Mutations to be performed as part of the test
     - assignUserToGroup
     - removeUserFromGroup
     - updateProfile
     - updateOpportunity
     - createUser

## Test data
- [ ] Prepare test data above to be populated to performance environment
- [ ] Define mechanism for environment data cleanup

## Performance results
  - [ ] Stored for each api call and specific amount of concurrent user i.e.:
    - [ ] Scenario A results:
      - [ ] Query users:
        - [ ]  10 users perform "query users" - results
        - [ ]  50 users perform "query users" - results
        - [ ]  100 users perform "query users" - results
        - [ ]  500 users perform "query users" - results
      - [ ] assignUserToGroup:
        - [ ]  10 users perform "assignUserToGroup" - results
        - [ ]  50 users perform "assignUserToGroup" - results
        - [ ]  100 users perform "assignUserToGroup" - results
        - [ ]  500 users perform "assignUserToGroup" - results

## Environment

- Building the scenarios in test suite will be done against local environment
- First run of the tests will be run against Azure environment
- When capacity allows, the tests will be run against environment hosted on AWS

## Tools
 
- JMeter
- Gatling?

## Additional Context
The queries, mutations will be run against environment with authEnabled=false
Investigation, how different users, can update different (same) entities simultaneously 
Stress testing
- [ ] Goal of handling 2,000 concurrent users, and knowing where it starts struggling (where the bottlenecks are)
