### ISSUE TITLE
api: roadmap + design

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#299]
As an architect I want to ensure that we have a clear roadmap for the api evolution and patterns

To cover: more flexibility in how the client can retrieve multiple entities  at the same time. Caching considerations. Indexing / paging large numbers of results. 

## Acceptance criteria
- [ ] Evaluate and brainstorm best practices across graphql apis
- [ ] Prioritized list of key enhancements to be carried out, with spikes as necessary

To consider
- [ ] all <verb>On<entity> to be interfaces
- [ ] should groups be assignable like users are assignable?
