### ISSUE TITLE
Client: Technical design refresh

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#302]
As an architect, I want to ensure that the client design is clean and can be developed further

## Acceptance criteria
- [x] Define a convention for the directory structure
- [x] Define a convention for components (what and when)
- [x] Detail both conventions in a top level "development-setup.md" file
- [x] Carry out initial directory restructuring / renaming
- [x] XState to replace Redux for state mgmt, usage for authentication
- [ ] Logging framework for usage in browser (replacing console.log usage)
- [s] Carry out a gap analysis regarding components setup, and do easy / obvious renamings / movings
- [ ] Remove dependency on Bootstrap
- [x] Gap analysis from the current setup to a setup that is fully compliant with the identified design

## Additional Context
https://miro.com/app/board/o9J_l6J1tTI=/
Design gaps analysis - https://hackmd.io/@alkemio/SJeEp6CR_
