### ISSUE TITLE
Credential Based Authorization

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#307]
As a user of CT, I want flexibility and many roles that can be used to facilitate the interactions. 

## Background
The current setup for Authorization is via restricted groups on an Ecoverse. These groups are also used for global roles. This works when there is a single Ecoverse, but not if there are multiple Ecoverses.

In addition, the goal is to move to SSI style decentralization - for which centralized groups for managing access (ACLs) is simply not feasible. 

As such the first step is to move to credential based authorization - whereby a user or other actor is granted access by virtue of Credentials that they hold. 

Note: these are still Credentials that are managed by the platform, so not Verified Credentials as that term is used in the SSI space. But the critical change is to switch to using Credentials - as this drives the interaction patterns on the platform. It should then be a much easier step to start using VCs. 

## Acceptance criteria
- [ ] Users to be able to hold generic Credentials, in a way that can be expanded to other actors (e.g. Challenges, Opportunities, UserGroups, Organisations) later
- [ ] Authorization updated to check for possession of Authorization Credentials for the actors carrying out an action
- [ ] Remove the usage of restricted UserGroups
- [ ] Client updated to manage Credentials assigned to a User
- [ ] Client updated to manage the set of Users to which a Credential is assigned
- [ ] Client updated to use the information in the Credentials held by a User instead of MemberOf

## Additional Information
Raw working notes: https://hackmd.io/uoAWZwj7RAa0WbZjqEqFTg
