### ISSUE TITLE
User Applications UX

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#308]
As a registered user of CT, I want to be able to apply to be a full ecoverse member.

As an admin of CT, I want that it is easy for users to apply to become an ecoverse member - in a way that is effective for me.

Note: The server api already has support for User Applications, but it likely will need to be refined based on feedback from this Epic.

## Acceptance criteria
- [ ] Client: new button that invites users to apply to become an ecoverse member. The form creates a new Application entity, that captures the required information for the Application.
- [ ] All Applications are then visible to the Community Admin role via a new "Applications" section on the admin site. The Applications by default are filtered to show open Applications.
 - [ ] The Community Admin can approve / reject the applications
- [ ] Users able to use a similar pattern to be able to apply to join a Challenge

Later
- Takes an optional ApplicationsInput object that allows filtering the set of returned applications?

TBD: how to handle finding the set of open applications for a user? Can imagine that a user would very much like to be able to see if they have any applications open...

## Notes
Notifications are currently not supported; when they are then the applicant and the community admin should receive a notifications upon submission of the application (e.g. email) and for applicants when their application is approved / rejected.

For now we do not capture audit trails, though clearly would be nice to know who approved and when...
