### ISSUE TITLE
Multi-tenant demo environment with multiple ecoverses

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#313]
As a potential user, I want to understand how the platform with multiple ecoverses looks. 

## Acceptance criteria
- [x] New demo environment: demo.cherrytwist.org
- [x] Ecoverses on existing demo environments (sdgs, valuetracks, digicampus) recreated on new demo env
- [ ] The-hague environment as a private ecoverse
- [ ] Old demo environments decommissioned
- [ ] Demo repo updated with latest client / server images, and an updated sample file with valid image links
