### ISSUE TITLE
Aspect Templates: Hub management

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#314]
As a hub admin I want to be able to customize my hub.

## Acceptance critieria
- [ ] Design for how templates are managed at the platform and hub level, that is consistent across all data types
- [ ] Ability to manage Aspect Templates at Hub level
- [ ] Aspect templates business logic updated as per design
- [ ] Authorization around the management of templates

## Context

Design MD: https://hackmd.io/zQ5lKDbfSqmW_RhY-4gDYg

Hub template management:
https://xd.adobe.com/view/39240558-394d-42a4-a227-229d1105578e-6c77/
