### ISSUE TITLE
Server test harness refresh

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Coordination#315]
## Initiative / goal
Test utilities and remaining tests are updated to latest changes against server repository

## Acceptance criteria and must have scope
 - [x] User management and Lifecycle tests are updated to use unique identifiers
 - [x]  Search tests are updated to use unique identifiers
 - [x] Enable and optimize Opportunity tests 
 - [x] Test-data service is updated with respect to the latest server changes
- [x] Initial single data setup scenario authorization test harness is in place as per spreadsheet: [privileges]
(https://drive.google.com/drive/u/1/folders/1gM5fTVFvQIqIQI8dtmK5wuo13bVST71O)
