### ISSUE TITLE
Authentication: Github support; admin; +++

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#321]
Features to build upon the base OSS IdP provider:

- [ ] Add login with github support
- [ ] how does a platform admin trigger resets / remove accounts?

Other:
- [ ] whoami exposed through graphql 
- [ ] improved self service flows:
   - [ ] account recovery
   - [ ] account settings
- [ ] Oathkeeper Master access rules for easier k8s management
- [ ] Alignment of the Kratos profile with the domain model profile: what data comes from where? 

## Additional notes
The user flows from Kratos also prompt the user to edit their profile information that is managed there, may want to pull some of our fields for example from kratos.
