### ISSUE TITLE
Client: Multiple ecoverse support

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#328]
- Mockup here (https://wireframepro.mockflow.com/view/Ma6964ec9e05d4842bfcc458397fcef561622124883927#/page/Dab1c865119263e53f91c0b4e8cc80fde)
- The branch is client-web#homepage-prototype
- An old version of Aldert's work that was part of the inspiration for the prototype here (https://xd.adobe.com/view/09cd710e-81a5-4c37-b7d4-0cd34d583aac-5c9e/screen/30f9b114-63af-4b3d-b3b4-9772d84eda47/)

## Acceptance criteria
- The app navigation is updated according to the idea presented in the #homepage-prototype branch
- The ecoverse page is the landing/home page
- Multiple ecoverses are loaded based on the current user where:
   - [ ] The ecoverses in which the user is a member of are distinguished
   - [ ] The ecoverses in which the user is a member of are loaded and potentially paginated

- Ecoverses are displayed in such a manner that:
   - [ ] When the user is logged a segment displays his ecoverses in browsable fashion, otherwise the segment is not present
   - [ ] In both (logged in/not logged in) cases there is a way to explore ecoverses and visualize them in focus mode where ecoverse details are displayed: name, logo, challenge context, etc.

- [ ] Ecoverse summary (only when not logged in): Displays platform information about contained ecoverses, challenges, members
