### ISSUE TITLE
Administration of ecoverses / challenges

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#329]
As an ecoverse admin, I want to be able to manage all aspects of the ecoverse

## Acceptance criteria
- [x] Ecoverse administration page to have an additional section: Authorization, that allows managing of "ecoverse-admin" credentials tied to that ecoverse
- [x] Ecoverse admin page to allow choosing the Ecoverse Host. Note: there must always be exactly one. 
- [x] Challenge administration page to have an additional section: Authorization, that allows managing of "challenge-admin" credentials tied to that challenge
- [ ] Challenge admin page to allow specifying the Lead organisations (adding / removing).
- [x] Allow deletion of challenges + opportunities from admin pages
