### ISSUE TITLE
Server api test harness separated

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#333]
As a QA I want to have an api test harness that can be run against any end-point

## Acceptance criteria
- [x] All api level tests separated out to a new repo: server-api-tests
- [x] Nightly build, based on Travis, on server 'develop' branch updated to that the test harness (from server-api-test) is executed
- [x] test folder removed from server repo
