### ISSUE TITLE
Authorization: User privileges + usage to determine the contents displayed on the client

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#334]
As a user, I want the administration of the platform to be easy to carry out
As a User I only want to be presented with the actions I have privileges to carry out
As a user I want to see the pages I should have read access to
As a user / developer I want to know who should be able to see what information

## Acceptance criteria
- [ ] Only show users the administration options that are relevant to them / that they can carry out
- [ ] Only show cogwheels on hub / challenge / opportunity if the user has the "UPDATE" privilege
- [ ] ...

- [ ] MD file that describes the different visibility levels and what pages are visible to what roles
- [ ] Public / private hubs, challenges
- [ ] 

## Additional Context
[Client web page visibility spreadsheet](https://stichtingcherrytwist-my.sharepoint.com/:x:/g/personal/svetoslav_alkem_io/EcTJIdgr_P9NuK22WEOOjh0BIzTgND_Uh_JEiVhIrrPyXw?e=BHDn22)
