### ISSUE TITLE
Community: server messaging robustness

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#335]
As a user I want to be able to send message to other users

## Acceptance criteria
- [ ] Feedback points from review addressed
- [ ] No dependency on domain model from services
- [ ] Full code review, with all todo's removed
- [ ] ...
