### ISSUE TITLE
Documentation refresh

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#336]
## Description
As a contributor I want to be able to understand the capabilities of the platform

## Acceptance criteria

- [x] Identities + Credential Based Authorization approach
- [x] Templates
- [x] General tidy up
- [x] Logical domain model updated: Opportunity, Context.Visual, VC, Auth Policy, nameID, UUID,  ...
- [x] Identifiiers: nameIDs + UUIDs
- [x] Communication: usage of Matrix; rooms on community + for user-user
- [x] Lifecycles, usage of XState
- [x] Community Mgmt, including Applications
- [x] Security.md file is out of date
- [x] Containerisation usage / microservies (current docs gives a classic layered arch approach which is not accurate)
- [x] Refresh the images that are used in the Technical Design to use the branding colors

## Additional Context
