### ISSUE TITLE
Client: Consistent styling

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#343]
To ensure a standard end user experience, and for developer productivity / clarity.

## Acceptance criteria
- [ ] Create a branding style guide for the client
- [ ] Apply branding guidelines to existing UI
- [ ] Remove contents of current 'styles' folder

## Additional Thoughts 
From alkem-io/client-web#910
If the button name is changed to Back it will mean that the user will be navigated to the previous page and the user will not know that "all" changes will be lost. So Cancel is more suitable for that action.
All is in quotes because not all data will be lost. Adding/Removing References won't be reverted. Further information on that topic in #909.

Further discussion is required.
Agenda:

Normalize buttons usage on forms. Current state is a bit messy and not all similar pages have same buttons. (Edit Ecoverse has only Save button. Edit User has Delete, Cancel, Save ...)
On dialogs: the dialog have close button which can be used instead of Cancel
On pages: see next point
Where we need Save, Delete, Back, Cancel, OK?
Do we need Cancel button on edit page at all? We can leave the user with the option to press Back button on the Browser.
Because we don't use UI state navigating back will lose all changes made by the user:
solution 1: implement persistent UI state
solution 2: add navigation check and alert the user that all changes will be lost.
