### ISSUE TITLE
Search: Result display, content

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#344]
As a user, I want to be able to search more types of data, and more effectively understand the results returned.

## Acceptance criteria
- [ ] Expand data types included for searching to include: ecoverse, challenges
- [ ] Update client to be able to display the additional data types that are returned
- [ ] Improve the information that displayed on user cards / org / group cards
