### ISSUE TITLE
Communication: User-user interaction

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#345]
As a user I want to be able to interact with other users

## Acceptance criteria
- [ ] Spike to understand capabilities / integration options for Matrix React SDK
- [ ] Users able to message each other
- [ ] Live updates displayed in near real time on the client if new messages are received while the user is on the page

## Additional information
This is not about having the functionality production ready, but about having a working demonstrator for the end - end flow. 

To consider later is allowing users to opt-in to communication / invitations to connect etc.

Note: also can look at notifications for when the user is not on the page separately.

Note: there is an old branch on this topic, it is likely to be used primarily as a reference.

**Comment by FloriSpoelstra** [comment]
Would be great to also have e-mail notification related to this epic, to draw people to the platform.
