### ISSUE TITLE
UX: Guidelines, org / user profile, community page, accessibility

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#352]
As a User I want to have a UI that enables me to effectively carry out the jobs I want to do

## Acceptance criteria
- [ ] Definition + documentation of UX colors / standards
- [ ] Redesign of community page, user profile page, organization profile page
- [ ] Usability: migration to accessibility standards compatible colors
- [ ] Usability: addressing tabbing order (to be prioritized / evaluated)

## Additional context
Latest mockups: https://xd.adobe.com/view/a324d49f-9037-4809-87d3-4820f1e110a1-f677/

**Comment by techsmyth** [comment]
Moved last open issue to UX switch to tabs so that we can clearer see the topics that are open
