### ISSUE TITLE
Integrated help system / guidance

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#364]
As a new user to the platform, I want to be able to understand what the platform can do and how to use it

## Acceptance criteria
- [ ] Help system available with SAAS usage related documentation 
- [ ] Guidance system for new users to help them get going on the platform
- [ ] Explanation of key terms, especially Hub, Challenge, Opportunity
- [ ] Details of new releases / features

## Notes
How does the contents of this help relate to the repository level documentation regarding platform concepts?
