### ISSUE TITLE
Invite Users to Space

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#365]
## Description
There are multiple spaces that will start onboarding more members and therefore invitations become more and more important. Also the settings around membership and authorization are often unclear. For example you can only add leads that are already member and what the distinction is between lead and admin. The settings are in need of a refresh so when adding invitations, the community settings can already be taken into account. 

## Initiative / goal
Simplifying the onboarding and management of new community members

### Hypothesis
Providing the ability for space admins to invite users to their community is key to helping them make their community come onto Alkemio

## Acceptance criteria and must have scope
Admin: 
- [ ] Ability to invite existing users 
- [ ] Ability to invite external users (without a profile on Alkemio), providing a welcome message as well as the user first / last name
- [ ] Remove ability for space admins to ADD users (dependent on COMMUNITY_ADD privilege)

User:
- [ ] In menu of profile avatar (top right) new option for pending invitations/applications 
- [ ] To show number of invitations or applications
- [ ] Clicking on invites shows dialog with open invitations

Server:
- [ ] Space admins able to client on INVITE and choose an existing User to invite to join the space
- [ ] admins able to see open invitations, when they were sent and which have been accepted 
- [ ] User then receives an email notification, including the link to the space they are being invited to join
- [ ] admins able to delete invitations not yet accepted

Later: 
- [ ] Admins able to bulk upload user details from a spreadsheet

## Stakeholders
VNG + Digital Twin 

## Timeline
asap

## Design
Figma admin: https://www.figma.com/file/t3XQACWEsDa3r8YPyihmsp/Settings---refresh-Q2%2F3-2023?type=design&node-id=10%3A4&t=PA9DVRvZ0fGff7W2-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/4656b7b1-173c-415e-8386-a9ddfc5f247c)
Figma user: https://www.figma.com/file/CAveHHIWJanVVXIWis2p1H/Homepage-refresh-2023?type=design&node-id=0%3A1&t=Gd23bYwSvJaDMOXq-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/367477cb-463e-4b9c-90e3-1fc7d3a0e731)

## Additional Context
https://github.com/ory/kratos/issues/2525

**Comment by FloriSpoelstra** [comment]
Would be great to have this functionality also on challenge level (if possible). Since the existing communities we are onboarding are always centered around a specific challenge.

**Comment by SimoneZaza** [comment]
@techsmyth  Can people also be invited to a Challenge or Opportunity?

**Comment by techsmyth** [comment]
@SimoneZaza focus for now is inviting to spaces. Lets do challenge invites as an extension.
