### ISSUE TITLE
Search: Opportunties; expanded set of searched fields

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#368]
As an ecoverse / challenge admin, I want to be able to find Opportunities that are using a particular technology

## Acceptance criteria
Server:
- [ ] Search results expanded to return Opportunities
- [ ] Searching on Challenge / Opportunity to search also on the following context fields: background, impact, who, vision
- [ ] Authorisation: only return the opportunities that the currently logged in user has READ access to (protect data in private ecoverses)
Client:
- [ ] Client: add search result card and popup for Opportunity
- [ ] Client filtering to also allow filtering by Opportunities

**Comment by FloriSpoelstra** [comment]
Can't wait to have this :-)

I'm not sure how search currently works: is it only searching tags or also text? I would prefer the latter. I think people will, for example, want to look for innovation projects related to a specific organization/their organisation. These are always mentioned in the text but I am currently not tagging them (because sometimes there are just too many involved).

**Comment by FloriSpoelstra** [comment]
I would like to see the search function expanded further:
- Search function also searches in titles and text (not only tags)
- Search function also searches partially correct matches. For example: searching for chat will also give a hit on chatbot (and preferably also vice versa).
