### ISSUE TITLE
Client: Redesign v2

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#387]
As an architect, I want to ensure that the client design is clean and can be developed further

## Acceptance criteria
- [ ] Expand usage of XState: roadmap?
- [ ] Components re-use / design?
- [ ] QA / test harness approach
- [ ] Usage of codegen for working with graphql queries (per component?)
- [ ] Leverage material components instead of custom
- [ ] Fix caching issues
- [ ] Routing updates following coding guidelines + Credential Based (Resource) Authorization

## Additional Context
- Directory structure food for thought: https://www.taniarascia.com/react-architecture-directory-structure/) 
- Components food for thought: https://medium.com/wesionary-team/types-of-react-components-you-should-know-251cceacd8ac

https://miro.com/app/board/o9J_l6J1tTI=/
Design gaps analysis - https://hackmd.io/@alkemio/SJeEp6CR_
