### ISSUE TITLE
Authorization: Delegating roles; Org mgmt; Definition => Policy

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#388]
As an EcoverseAdmin I want to be able to assign other EcoverseAdmines + ChallengeAdmins within my ecoverse. Also for Opportunities

## Acceptance Criteria
- [x] add mutations for assigning / removing the following credentials: EcoverseAdmin, ChallengeAdmin, OrganisationAdmin, OpportunityAdmin
- [x] Update client to use the new api calls
- [x] Rename from AuthorizationDefinition to AuthorizationPolicy
