### ISSUE TITLE
Community Page + visibility

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#393]
As a user I would like to be able to explore and connect for Communities on Ecoverse, Challenge + Opportunitie

## Acceptance criteria
- [ ] New 'community" page that is shown on clicking the 'explore + connect' button 
- [ ] Route for the page would be 'community' after the previous page e.g. https://hub.alkem.io/digicampus/community
- [ ] Page contents would include: (a) List of all members, clickable like on search (b) list of members filterable (c) host for ecoverse, lead orgs for challenges (d) other affiliated organisations (e) groups 
- [ ] ...

## Additional context
Actual page contents to be worked further.
