### ISSUE TITLE
Operations vNext

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#402]
Bucket (currently unscoped and unrefined) about the next set of activities that need to be done to improve our infrastructure:

- [ ] IPFS Backups - currently the IPFS data is not being backed up manually, the only form of redundancy is done based on the storage class used
- [ ] Security refinements - improve key management, secrets vs configuration, review exposed endpoints and protocols. Review CSPs.
- [ ] MySQL / Postgres backups archived, encrypted and uploaded to a 2nd location / bucket
- [ ] Improved dashboards / monitoring / notifications
- [ ] Add helm charts upgrades to automated deployments
- [ ] Automatic publishing to npm for packages on npmjs on a release

**Comment by techsmyth** [comment]
Duplicate with #148
