### ISSUE TITLE
Communications: Scalability + management ++ (bucket)

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#406]
As a user / community admin, I want a performance setup for communications on the platform

## Acceptance critiera
- [ ] Management / configuration of a pool of agent connections to Matrix. Expose an additional platform parameter(s) for controlling this?
- [ ] Integration of a scalable messaging broker
- [ ] Expand the options for management of the Matrix server: clean up of orphaned rooms / tooling to use. 

- [ ] able to do backups / restore across environments i.e. able to take alkemio, kratos + synapse db from prod + deploy into acc + it all "works"

- - [ ] Able to edit / delete previous messages
Note: Edit/Delete messages is not available in the current Alkemio API and would require investigation. Starting point for edits might be [this](https://github.com/matrix-org/matrix-react-sdk/blob/ac309a0d08159c321690ee613e297b20443c4db1/src/components/views/rooms/EditMessageComposer.tsx#L324). Might be a good idea to tackle edit/delete in a separate issue.

**Comment by Enderedne** [comment]
I would suggest splitting this epic in two - one for scalability where we additionally spend time on evaluating the current system limitations using performance tests. etc. and one for management - I believe it can easily grow in size and seems like it's already big enough to be a standalone epic.
