### ISSUE TITLE
Organisation pages, owner role + expanded profile 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#412]
## Description
As a user I want to be able to have more information about an organisation
As an organisation, I want to be able to have a profile page on the platform

## Acceptance criteria
Org roles + profile page
- [x] Add a new credential type: "organisation-owner", with associated mutations for assigning / removing
- [x] Logic to verify that there is still at least one organisation-owner when removing a user from the organisation-owner role
- [x] Add an OrganisationPage that is available at the following URL: /organisation/<org-nameID>
- [x] Expand the organisation entity to have the following fields: Display Name (needs to be unique); Legal entity name (required if hosting an ecoverse); domain (what is verified) eg. alkem.io; website; contact email address (what is verified); verification level: enumeration with only "not verified | manual attestation" for now.
- [x] Update mutations related to organisation creation / update to work with the new fields
