### ISSUE TITLE
Notifications for beta testers

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#419]
## Description

The User should be able to access his notifications in the app through a unified inbox.

## Initiative / goal

Users should not have to go to their mailbox to see messages from other users or other notifications. Currently, we rely on the activity logs for users to see notifications that require additional navigation and change of context from what the User was doing on the platform.

### Hypothesis

Users should have easy one click access to their notifications.

## Acceptance criteria and must have scope

- [ ] Working end to end
- [ ] Limited set of events (3)
- [ ] Events only come through for beta testers
- [ ] Button only visible for beta testers

## Stakeholders

Product/Engineering

## Timeline

February 2024

## Design
Research: https://alkem.io/building-alkemio/challenges/mydashboardhomep-4715/opportunities/notificationsonthe-7063/dashboard

Figma: https://www.figma.com/design/pRGFSyng0dxovpvlaWGI8t/Notifications?node-id=295-5783&t=Zqp4kdh0YykbQq6C-1

---------
#OLD
## Description
As a user I would like to have an overview of all the notifications / actions awaiting my attention on the platform

## Acceptance criteria

- [ ] Overview of all applications / other actions awaiting attention for an ecoverse / challenge admin, across multiple challenges / ecoverses
- ...

## Additional Context
Requested by Flori

**Comment by jeroentskui** [comment]
For @jeroentskui 

have a look at the design; and where to place the buttons in the notifications and read and unread and delete; 
https://www.figma.com/design/pRGFSyng0dxovpvlaWGI8t/Notifications?node-id=295-5783&t=Ns1fmWbGjVxIunfN-1
