### ISSUE TITLE
Communications: Community discussions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#423]
As a user I want to be able to ask questions to a community.

## Acceptance criteria
- [ ] Users able to ask questions within the context of a particular community
- [ ] Community admins (ecoverse / challenge admin) able to reply to questions
- [ ] Community admins able to delete messages that are not appropriate
- [ ] Q&A visible on community panel, as well as on community page
- [ ] ....

Admin
- [ ] queries to allow check the health status of the matrix integration: -rooms, user-matrixID, ...
- [ ] remove orphaned rooms on synapse?

Separate:
- [ ] Subscriptions/updates to the client will be needed for discussions
