### ISSUE TITLE
Authorization: Opportunity Admins

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#424]
As a Challenge Owner I want to be able to delegate rights to manage a particular Opportunity

## Acceptance criteria
- [ ] New credential: Opportunity Owner, with associated mutations to assign / remove
- [ ] Admin: allow assignment of Opportunity Owner to members of an Opportunity
- [ ] Admin: restrict users that can be assigned to members of the Opportunity
