### ISSUE TITLE
Renaming: Ecoverse ==> Challenge Hub (visible)

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#430]
## Description
As a user I want as simple as possible set of terms that I need to understand to use the platform

## Acceptance criteria

- [ ] UI updated to use the term "Challenge Hub" instead of Ecoverse
- [ ] Conceptual design / other documentation updated to use Challenge Hub
- [ ] Populator updated to use ChallengeHub

## Additional Context
This updated to happen in two phases: first on the front end in terms of how the contents are presented to users (urgent), then backfilling to update the server.
