### ISSUE TITLE
Opportunity: Community, domain model, usability, submission, ...

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#436]
## Description
As a  user I want an effective page for interacting around Opportunities
As an organisation I want my association with an Opportunity to be visible. 
As a user group, I want my association with an opportunity to be visible.
As a member of a challenge I want to be able to submit ideas that can be reviewed

## Acceptance criteria

- [ ] Domain model extended to be able to track organisations that are associated with an Opportunity (extend generically?)
- [ ] Client updated to be able to show the associations on both the main opportunity page and the related community page for the opportunity
- [ ] Admin pages updated for managing the community
- [ ] UX redesign
- [ ] Domain model updates identified and planned in
- [ ] ...

## Additional Context
The current opportunity page is due a significant overhaul

**Comment by techsmyth** [comment]
Completed with community model enhancements
