### ISSUE TITLE
Release management improvements

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#445]
As a devops / release manager I want that releases are safe / reliable

## Acceptance criteria
- [ ] Authorization tests are extended and executed
- [ ] authorization policies are reset standard on releases
- [ ] releases to restart all key services and check values returned by k8s
- [ ] Expand automation of release mgmt process
- [ ] Change log / update tracking
