### ISSUE TITLE
Notifications++

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#448]
## Description
As a user I want to have multiple event types supported by the platform that I can get notifications on

## Acceptance criteria

- [ ] Expand notifications support to include the following event types: ...
- [ ] …

To refine further:
- [ ] User profile extended so that users can subscribe to notifications for particular events
- [ ] Supported events: "Applications to Ecoverse / Challenge / Opportunity"
