### ISSUE TITLE
Notifications: opportunity / challenge creation

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#453]
## Description
As a user I want to have multiple event types that I can register to receive notifications for

## Acceptance criteria
Event types expanded to cover the following: 
- [x] New Opportunity / Challenge created
- [ ] org owner requests manual verification
- [ ] org owner receives notifiction that manual verification request was approved / rejected
- ...
