### ISSUE TITLE
Notifications: new users; communication updates + new discussions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#459]
## Description
As a user I want to have multiple event types that I can register to receive notifications for

## Acceptance criteria
Event types expanded to cover the following: 
- [ ] New user registration: admin notification 
- [ ] New user registration: Welcome email after someone has completed sign up (so different than email verification)
- [ ] Communication: Updates sent to a community I am a member of
- [ ] Communication: New discussion created on a community I am a member of

Email contents:
- [ ] Ability to embed links for the following entities: User, Organization, Hub, Chalenge, Opportunity.

Note: do not support direct linking to e.g.. applications or to the admin settings for now. 

## Additional Context
Events that are already done:
- user application to join ecoverse / challenge: informing both the user and the community admin

**Comment by techsmyth** [comment]
Merged with the initial notifications epic so we can see all notifications issues in one place
