### ISSUE TITLE
Managing the user-organization + org roles relationship

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#466]
## Description
As a user I would like to be able to be associated with an organization

## Acceptance criteria

- [ ] Users should be able to apply to be associated with an organization
- [ ] Organization admins/owners should be able to approve / reject such requests
- [ ] Users should see the application status
- [ ] Notifications should be in place to update both users and admins 

## Additional Context
Connected to #817

**Comment by techsmyth** [comment]
Duplicate of epics in Q4 2025
