### ISSUE TITLE
Communications: Community Discussions v2

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#475]
## Description
As a user I want performant discussions
As a client dev I want an effective domain model
As an admin I would like to be able to query the matrix instance for information

## Acceptance criteria

- [ ] Evaluate end-end performance of discussions
- [ ] Expand functionality
- [ ] Refine the domain model in light of findings

To discuss:
- [ ] Ability to edit existing messages 
- [ ] Design document showing what maps to what / how it all integrates
- [ ] What admin functions are needed to e.g. reset communication rooms on a community

Expand admin communications capability
- [ ] reset the updates room on a community?
- [ ] Verify that direct rooms between users are 1-1?

Later
- [ ] Usage of ws package recommended by nestjs - **Not applicable** - available after nestjs@9.0.0

Later:
- how the message time is displayed
- ability to quote when replying
