### ISSUE TITLE
Community Membership on Opportunity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#484]
## Description
As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Allow users to apply to become members of an Opportunity
- [ ] Enable Discussions tab and add discussions preview on Opportunity dashboard
- [ ] Update logic around membership of Opportunity
....

**Comment by techsmyth** [comment]
Duplicate of #616
