### ISSUE TITLE
UX: Image usage and rules

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#486]
## Description
As a user I want to be easily able to upload in the right format visuals associated with my entities

As an admin I would like to be able to upload the visual assets that are used to display the ecoverse/challenge/opp

## Acceptance criteria
- [ ] New entity: Visual, that has the following fields: name, xRes, yRes, aspectRatio, allowedTypes: string[], url: string
- [ ] new mutation to allow uploading an image to a Visual that validates the above fields (to be discussed re logic)
- [ ] context.visual entity migrated to be an array of Visuals. Two such visuals: banner, bannerNarrow
- [ ] Client: provide information to users about the desired image resolution / ratio / formats to the user
- [ ] Client: allow the user to convert / select the right image contents from allowed file formats

## Additional Context
To cover the following image usages:
(user, organization, usergroup).profile avatar
(hub, challenge, opportunity).context.visual.[avatar, banner, background]

See also:
https://github.com/alkem-io/alkemio/discussions/492
