### ISSUE TITLE
Private challenges

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#501]
## Description

An a hub admin I want to be able to make challenges private

## Acceptance criteria

- [ ] Ability to set the flag about privacy on a challenge
- [ ] The flag is preserved after the authorization policy on the hub is reset
- [ ] The challenge should not be returned in search results for users that do not have access to it
- [ ] The challenge should not be visible to non-admins on the hub page

## Additional Context
Note: still some usability aspects / authorization aspects to be worked out around this card.

**Comment by larssondenise** [comment]
@techsmyth ready to be estimated?

**Comment by techsmyth** [comment]
Yes this is ready.
