### ISSUE TITLE
Context: Capturing community input 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#511]
## Description
As a user I want to be able to share information relevant to a particular Hub / Challenge / Opportunity

## Acceptance criteria

- [x] Aspect entity used as part of Context gathering, at each of the three levels
- [x] Users that are members of a Hub are able to submit
- [x] Associating an image per Aspect
- [x] Members able to comment on an Aspect
- [x] Free form tags 

## Additional Context
https://xd.adobe.com/view/7c98070c-f9d6-425a-8e0d-aa54f4fc3758-29cb/
