### ISSUE TITLE
Subscriptions: Working when server is horizontally scaled 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#525]
## Description
As a user I want near real time updates

## Acceptance criteria

- [ ] Subscriptions working reliably for the following situations: discussions, updates, comments, canvases

## Additional Context
Results from all hands testing

- [ ] Subscription error:
   - [ ] Web sockets: unauthenticated error is thrown. (could happen when user navigate from challenge to opportunity dashboards page) 
   - [ ] When user is on a discussion and receives a message the page is refreshed
- [ ] Discussions
  - [ ] 1 hub member receive and 1 doesn't receive **hub** discussion message
  - [ ] Global community admin, member of community doesn't see message sent by him to a discussion
  - [ ] Client doesn't pick data properly on **challenge** discussion for sender
    - [ ] Member creates a discussion, no one sees it on dashboards page (challenge level)
    - [ ] Challenge member creates a discussion, no one sees it on dashboards page (challenge level)
- [ ] Updates
  - [ ] Hub admin doesn't receive updates from challenges 
- [ ] Canvases:
   - [ ] Display the user who checked-out a canvas
   - [ ] Add ability for admins to checkin left checkout canvases
   - [ ] Enrich canvas subscriptions. For example: subscription for new canvas, for deletion, for changed state, while on canvas page
