### ISSUE TITLE
Multiple Language Support on the Client: EN, NL

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#530]
## Description
As a user from NL  I want to be able to see the labels / descriptive text in my own language

## Acceptance criteria

- [ ] Language files for: EN, NL
- [ ] Demonstrator using a React component to allow the users to switch between languages
- [ ] MD file detailing out the options for full support
