### ISSUE TITLE
Organization direct membership

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#542]
## Description
As an organization admin I want users from my organization to directly be assigned to my organization
As a user I want to be able to use my organization membership to access / join communities

## Acceptance criteria

- [x] Users to be directly assigned to an organization upon signing up if their **verified** email address matches the domain for an organization
- [ ] Organization creation + update rules updated to prevent more than one organization "owning" a particular domain
- [x] Organizations able to specify that users with emails matching their domains, and that are verified, are automatically granted membership of that organizations
