### ISSUE TITLE
Community Terms: phase 1 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#554]
## Description
As a Community,  want to ensure that all members agree to a consistent set of terms

## Initiative / goal
Innovation Library
Effective Communities

### Hypothesis
Communities need to have clear rules for how they interact with each other, what happens with value generated etc. 

## Acceptance criteria and must have scope
- [ ] Member Guidelines profile
- [ ] Possibility for admins to set/update Member Guidelines
- [ ] If terms are set, then the client should make those terms available to the User as part of the Apply / Join UI
- [ ] Invitations: terms to be visible as part of invitation acceptance / joining / applying

**Templates**
- [ ] New template type: community guidelines
- [ ] Add default platform guidelines to space when it is created. 

Content term is mostly about the license that will be applied to content that is uploaded within the space. This is a key one for TIP.

TBD: to be scoped via Innovation Agreement Templates, TIP

## Stakeholders
Digicampus
TIP
...

## Timeline
tbd

## Design

https://www.figma.com/file/RJ72PKZ2aGQkbB7KKpQqha/Community-Rules?type=design&node-id=0%3A1&mode=design&t=0TdSSOHJt7tfDtcS-1

Excalidraw (work in progress): https://app.excalidraw.com/s/4BCnkZqaP0t/2GDzhpunmgM
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by techsmyth** [comment]
@sander-cb fyi - suggest you follow this epic

**Comment by techsmyth** [comment]
@SimoneZaza just realized that we had not covered the community guideline templates in the above description...to be discussed. May want to have these also selectable either directly on space creation (or not, simpler?), and then updatable from platform library when editing them?

**Comment by SimoneZaza** [comment]
@techsmyth Regarding the Space create flow - I think we should keep this as simple as possible. As defaults we can then either have no guidelines, or a generic but nice text about respecting each other etc. 
As long as we don't have guidelines on Challenges, I think it overcomplicates things to add them to the Space Templates (in the UI). I would prefer to only have a library button inside the Member Guidelines block in the community settings, and from there be able to choose a template. This does mean that if you choose a new template, you loose the text that you had before. But with a proper warning that should be ok.
