### ISSUE TITLE
Classification TagsetsXXXXXX - dead

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#558]
## Description
As a hub admin I want to be able to control the set of tags that are used 

## Acceptance criteria

- [ ] Add notion of a classification tagset that can be managed per hub, with a name and a set of allowed values
- [ ] Design for how the interaction with a classification tagset happens
- [ ] Specification for where the classification tagset would be used e.g. per challenge, per aspect, ...

## Additional Context

This is something that UWV would like for assigning their strategic priorities to all the entities. 
Also came up from Digicampus, and SZW. 

One option would be to simply have a list of allowed values for tagsets on the relevant entities. Or to have two tagsets, one free form and one for the classification tagset.

**Comment by techsmyth** [comment]
Closing as is a duplicate of #776
