### ISSUE TITLE
Migration to Kratos v0.10.1

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#561]
## Description
As an admin I want to be able to leverage the latest functionality from Kratos

## Acceptance criteria

- [x] Migration of client + server to Kratos v0.10.1
- [x] Migration of k8s environments and docker-compose setups to Kratos v0.10.1
- [x] Update to helm chart from Kratos 0.10.1
