### ISSUE TITLE
Updates Usage

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#568]
## Description
As Organization I want to be able to share interviews, use cases, podcasts etc. with my community. Question is whether to use Updates for this.

## Acceptance criteria and must have scope
- [ ] Discuss future usage of Updates (also for interviews/use cases, etc.)
- [ ] Name change to News?
- [ ] Discuss position (above statistics on hub page to give more prominent place)
- [ ] Make initial UX design
- [ ]...

## Stakeholders
Requested by UWV
