### ISSUE TITLE
Bucket: Exporting the information from Alkemio in other formats (report style)

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#575]
## Description
As the platform will be used more and more, there will also be projects or Spaces that will be closed or require mid-term reporting. Exporting a summary of the work would support these users.

## Goal
Ability to export a summary of your work on the platform

## Hypothesis
Especially for projects that are for example part of a subsidy or European program/grant, reporting is an important topic

## Must have scope

- [ ] Summary of a Subspace
- [ ] Option to choose what to include / not to include
- [ ] PDF format export

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
