### ISSUE TITLE
UX: Management of UX designs

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#585]
## Description
As team members I want a clear House-style for UI/UX now that the team is expanding
As team members I want to easily find components to make mock-ups for the development team

## Acceptance criteria
- [ ] Choice of whether to go with AdobeXD vs Figma
- [ ] HackMD with up-to-date Housestyle, including colour codes, fonts, etc.
- [ ] Adobe XD document that is up-to-date with the components currently used
- [ ] An Alkemio Adobe XD account
- [ ] Migration of content and work processes to Figma
