### ISSUE TITLE
QA: Review of functionality since release 2022-04-21

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#592]
## Description
As a QA I want to be sure I have reviewed all closed work packs, but without delaying the sprint reporting.

## Acceptance criteria

- [ ] Issues completed during previous sprint that were not fully QA reviewed are validated

**Comment by Comoque1** [comment]
- [x] BUG: Memory leak warning is thrown, when GA sends an update #1797 - not reproducible anymore
- [x] improved logging + error handling around subscriptions #1889 - works fine locally
- [x] Remove creation of user preference definitions in the bootstrap service #1884 - no preferences were created after service restart
