### ISSUE TITLE
Location usage

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#596]
## Description
As a hub admin I want to have locations for challenges and opportunities
As an Organization admin I want to have location for my organization
As a user I want to see where entities are located

## Acceptance criteria

- [ ] Location entity added to the domain model
- [ ] Profile entity to have a Location field
- [ ] Context entity to have a location field
- [ ] User.city + User.country migration to the Location entity under Profile
- [ ] Client UX updated to allow users to enter location on the following entities: Organization, Challenge, Opportunity
- [ ] Client UX updated to show the location information on the following entities: Organization, Challenge, Opportunity
- [ ] Populator updated to allow specifying the location information on Organization, Challenge, Opportunity

## Additional Context
The usage of Location is valuable for displaying the entities on a map display.
The information is needed for the data being used by VNG around digital twins

Note that the Location entity at the moment is still fairly simple: only city, country are there. However having Location as an entity that is used across all entities that deal with Location data means that we can upgrade this easily enough as we need to.
