### ISSUE TITLE
Community: Org members, User leads (api only)

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#597]
## Description
As an admin I want to show the Organizations that are members of an Opportunity even if they are not leading it
As a user I would like to have Users that are visible as Leads for a Community so I know who to contact

## Acceptance criteria

- [ ] Organizations can also be members of a Community
- [ ] Users can also be leads of a Community
- [ ] Populator updated to allow setting of Org members on a Community for Challenges and Opportunities

## Additional Context
The full support for the display of users as leads is split out into #646
