### ISSUE TITLE
Visuals on Journeys: Enhanced selection + suggested images

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#601]
## Description

As a user I want to be easily able to update the images for the banners on my entities
As a platform I want to have visual images associated with content
As a compliance officer I want to ensure that the images being offered are under a valid license

## Initiative / goal
User Engagement. 

### Hypothesis
Visuals make the platform more enticing to users. By making it easier to select and find enticing images for hubs / challenges / opportunities the overall quality of the Alkemio platform will be higher.

## Acceptance criteria and must have scope
- [ ] Edit image moved to banner instead of in settings
- [ ] Editing of visuals to be done via a dialog
- [ ] Make it easy for users to search on CC image repositories
- [ ] Choosing images from image space library/previously used images

## Stakeholders
tbd

## Timeline
tbd

## Additional Context
Figma file: https://www.figma.com/file/4yKwyi3yt8N4ov8bX6iwFZ/Visuals-Management?node-id=0%3A1

**Comment by hoyterutteman** [comment]
Duplicate
