### ISSUE TITLE
Trigger users to contribute

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#603]
## Description
As a hub admin I want that the users in my community are active and contribute

## Acceptance criteria
- [ ] Personas identified and framed
- [ ] Design criteria identified, prioritized and captured on a Moscow board
- [ ] 3 designs made in co-create session with the Product team
- [ ] First prototype 
- [ ] Feedback gathered from dev + ops
- [ ] Refined prototype
- [ ] Second round of feedback from external stakeholder

## Additional Context
https://hub.alkem.io/open-innovation/challenges/user centric/opportunities/contribute/dashboard
