### ISSUE TITLE
Map based displays using locations

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#617]
## Description
As a user I would like to see the locations of Challenges / contributors on a map

## Acceptance criteria

- [ ] Selection of a map display service
- [ ] Integration and management of the map display service as part of server deployment
- [ ] Dashboard tab on Hub to display the locations of all Challenges / Opportunities / contributors in a control, with the same control also available on Community tab.
