### ISSUE TITLE
User engagement: simplified tabs, menu

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#637]
## Description
Simplify the main structure the core of the platform i.e. Hub, Challenge, Opportunity
Engage the community via Call-outs

As Alkemio I want my Users to understand how to use the platform correctly

## Initiative / goal
User engagement

### Hypothesis
The current set of tabs is too complex, it needs to be much simpler.
We need a structural manner for engaging the communities via call-outs

## Acceptance criteria and must have scope
- [ ] Phase 1 design
- [ ] Domain model extended with notion of collaboration and different types of call-outs
- [ ] Tabs simplified down to 4 as per design
- [ ] Existing data migrated to the two default callouts (one for aspects, one for canvases)
- [ ] Canvas UI updated to work with new approach to templates and with a view to call outs
- [ ] New menu structure at the top
- [ ] Client to switch to using the new domain model for interacting with canvases + aspects

To do: refine results of data analysis - https://hackmd.io/dl4ri8UvRcC6bmnySvNrMw

Out of scope
-  admin UI updates
- creation + launching of additional call-outs. They are a fixed set for now.

## Stakeholders
Partners

## Timeline
End July for this scope of work. 

## Additional Context
Material Guidelines: https://material.io/components/tabs

Figma entire file (not in presentation mode): https://www.figma.com/file/HxG0l93psLUxZUDt8IIini/Redesign-V1?node-id=0%3A1
 
FIGMA LINK: https://www.figma.com/proto/4RIiubc5QepoQAQgjM7Rsp/General-Structure?node-id=226%3A2195&scaling=contain&page-id=0%3A1&starting-point-node-id=226%3A2261

https://www.figma.com/proto/HxG0l93psLUxZUDt8IIini/Redesign-V1?node-id=0%3A1&scaling=min-zoom&starting-point-node-id=1%3A493&show-proto-sidebar=1

https://hub.alkem.io/challengecentric/challenges/structure/dashboard

![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/f478624d-07a7-48ed-9537-3794d6b01f57)
