### ISSUE TITLE
Community: Users leads + Org roles

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#646]
## Description
As a user I want to know who is the lead in a community / organization

## Acceptance criteria

- [ ] Display of users as leads on a hub / challenge / opportunity
- [ ] Roles of an organization visible on Org profile
- [ ] Selection of users / organizations on admin

## Additional Context
The server supports the notion of a user in a lead role, but there is design needed for how to use this to help interactions on the client

https://www.figma.com/file/q32jnaQxiTZhrH67iB8716/Managing-memberships-for-users?node-id=0%3A1

Out of scope: 
- [ ] Logic extensions if needed for how people interact with the leads
