### ISSUE TITLE
Upgrade to Kratos 0.10.0

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#647]
## Description
As a user I want extended sessions
As a platform steward I want to have the beta version

## Acceptance criteria

- [ ] Usage of Kratos version to be 0.10.0 or later
- [ ] Helm charts updated
- [ ] User sessions extended past token lifetime
- [ ] Courier / Oathkeeper upgrades?

**Comment by techsmyth** [comment]
Merged with the epic around improved user login / session mgmt
