### ISSUE TITLE
Allow users to join Orgs based on email matching domain

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#682]
## Description
Brief summary of what this Epic is, whether it's a larger project, goal, or user story. Describe the job to be done, which persona this Epic is mainly for, or if more multiple, break it down by user and job story.

## Initiative / goal
Describe how this Epic impacts an initiative the business is working on.

### Hypothesis
What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit.

## Acceptance criteria and must have scope
- [ ] Users whose email matches the domain of an org can "Join" the organization
- [ ] Join button is shown where relevant to users on the Org profile page
- [ ] New Privilege for authorization model "ORGANIZATION_JOIN" that controls whether the button is enabled
- [ ] New type of credential rule tbd?
- [ ] Organization preference to allow users to join to be enabled / disabled (default false)
- [ ] Org admins to receive a notification if a user joins their org
- [ ] Users to receive a notification to confirm that they have joined an org

## Stakeholders
Org admins

## Timeline
tbd
