### ISSUE TITLE
Engagement: Smart + custom sorting 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#684]
## Description
The set of Hubs shown on the home page, or elsewhere on Alkemio, can be sorted in multiple ways. Further, the way it is sorted can also take into account information that is known about the currently logged in user.

## Initiative / goal
This is about driving up user engagement on the platform

### Hypothesis
By showing users the Hubs (or Challenges) that are relevant to them first that they are more likely to engage + explore more

## Acceptance criteria and must have scope
- [ ] Display of the hubs on the home page to exclude hubs that are already shown in the "my hubs" section
- [ ] Sorting of hubs to take into account the following information about the user: the organizations the user is associated with and if any of them are hosts of a hub, the domain of the host org of hubs + how that relates to the user email address etc
- [ ] The list of hubs should also be retrievable by **excluding** the set of hubs that the user is already a member of

Note: most of the above also applies equally to how Challenges are shown within a hub.

## Stakeholders
Partner community managers

## Timeline
tbd
