### ISSUE TITLE
Conversion between Challenge related entity types

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#692]
## Description
All conversion of one type of entity e.g. challenge into another. 

## Initiative / goal
Allow the usage of the platform in production to be adjusted without losing data

### Hypothesis
By allowing users to promote challenges to Hubs, and to promote opportunities to challenges

## Acceptance criteria and must have scope
- [ ] Mutation to allow a Challenge to be promoted to a Hub
- [ ] Mutation to allow an Opportunity to be promoted to a Challenge
- [ ] Both mutations offered by a new platform level service and not done via the domain model mutations. 
- [ ] Promotion only available to global admins

## Stakeholders
Gerlof (VNG)
UWV

## Timeline
Asap, the longer we leave it the more disruptive the change.
