### ISSUE TITLE
Whiteboard: interactive multi-user editing demonstrator

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#696]
## Description
Allowing whiteboard to be worked on by multiple users at the same time

## Initiative / goal
User engagement 
Using the platform ourselves

### Hypothesis
By making the whiteboard multi user and real time editing that we will make it easier for users to collaborate using the platform
Also it seems that this is a key requirement for our own usage, which is a sign that it is also a requirement for whiteboard to be really useful for our users

## Acceptance criteria and must have scope
- [ ] Canvas to have multiple edit modes, one of which is allowing any user with appropriate access rights to be able to edit it at the same time as other users
- [ ] Ability for multiple users to be editing a canvas at the same time together
- [ ] Design for how and when we store snapshots into the domain model

## Stakeholders
All platform users

## Timeline
tbd

## Findings
Excallidraw real time events: https://hackmd.io/@alkemio/r1iRZnuw3
[Real-time collaboration setup with Hocuspocus in HackMD](https://hackmd.io/KigrFHfLQS-CVdzerfULfw)

## Options
https://tiptap.dev/hocuspocus/introduction

https://app.excalidraw.com/s/4BCnkZqaP0t/9CZtSewbUoU
