### ISSUE TITLE
Exploring Challenges + Contributors refresh

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#697]
## Description
The initial orientation of new users on the platform should help with them engaging. At the moment the Contributors and Challenges pages do not provide a lot of content to entice them to engage.

## Initiative / goal
User engagement

### Hypothesis
By giving better and more relevant content on the Challenges and Contributors tabs that users are more likely to engage. 

## Acceptance criteria and must have scope
- [ ] Challenges page to trigger a search on the term "Innovation" when it loads
- [ ] Contributors page to have page for logged in users
- [ ] Contributors page for not logged in users

## Stakeholders
New potential users

## Timeline
tbd

## Design
Figma: https://www.figma.com/file/CXQhK3EatE6jhX7O4srhNT/Challenges---Contributors-main-pages?node-id=0%3A1
Printscreens:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/d712f3cb-999b-4dc9-ac46-224dd9ce5e9e)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/e4512087-7e04-4c64-859e-32911cb96563)
