### ISSUE TITLE
Canvas Templates

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#703]
## Description
Allow the management of Canvas Templates by a Hub Admin

## Initiative / goal
Sharing of best practices and knowledge

### Hypothesis
By making it easier to manage Canvas Templates, and bring them into the same management framework as Aspect Templates, that more such templates will be used

## Acceptance criteria
- [ ] Ability to manage Canvas Templates at Hub level, using the CanvasTemplate entity already on TemplatesSet
- [ ] Canvas business logic updated to load only Canvas Templates at the Hub level, regardless of whether at hub, challenge or opportunity
 - [ ] Users able to create new CanvasTemplate instances on a Hub

## Additional Information

Hub template management:
https://xd.adobe.com/view/39240558-394d-42a4-a227-229d1105578e-6c77/

## Stakeholders
Digicampus

## Timeline
Spring 41
