### ISSUE TITLE
Innovation Flow templates

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#704]
## Description
Allow the management of Innovation Flow Templates for usage by a Challenge / Opportunity by a Hub Admin

## Initiative / goal
Sharing of best practices and knowledge

### Hypothesis
By making it easier to manage Innovation Flow Templates, and bring them into the same framework for Templates, that more such templates will be used

## Acceptance criteria
- [ ] Domain model extended with a new entity: InnovationFlowTemplate, which has the following template type specific fields: 
- LifecycleDefinition
- Usage: string[ ] with the set of options being limited to Challenge, Opportunity for now
- [ ] Ability to manage InnovationFlowTemplates at Hub level
- [ ] Challenge + Opportunity business logic to require specifying the Innovation Flow Template as part of the create mutation
- [ ] Hub creation to ensure there is one default lifecycle template that applies to both Challenges + Opportunities
- [ ] Challenge and Opportunity to have a separate mutation to update the Lifecycle 

- [ ] Validation of Lifecycle definitions as part of DTO validation

## Additional Information
UX design tbd

## Stakeholders
VNG
The Hague
Novum

## Timeline
Spring 41

**Comment by oldhoyte** [comment]
"Innovation Flow"
