### ISSUE TITLE
Discussion callout

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#717]
## Description
An additional call out type for hosting discussions

### Hypothesis
By allowing members of a community to interact with each other, the engagement on the topic will increase

## Acceptance criteria and must have scope
- [ ] Collaboration entity updated to allow selection of additional option: Discussion
- [ ] Add Comments entity to the Discussion Callout
- [ ] New component on the client to display the contents of the Discussion entity
- [ ] Subscription for comment added to discussion is wired up

## Stakeholders
Partners
UWV

## Timeline
Q3 2022

## Design
Figma: https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=0%3A1
