### ISSUE TITLE
Search: Hub + with Contributions results

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#718]
## Description
As a User I want to see content that matches my search terms (global + Hub level), including results for Cards (aspects) and Canvases

## Acceptance criteria
- [ ] Expand search results to return Cards, Canvases
- [ ] Client search results page expanded to have an additional section for content results, where cards + canvases would be displayed
- [ ] Each search result type to return 10 entries, and this to be displayed on text on screen

Contributions section:
- [ ] Expand search results to return Cards
- [ ] Search results to have an additional section for content results, where cards would be displayed

Search results limits:
- [ ] Each search result type to return 10 entries, and this to be displayed on text on screen

## Additional Context

Current design:  https://www.figma.com/file/rkPg9ud5OCPYAfEpVLaPRX/UX-Search-cards-behaviour-%2B-results?node-id=36%3A69
