### ISSUE TITLE
Arch: Management of message types and payloads between microservices

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#719]
## Description
As a developer I want to have a maintainable way of managing the interactions between the microservices in usage in the platform

## Acceptance criteria

- [ ] Creation of a new package: notifications-client as part of the notifications repo that has DTO definitions for all the incoming and outgoing payloads, as well as enum for message types supported
- [ ] Usage of the notifications-client package within the server repo to check the type on all messages being sent and their responses. Removal of duplicate DTO definitions.
- [ ] Creation of a NotificationsAdapter, as part of services, on teh server repo to manage all interactions with the Notifications service
- [ ] Creation of a new package: wallet-manager-client as part of the wallet-manager repo that has DTO definitions for all the incoming and outgoing payloads, as well as enum for message types supported
- [ ] Usage of the wallet-manager-client package within the server repo to check the type on all messages being sent and their responses. Removal of duplicate DTO definitions.

## Additional Context
At the moment the microservices are being injected in many places in the server, and types are also in a lot of places.
