### ISSUE TITLE
Roadmap / backlog management

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#723]
## Description
Creating a shared view across developers, Product / UX and partners about the roadmap for Alkemio

### Hypothesis
By having a shared view of the roadmap it is much easier to understand what is being worked on and what the context is for each work pack

## Acceptance criteria and must have scope
- [ ] Zenhub usage refined with additional columns
- [ ] Inititial set of Initiatives defined and Epics assigned to them
- [ ] Initial set of Theme labels defined and start on assignment

- [ ] Miro board for the Alkemio roadmap shared and "linked"
- [ ] Team ways of working updated

tbd - decide on whether to host all epics on either Alkemio repo or infra-ops?
tbd - review added set of initiatives as well as labels
tbd - assign leads from both product and development to all epics 
tbd - agree on when we can show timelines e.g. current / next quarter?
tbd - decide on limits for each of the Epic columns e.g. 7 per column?!

## Stakeholders
Product team
Development team
Partners

## Timeline
Q3 2022

## Potential tools
- Rally
- Jira Agile
- Digital.ai
- Spiral plan

Above names found via article on agilemania.com - and by searching on "safe agile"
