### ISSUE TITLE
Library: Innovation Pack management

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Coordination#739]
## Description
This epic brings full user access to the Library contents, as well as the ability for Organizations to manage their own Innovation Packs. 

Note: it is also interesting to be able to use the store for knowledge sharing outside of Alkemio usage. Any content added is by definition, for now, public.

Note also that templates are not "owned" but more a question of who can manage them.

## Initiative / goal
Knowledge institutions are able to share best practice templates for usage on Alkemio.
Drives non-Alkemio users to the platform to find best practices / knowledge related to multi stakeholder collaboration

### Hypothesis
Hub admins are able to find and import best practices (created centrally + available to all + use).

## Acceptance criteria and must have scope

1. A Library page
- [x] all users, logged in or not, are able to browse all the published templates, either aggregated by type of displayed as Innovation Packs. Via the Innovation Packs each Templates is associated with an organization
2. Hub/Setting/Templates
- [x] Hub admins are able to import templates associated with the template type (admin is presented with a filtered view of the templates of the particular type)

- [x] tbd - what does admin look like? If take a more Innovation Pack view then can have settings directly on that + let those with access directly update the Templates in an Innovation Pack there. 
- [x] allowing users to browse the templates directly for Canvases?

Note: partially split out into a separate epic

## Stakeholders
- Alkemio Stewards
- UWV
- Development Team
- Product team

## Timeline
- UI Designs 
- Development capacity
- Approval from CTO

## Miro board
https://miro.com/app/board/uXjVOkjWSVI=

Platform template management:
https://xd.adobe.com/view/d4b6bc7f-ea02-4473-9c52-8ce59e60651c-81e5/

July 2022 Figma file: https://www.figma.com/file/PwLYdTm1PNEZvPMpZt94up/Platform-Template-Library?node-id=0%3A1

Potential design:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/d62176a7-1371-4904-b1e9-dba08e368268)

**Comment by techsmyth** [comment]
Great capture! 
 
 What is best way to share feedback? 
 
For example I think there has to be a separate concept, which I called Provider, to group templates with meta info. Initially associated with a single org, but that later be more flexible. Also a single org can have many sets of best practices, potentially under different terms / packaged differently.

**Comment by techsmyth** [comment]
Also some of above I would split into a follow up epic: ability to suggest/accept suggestions, and notifications. Key is what is minimum set of value that is valuable in itself?

**Comment by techsmyth** [comment]
Like the idea of hub pref re allowing open canvases, applies across all types potentially so may need to be generic. In general there may need to be a common “usage policy” for templates?

**Comment by hero101** [comment]
@techsmyth The epic is work in progress. We are happy to discuss all the features mentioned here and then break down the mvp.

**Comment by oldhoyte** [comment]
If I understand correctly your first reply, this is what you mean:

Multiple Orgs can form a Provider. Each Provider can have many templates. These templates from this Provider can then be packaged?

Our question is then: why would you want multiple orgs to be one provider. If you look at an app store (apple/google), each app is provided by 1 org

**Comment by techsmyth** [comment]
Clear it is wip, hence my question re how to iterate it. Suggest we just use these comments

**Comment by techsmyth** [comment]
@hoyterutteman there needs to be indirection for flexibility. The org cannot be the linking entity which is what I interpreted. In the not too far future we can have hubs without a host org or multiple etc. ditto re bundles of best practices (provider or another term)

**Comment by techsmyth** [comment]
I think Provider is wrong term.It is bundling a set of content that is "provided" by an Org. Am ok to have one org in that role for now, same as with hub. But would prefer not to depend on it.

**Comment by techsmyth** [comment]
[https://app.zenhub.com/files/266739765/02fa4bd5-da7e-4853-a2d8-93c4b3f624d3/download](https://app.zenhub.com/files/266739765/02fa4bd5-da7e-4853-a2d8-93c4b3f624d3/download)

**Comment by techsmyth** [comment]
@SimoneZaza @larssondenise this one is actually nearly done. We had it tagged for Q3 but we may want to push through and close this area out. Key gap still is how new innovation packs get added.
