### ISSUE TITLE
Innovation Hubs: Specified Hubs, Hub visibility

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#743]
## Description
Allow clustering of communities with visual distinction, showing the listed communities based on e.g. tags

Allowing displaying of hubs with a given visibility via a custom sub-domain: https://demo.alkem.io 

## Innitiative
Innovation Spaces

## Additional information
https://miro.com/app/board/uXjVOivg9es=/

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/04c32849-2944-4b52-b291-299704f0131c)
Domain model brainstorm results:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/fca23420-05df-4277-8584-54a75a301e2c)

## Initiative / goal
Providing a visually separate view onto the data on Alkemio

### Hypothesis
Innovation Spaces will reinforce user commitment and the feeling of ownership of the hubs on the platform.

https://demo.alkem.io can be the first step to focused front end but in a simplified format, where the need for a custom UI / branding / white labeling is not present. This way we'll also increase the visibility of our environment, increase the number of users + organizations on the platform and make a more compelling marketing use case.

## Acceptance criteria
- [ ] Specify per Innovation Space the set of Communities to be visible
- [ ] Branding control: logo, header, welcome text
- [ ] Currently configuration is static, on-demand 
- [ ] demo.alkem.io to show Hubs with visibility of DEMO as default type (so instead of ACTIVE)
- [ ] archived.alkem.io to show Hubs with visibility of ARCHIVE as default type (so instead of ACTIVE)
- [ ] existing Demo environment to be availble at demo-old.alkem.io
- [ ] Configuration for what content is displayed on a given InnovationSpace (for now only criteria is URL, but could be more later)

For later: 
- [ ] Search results / challenges / contributors pages prioritize Innovation Space content
- [ ] Custom landing page for logged-in / anonymous access

## Stakeholders
VNG, UWV

## Timeline
Q1

## Additional Context

https://www.figma.com/file/OZdB6Cj80EELlIoYotS9qj/Company-persona-mock-up?node-id=0%3A1

Link to mocked-up pages: https://www.figma.com/file/wZkvw4E1KhRq9Ga6L6HmSL/FFE?node-id=105%3A757
