### ISSUE TITLE
Infrastructure: Maintainability 2026 Q2

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#744]
## Description
CAPEX investment in infrastructure maintainability in order to reduce its high OPEX.

## Initiative / goal
Provide faster, easier to deploy and maintain infrastructure.

Scope: provisioning and orchestration.

### Hypothesis
Reducing copy / paste in the infrastructure, templating it, and organizing it (both orchestration and provisioning) will decrease the time and therefore the cost needed to maintain it + will reduce the risk of manual, human errors.

## Acceptance criteria
- [ ] Script deployment prerequisites instead of documenting them
- [ ] Use alkemio domain in configuration where possible (it's base for like 9 configuration parameters)
- [ ] Automate TLS certificate extension

## Stakeholders
Stichting Alkemio

## Timeline
Spring 43, 44

**Comment by techsmyth** [comment]
@valentinyanakiev moved this to be in progress as that is what it is...also made the scope to be k8s / provisioning so took the npm publishing out of it.
