### ISSUE TITLE
Custom URL for Demo Hubs on production

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#745]
## Description
https://demo.alkem.io hubs to be hosted on the production environment 

## Innitiative
Innovation Spaces

### Hypothesis
https://demo.alkem.io can be the first step to focused front end but in a simplified format, where the need for a custom UI / branding / white labeling is not present. This way we'll also increase the visibility of our environment, increase the number of users + organizations on the platform and make a more compelling marketing use case.

## Acceptance criteria
- [ ] demo.alkem.io to show Hubs with visibility of DEMO as default type (so instead of ACTIVE)
- [ ] archived.alkem.io to show Hubs with visibility of ARCHIVE as default type (so instead of ACTIVE)
- [ ] existing Demo environment to be availble at demo-old.alkem.io
- [ ] Configuration for what content is displayed on a given InnovationSpace (for now only criteria is URL, but could be more later)

Note: data migration + closing down the old environment to be a separate epic

## Additional Information
https://miro.com/app/board/uXjVOivg9es=/

## Stakeholders
Stichting Alkemio

## Timeline
tbd

## Additional information
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/04c32849-2944-4b52-b291-299704f0131c)
Domain model brainstorm results:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/fca23420-05df-4277-8584-54a75a301e2c)
