### ISSUE TITLE
Client: Codebase Structure

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#755]
## Description
Ensuring that the client development setup is clean and easier to work with.

## Initiative / goal
Development team effectiveness. Ability to engage additional / external developers.

### Hypothesis
By making the development setup cleaner it is easier for a developer to be effective and to on-board additional developers.

## Acceptance criteria and must have scope
- [ ] Single approach in the folder structure for source code
- [ ] Remove the following top level folders + move contents elsewhere: components, routing, pages, views, styles, themes, models
- [ ] Naming convention agreed + enforced by Lint rule
- [ ] Remove having double type names in the code base. Wrappers for MUI components should be e.g. ButtonWrapper.

## Stakeholders
Development team

## Timeline
Q3
