### ISSUE TITLE
Contributor visibility

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#757]
## Description
As a user or organization you want a distinction on your profile between the pages you are a lead and a member of.
Also, there is an inconsistent use of user and organization (hover) cards across the various platform pages.

## Initiative / goal
Improve information display by applying a consistent approach of contributor cards as well as highlighting their contributions

### Hypothesis
By making roles of contributors more clearly visible there is more value from the network that is on Alkemio

## Acceptance criteria and must have scope
- [ ] User + organization profiles to show the different roles for each community
- [ ] Visibility of demo hubs
- [ ] Organization profiles show the organization admin
- [ ] Organization profile page to show the Innovation Packs they are providing
- [ ] Organization profile page to show the custom landing pages they are hosting
- [ ] Organization and individual profile cards updated / consistent with cards on the platform

## Timeline
tbd

**Comment by techsmyth** [comment]
@valentinyanakiev @SimoneZaza please do talk this one through - it is a big gap. We moved it back to being elaborated as I recall that Valentin had some questions / views that needed to be talked through.
