### ISSUE TITLE
Callout Engagement: ++

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#768]
## Description
As a Hub or Challenge Lead I want to guide users to the Callouts
As a User I want to see where the activity is happening within the Hub Challenge or Opportunity

## Initiative / goal
Further Community engagement related to the Callouts

### Hypothesis
By improving the callouts experience users will be enticed to contribute more to Callouts

## Acceptance criteria
- [ ] Subscriptions connected for new cards, new canvases + new comments
- [ ] Subscriptions for new members
- [ ] Search on explore tab that does client side filtering on content)
- [ ] Option to notify members about new Callout 
- [ ] Option to allow/not-allow members to submit cards/canvases

## Stakeholders
UWV
VNG
Digicampus

## Timeline
Q3 2022

## Additional Context
Figma link: https://www.figma.com/file/MIjrxdRWOjxJwzfwpc4hlm/Dashboard-page-refresh?node-id=0%3A1
![Schermafbeelding 2022-09-19 om 14.32.13.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/09317d87-4368-4b8e-8bca-bd225aba68ad)

Search in Callouts
https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=387%3A5374
Page: Search within Explore tab

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/10a2b8f3-2736-41bb-89d7-6396a77e8290)

This is the data that we currently can retrieve and the set of activity that can be logged:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/4e0ea443-58f6-4892-9f98-da639d475881)

Easy enough to extend.

**Comment by techsmyth** [comment]
@SimoneZaza @larssondenise after a brainstorm with Valentin, there is now an initial implementation of an Activity Log around Collaboration entity. This means that we have a good source of data to work with for the activity panel on the Dashboard Tab. 

We can also use this as a "poor mans audit log" for on the admin panel so that users can see what has happened...so we should also mockup how that would be displayed.

**Comment by techsmyth** [comment]
@ccanos if you get a few minutes to scan this before the standup on Monday that would be great. There is already a PR on the server - and I want to brainstorm with you re what is needed to implement this.
