### ISSUE TITLE
Challenges Page refresh

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#769]
## Description
The Challenges page is a key landing page for a Challenge centric platform. It currently only shows a set of Challenges after searching and grouped by Hub. 

## Initiative / goal
Enabling a much more flexible interaction for users with Challenges hosted on the platform

### Hypothesis
By making Challenges more accessible and findable that users will engage more on Challenges

## Acceptance criteria and must have scope
- [ ] Ability to show all the Challenges that a user has read access to on the platform 
- [ ] The loading of the Challenges should be paginated so that the page can deal with a large number of challenges and still remain performance
- [ ] Challenges shown on the page should be searchable across multiple fields in the Challenge (exact fields tbd)
- [ ] Client challenges page updated to allow interaction with the Challenges

## Stakeholders
Users on the platform that want to find Challenges relevant to them

## Timeline
tbd

## Design

Note: to be updated to focus on Challenges page.

Figma: https://www.figma.com/file/CXQhK3EatE6jhX7O4srhNT/Challenges---Contributors-main-pages?node-id=0%3A1
Printscreens:
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/d712f3cb-999b-4dc9-ac46-224dd9ce5e9e)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/e4512087-7e04-4c64-859e-32911cb96563)
