### ISSUE TITLE
Creation + management of Challenges / Opportunities

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#771]
## Description
A Hub, Challenge and Opportunity are very different things. However we are treating them the same in the Context fields
Also, the 'heavy markdown fields' when you are creating and managing Hubs / Challenges / Opportunities, are scary

## Initiative / goal
User engagement

### Hypothesis
By making the application cleaner and easier, engagement will increase
By guiding users through the right set of questions, they will frame better Hubs/ Challenges/ Opportunities. 

## Acceptance criteria and must have scope
- [ ] Challenge / Opportunity create form refreshed
- [ ] Create button on the Challenges / Opportunities page
- [ ] Different set of "Context fields" for Hub / Challenge / Opportunity
- [ ] New Innovation Flow tab on admin, for both changing the current Innovation Flow state + switching to another one

## Design
https://www.figma.com/file/nyMxnaOQbhGwtIzvJjsQmU/Create-challenge%2Fopportunity-in-context?node-id=0%3A1

## Stakeholders
General community
Webbers

## Timeline
Q3
