### ISSUE TITLE
Hub Archiving + Visibility

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#773]
## Description
Allowing Hubs to exist in multiple states, such as draft (not visible in general), published, archived etc. 

## Initiative / goal
Allowing us to remove the visibility of Hubs that are not active without deleting the content

### Hypothesis
The set of content that is visible on Alkemio should be active, thereby increasing engagement

## Acceptance criteria and must have scope
- [ ] Able to archive a Hub so that it is not longer visible
- [ ] Hubs that are archived are no longer manageable by Hub admins from that Hub
- [ ] Hubs that are archived should not be browsable beyond that of private hubs i.e. context / home page is visible
- [ ] Hubs that are archived (or demo) should have a visual display of this status on the Hub homepage
- [ ] It should still be possible to get a list of Hubs of any visibility, but default the hubs() query should only return active hubs
- [ ] Content of archived hubs should not show up in search results i.e. challenges / opportunities should not be visible
- [ ] Platform statistics to be updated to only show active hubs
- [ ] Admin management of Hubs to show which hubs are archived / demo in the list (label?)
 - [ ] Admin of a Hub content to show the visibility (read only)

Note: for now to update the hub visibility requires a graphql mutation

## Stakeholders
New community partners
Platform admins so that they can archive content

## Timeline
q3 2022

## Additional context
https://www.figma.com/file/vnvlhzYYt097B3mxjoQEYw/Archived-hubs?node-id=0%3A1
