### ISSUE TITLE
Callout templates

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#789]
## Description
Providing a set of immediately usable Callout templates that community managers can leverage to engage their community

## Initiative / goal
User engagement

### Hypothesis
By providing examples of how callouts can be used to engage the community more effective callouts will happen and users will engage more

## Acceptance criteria and must have scope
- [ ] Add notion of callout template that is available at the Hub level (similar to canvas templates)
- [ ] Platform level set of callout templates that are available by default in all hubs
- [ ] Creation of a first set of callout templates

## Stakeholders
UWV
Community Manager Role

## Timeline
tbd
