### ISSUE TITLE
Newsfeed from Twitter

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#794]
## Description
Allowing Hub / Challenge admins to display a feed of activity from Twitter

## Initiative / goal
User engagement

### Hypothesis
By making the content on a Hub / Challenge more engaging that users are more likely to engage

## Acceptance criteria and must have scope
- [ ] Select and embed a Twitter newsfeed component
- [ ] Allow Hub / Challenge admins to enable the newsfeed
- [ ] Allow Hub / Challenge admins to control the set of hashtags that will be used to show tweets from

## Stakeholders
Webbers

## Timeline
tbd
