### ISSUE TITLE
Poll

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#798]
## Description
As a facilitator, I would like to gather the opinions / views of the community
As a facilitator, I want to be able to schedule a date for our next session by asking everyone's availability

## Initiative / goal
Add the option for voting to the additional context

### Hypothesis
By giving lightweight ways to engage the community there is more user engagement
By adding the option for voting, we keep facilitators on the platform and pull the community towards the platform as opposed to using email / datumprikker

##  Acceptance Criteria P1
- [ ] As a facilitator, I want to create polls to gather community input - whether opinions on decisions, preferences, or availability for meeting dates - so that I can understand the group's perspective and coordinate effectively.
- [ ] As a creator, I want my contributors to be able to vote multiple times
- [ ] As a creator, I want to receive notifications from new votes
- [ ] As a creator / contributor, I want to see who voted what
- [ ] As a contributor, I want to be able to change my answer
- [ ] As a creator, I want to be able to change the options in the poll
- [ ] As a creator, I want to see the options ranked based on most votes

##  To pick up later if users ask for it
- [ ] As a facilitator, I want to allow anonymous voting, as a contributor I want to vote anonymously
- [ ] As a facilitator, I want to be able to close a poll 
- [ ] Settings option, not to see votes until voted
- [ ] Add voting as an option in additional context
- [ ] Ensure notifications are send to post creators when new votes are in
- [ ] Notifications for users who've already voted?
- [ ] As a creator, I want to be able to close the poll and notify the contributors
- [ ] As a facilitator, I want to choose whether contributors can vote one or multiple times. 
- [ ] As a contributor, I want to receive notifications from new votes after I've voted
- [ ] As a product owner, I want all settings (multiple/anonymous/etc.) nicely captured in one dialog

## Stakeholders
Facilitators

## Design 

Design: https://www.figma.com/design/lo6l3ct5nZDx7uEkMIGIwi/Posts--Forms?node-id=80-14

**Comment by hoyterutteman** [comment]
[duplicate](https://github.com/orgs/alkem-io/projects/4/views/5?filterQuery=-label%3AInitiative+label%3AEpic+-status%3ADone&pane=issue&itemId=33886647&issue=alkem-io%7Calkemio%7C1063)
