### ISSUE TITLE
Callouts: Inspiration for usage

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#804]
## Description
Providing a set of examples for how to effectively use Callouts

## Initiative / goal
User engagement

### Hypothesis
By helping admins understand how to effectively use callouts that they will be better able to engage their community

## Acceptance criteria and must have scope
- [ ] Help text page that details out many examples of callouts to inspire admins
- [ ] Inspire icon (new concept?!) beside the Create Callout button that links to the help page
- [ ] Section on Challenge Centric Hub with additional examples of sample callouts

## Stakeholders
Hub / Challenge admins

## Timeline
asap

## Additional context
https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=9%3A1285

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/744cf3ed-8f56-41d3-8c6d-11dc59d48511)
