### ISSUE TITLE
Material: Cards refresh

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#805]
## Description
Cards are a key element of the Alkemio platform. They are in need of a refresh to show both more relevant information as well as to align with Material guidelines.

## Initiative / goal
User engagement

### Hypothesis
By making the information on the cards more relevant, and the display more consistent, they will drive user engagement. 

## Acceptance criteria and must have scope
- [ ] Users and Organizations
- [ ] Canvases and Cards
- [ ] Hubs, Challenges and Opportunities

## Stakeholders
Product 

## Design
https://www.figma.com/file/C0CXFtd4UgnJUf1G43UHc0/Material-Alignment?node-id=2%3A3
