### ISSUE TITLE
Callouts: usability refinements, activity entries

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#812]
## Description
Improving the usability and intuitiveness of Callouts

## Initiative / goal
User engagement

### Hypothesis
By making callouts easier to use we increase user engagement

## Acceptance criteria and must have scope
- [ ] Links in activity log clickable , and to navigate as far as possible using provided data
- [ ] Text for activity log entries updated
- [ ] Create Callout only allows to create as draft, with no summary step in the process

## Stakeholders
UWV

## Timeline
asap
