### ISSUE TITLE
Home Page + Contributors

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#813]
## Description
Show relevant contributors on the home page

## Initiative / goal
User engagement / credibility

### Hypothesis
By having more credible organisations + not direct contributor metrics no the home page the platform is more credible

## Acceptance criteria and must have scope
- [ ] Design for contributors section (or not) on the home page
- [ ] Showing **active / facilitating** organizations on the bottom section
- [ ] Edit wording by fintan
 
## Stakeholders
Alkemio team
Partners

## Timeline
asap

## Additional context
https://www.figma.com/file/Y4tU1CaZboYYW52xaImaLZ/Homepage-refresh-September?node-id=0%3A1

## Fintans feedback

-     Top section wording. Replace ‘A new way of working on challenges, together. Building a community of people, companies, NGOs and public bodies’ with ‘Empowering society. The platform to succeed in working on challenges, together’. This is to be in line with the manifesto (which is good for branding), and I think it is also important to have the words ‘platform’ and ‘society’ in this top section of the platform page

-     Rest of the top section wording, ‘Impact – Foundation – Open Source’. Change ‘Foundation’ to ‘Purpose Driven’, as ‘foundation’ could be seen as quite passive and not very ambitious, whereas ‘purpose driven’ has more energy/force. Change the overall order to ‘Purpose Driven – Open Source – Impact’, as then it flows and you are saying that being purpose driven and using open source is how you will have the most impact. We currently don’t have the word ‘innovation’ mentioned in this top section, whereas many of the hubs are focused on innovation, so if we are happy to have 4 concepts instead of 3 then we could say ‘Purpose Driven – Open Source – Innovation - Impact’, or if we want to keep it at 3 then ‘Purpose Driven – Open Source – Innovation’. My preference is to keep it at 3, and it depends what people feel about the choice of 'Impact' vs 'Innovation'

-     ‘New to Alkemio’ box; take out the word ‘manage’, as it could be interpreted as meaning Alkemio is like a project management software (note: this is an impression that some people have given to me when I explained Alkemio to them; this could have been due to my poor explanation (!) but in any case there are a lot of project management solutions out there, often with very low subscription fees, so we want to differentiate Alkemio from that market). Suggest changing to “Easy for you to engage in effective and meaningful ways. Find solutions to challenges.”

-     ‘Explore the Challenge Hubs’ box: For the sentence where it says that a hub can be public or private, put in a description of what it means to be public vs private, by having a short description that comes up when you hover over it. Otherwise people may be put off by a lot of hubs being labelled as private and think there is no way to join them, whereas I think you can still apply to join a private hub and it depends on the hub manager?

"Each Hub has members that are contributing. Become a member via the Hub page."

"Most Hubs are fully visible to everyone, some are private and content is only visible to members."

NL:
