### ISSUE TITLE
Callouts: Sorting control

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#815]
## Description
Allowing the storage and management of sort order for a set of entities within a given scope. For example being able to control the order of Callouts on a Collaboration. Or other ways of filtering/creating structure when there are lots of Callouts.

## Initiative / goal
User engagment

### Hypothesis
By providing control over the sort order of entities that the experience can be more logical and thus better for user engagement

## Acceptance criteria and must have scope
- [ ] Ability to control the sort order of callouts
- [ ] Able to manage the sort order of callouts via the client interface
- [ ] The updating of the sort order should be reliable and behave as expected by users i.e. no weird side effects
- [ ] The approach should be applicable to other entities that need to be ordered in a specific way

## Stakeholders
Energy transition Hub Giles when they start using lots of Callouts (actions, potentials, obstacles)

## Timeline
tbd

## Additional context
- Sorting Callouts: https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=9%3A1285  (Page: Version 3)
