### ISSUE TITLE
Callouts: Add single card type

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#824]
## Description
Allowing the creator of a callout to choose a single template to use for new cards added to the callout

Note: the card type could be changed, including visuals etc during the life of the Callout

## Initiative / goal
User engagement

### Hypothesis
By giving the users less choice when contributing to a callout that it is easier for them to add it

## Acceptance criteria and must have scope
- [ ] Ability for an admin to choose a single card template when creating the callout (one screen still!)
- [ ] When adding a card there is then no choice of type of card - that is just fixed
- [ ] Allow admins to move cards between callouts

## Stakeholders
WDC

## Additional context
https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=438%3A1487

**Comment by larssondenise** [comment]
@techsmyth following our chat yesterday, updated design! 
![Schermafbeelding 2022-11-01 om 10.00.13.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/38831e25-5e81-4dd6-b1d8-96ceb7926ec7)
