### ISSUE TITLE
Community: Wider participation (auth tidy up)

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#825]
## Description
Allowing wider participation from Hub members in Challenges and opportunities hosted within a Hub

e.g. that Hub members can have the rights normally assigned to members of Challenges

## Initiative / goal
Community engagement

### Hypothesis
By taking away barriers to contributing that more users will contribute

## Acceptance criteria and must have scope
- [ ] Challenges to have a flag, defaulting to true, that allows Hub Members to participate in the same way as Challenge members
- [ ] Challenges to have a flag, defaulting to true, that allows non-members visibility of the challenge contents (Private Hub)
- [ ] Opportunity to not have additional preferences but to have allow participation to Challenge / Hub members

TBD:
- Impact on interaction on the client? Anywhere we are not using privileges where we should be?

## Stakeholders
VNG (Gerlof)

## Timeline
tbd
