### ISSUE TITLE
User to user messaging

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#833]
## Description
It is currently not possible for a user to interact with another user or admin/host via the platform. However, there may be various cases where a user wants to send another user a personal message, wants to share an interesting callout with them via email or mention them in one of the comments.

## Initiative / goal
Allowing users to connect on the platform in three ways: personal message, sharing content via email + message, and mentioning in comments.

### Hypothesis
By allowing users to interact on the platform that users are more engaged and active. These notification trigger them to have a look at the platform. 

## Acceptance criteria and must have scope
- [ ] Allow users to send a message to community leads or any user within a community
- [ ] Allow users to forward particular content to another user on Alkemio (so choose Alkemio users + then send a personal message with a link)
- [ ] Allow users to tag someone in the comments of a Card or Discussion Callout
- [ ] New set of preferences for the user + admin
- [ ] Provide controls to avoid opening up spamming possibilities (e.g. user can send only 5 per xx minutes?)

TBD: GDPR implications of e.g. allowing any user to trigger a message to other users

## Stakeholders
All Alkemio users

## Timeline
tbd

## Additional context
 Notifications to be used for these interactions. This means that the messages are sent out of band i.e. not directly within Alkemio. Later these notifications would ideally also be visible within Alkemio, but not in this epic. There are already two relevant notifications that can be re-used / adapted:
- interested in collaborating
- feedback on challenge (only was used for SSI demo but is there)

To avoid confusion, we want to keep the options as simple as possible. So, also out of scope:
- [ ] Allow users to give feedback in multiple places within a journey (suggestion, feedback etc)
- [ ] Allow users to request help (send a flare, messages sent to community leads / admins)
