### ISSUE TITLE
Journey pages refresh MVP

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#838]
## Description
As we are moving towards alignment, there is also a refresh of the pages and cards needed

## Initiative / goal
Refresh of the Journey pages following the UI refresh 

### Hypothesis
This simple, more modern look and feel will be attractive / intuitive for users 

## Acceptance criteria and must have scope
_**Dashboard tab**_
- [ ] Infoblock
- [ ] Facilitating organization + Host
- [ ] News = updates + option to open dialog with more
- [ ] (Top) Contributors + option to open dialog with more
- [ ] Recent contributions = latest activities
- [ ] (Top) Challenges

**_Contribute tab_**
- [ ] Infoblock
- [ ] List of callouts + dialog to say if you want to order, contact us
- [ ] Callouts (updated lay-out + cards)    

**_Challenges / Opportunities tab_**
- [ ] Infoblock
- [ ] List of Challenges
- [ ] All Challenges (new cards)

_**About tab**_
- [ ] Infoblock
- [ ] Facilitating organization  + host
- [ ] References
- [ ] Statistics
- [ ] Blocks with background, vision, impact, who 
- [ ] News = updates 
- [ ] Contributors

_**Contribution cards**_
- [ ] Canvases
- [ ] Cards

_**Global changes**_
- [ ] Colors
- [ ] Grid vertical
- [ ] paper component
- [ ] text styles

## Stakeholders
partners

## Design
https://www.figma.com/file/yTQkqDOwJCPTBSpX9ZS0CS/Version-1---December-2022?node-id=0%3A1&t=aRtn0EQPSqj2vqqX-1
