### ISSUE TITLE
Notifications: Improved contents, expansion

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#841]
## Description
Ensuring that the information received by users is specific to the event that happened.

## Initiative / goal
User engagement

### Hypothesis
By giving the users more useful notifications they will more readily come back to the platform content

## Acceptance criteria and must have scope
- [ ] Address technical debt around DTO duplication
- [ ] Add additional notification related to comment on discussion callout
- [ ] Expand information in callout related notifications to include direct links to the callout / card / comment / canvas
- [ ] Add global hub admins to receive notifications related to new users signing up (needed for user onboarding flows)

## Stakeholders
tbd

## Timeline
tbd
