### ISSUE TITLE
Callout: single canvas type

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#845]
## Description
Currently, the user can choose between a lot of different templates (or not-user friendly screen with no templates) which makes it confusing. They need a simple way to submit their contributions.

Canvases are a powerful platform capability, but they are at the moment not widely used as they are not visible enough

## Initiative / goal
To structure the answers to a Callout and to simplify the procedure for both the Admin as well as the user, we are moving towards a callout with only one canvas type (either one of the template or blank canvas). 

### Hypothesis
By making canvases easier to use that they will bring more value to the platform.

## Acceptance criteria and must have scope
- [ ] Admin callout create screen to be able to choose one canvas type
- [ ] Remove option to choose canvas type from user contribution submission
- [ ] Clicking on contribute in Canvas Callout results in directly opening the canvas in edit mode

## Stakeholders
Platform champions who provide content for the library

```[tasklist]
### Tasks
- [ ] Add a draft title or issxxx

## Timeline
asap

https://www.figma.com/file/dxSkLrIm1pZidIcDLHfZ8J/Single-Canvas-Type?node-id=0%3A1&t=1XEi9lwErq9sak5Q-1

**Comment by techsmyth** [comment]
@larssondenise @SimonDoherty1234 I think if we are refreshing the canvas callout then we need to also look at how the canvases in the library can be accessed + used by users

**Comment by SimonDoherty1234** [comment]
Some thoughts on addition of a new Canvas:
1) When adding a new canvas, the user is presented with a selection of use-case named pre-existing templates (with a blank canvas being the default) - similar to what is done on some well-known office-based programs now.
2) To make the creation of a canvas easier, there might be some smaller canvas “components” available – a bit like code snippets, but visual, which (if generic) could be included in the canvases for various different callouts / opportunities.
