### ISSUE TITLE
Flexible Notifications

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#849]
## Description
I would really like some way of knowing that someone replied to my comment, without receiving a notification for every single comment made. Because that could be a bit too much when things get busier on the platform. Some ideas:

An actual reply function so you would only see direct replies on your message.
A daily excerpt that tells me there are new comments in challenge a, b and c.

## Initiative / goal
User engagement

### Hypothesis
By allowing users more flexibility in the notifications that they receive that they will be more likely to leave notifications enabled

## Acceptance criteria and must have scope
- [ ] Allow users to choose which journeys they want to receive notifications on
- [ ] Clean up and make much more intuitive the set of user preferences related to notifications
- [ ] Store notifications for users so they can have a sort of "inbox"
...

To be further elaborated...

## Stakeholders
tbd

## Timeline
tbd

## Additional information
The current set of user preferences related to notifications:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/4ef39100-dece-457d-80eb-99377a1d8f9a)

**Comment by hoyterutteman** [comment]
Not actual anymore
