### ISSUE TITLE
Help dialog

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#857]
## Description
Currently, the help icon navigates to a page with some links to faq pages, releases, and terminology. Not very appealing and guiding. 

## Initiative / goal
Create a dialog with buttons that link to various pages with help/inspiration etc. that can be easily managed/updated. 

### Hypothesis
Users need help on the platform and are currently not easily navigating to for example the faq page.

## Acceptance criteria and must have scope
- [ ] Floating help icon bottom right 
- [ ] Design for dialog with several buttons 
   - [ ] Link to FAQ page
   - [ ] Link to latest releases
   - [ ] Link to Foundation website
   - [ ] Link to Github 
   - [ ] Link to Blog

## Stakeholders
New users to the platform

## Design
https://www.figma.com/file/IcZgJtuguDeodanyH0Xy08/Help-dialog?node-id=0%3A1
