### ISSUE TITLE
Branding at platform level

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#864]
## Description
The colours of the platform, as well as the option to chose different colour sets have to be updated for accessibility, also possibly for differentiating between hub / challenge and opportunity. Also, this will be need to be implemented for the innovation spaces. 

## Initiative / goal
Admin section on the platform level (besides hub / users authorization etc) with 'Branding'.

### Hypothesis
We will the colours to be data driven, also when we implement our innovation spaces. 

## Acceptance criteria and must have scope
- [ ] De-risk the addition of branding at the platform level
- [ ] Choose a set of primary colours that will be used for the possible schemes
 - [ ] Set new platform colours

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.
