### ISSUE TITLE
Comments: Threads + replies

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#871]
## Description
Allowing users to reply to each others comments.
Allow users to give likes / emoticons as response to messages

Note: particularly for the Forums the threaded conversations are key. 

## Initiative / goal
Making the platform more engaging. 

### Hypothesis
By allowing users to directly reply to other comments they would be more likely to engage in discussions.
Also a single discussion can then be much more useful

## Acceptance criteria and must have scope
- [ ] Synapse upgraded to 1.82
- [ ] Users are able to reply to other comments
- [ ] Users are able to respond to messages with emoticons
- [ ] Users receive notifications when a user replies to their message
- [ ] Replies / emoticon responses to show up in near real time (subscriptions)
- [ ] Emoticons usage to pass through data validation (separate scalar type?)
- [ ] room entity added to api with associated mutations + subscriptions, replacing existing entities / subscriptions
- [ ] Conversations are shown with replies

## Stakeholders
All users

## Timeline
Q2 2023

## Additional Context
https://www.figma.com/file/8efoXJlYtDGuqoWuRLp35U/Threaded-Comments?type=design&node-id=0%3A1&t=K7g4kmNpEmioCxlM-1

https://link.excalidraw.com/l/4BCnkZqaP0t/9TcOF59TzOm
