### ISSUE TITLE
Reporting on Usage: overview of reports

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#882]
## Description
Structurally understanding the usage and value generated by the platform is key to articulating the value of Alkemio

### Hypothesis
Being able to show usage allows for informed product decisions
Being able to quantify activity allows articulating the value of the platform

## Acceptance criteria and must have scope
- [ ] Dashboards showing usage 
- [ ] Activity metrics used in the platform
- [ ] Reporting on the use / performance of specific functionality
- How often are users messaging each other
- What are the most used features
- How often are callouts viewed instead of contributed to 
- Use of innovation packs
- [ ] Reporting on User Profiles
- Heat Map where they are located
- Screen sizes
- ...
- [ ] Reporting on the user journey on the platform
- Number of notifications send
- Time spend per tab in the Spaces
- Where do people exit
- Where do they go when entering a Space
- How long do they stay in the Space
- How many searches
- How often search for other users
- Where do they go after the home page (specific Space, search, contributors page?) / where do they exit the platform
- Number of People signing up + directly joining space + contributing?
- [ ] Reporting on performance
- Service Health + alerts on dashboard
- Number error events + details
- Errors per release, per service
- Space Dashboard loading time
- All mutations + average response time + # over time
- GraphQL mutations
- [ ] All to be broken down by role + per Space

https://databox.com/metrics-every-saas-company-should-track#4

## Stakeholders
tbd

## Timeline
tbd

**Comment by larssondenise** [comment]
@techsmyth @hero101 Post-its added to this initiative, and now epics for these few selected ones? I see there are a lot of other epics also already included under the initiative
![abedaa0f-2fad-4f66-a02a-ba1a6f041a45.jpg](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/25a87020-f590-421f-b0c1-e138960ed304)

**Comment by techsmyth** [comment]
@larssondenise I would suggest one epic with the selected reports, with then an acceptance criteria for each
