### ISSUE TITLE
Release mgmt: Process + tooling

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#883]
## Description
Ensuring that the release management process is repeatable, documented, with clear roles  and separated from infrastructure management

## Initiative / goal
Platform management

### Hypothesis
Investing in release management allows for wider and more robust release mgmt process

## Acceptance criteria and must have scope
- [ ] Release process is documented, with clear roles
- [ ] Release process currently one is shared
- [ ] Evaluate additional release management tooling
- [ ] Suggested new release management process is written up + shared
- [ ] tbd....

TBD
- [ ] Recommendations for future improvements (gap analysis)

## Stakeholders
Admin
Security officer

## Timeline
tbd
