### ISSUE TITLE
Whiteboard: Usability v1

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#884]
## Description
Canvases are a powerful platform capability, but they are at the moment not widely used as they are not visible enough

## Initiative / goal
Usability

### Hypothesis
By making canvases more visible + easier to use that they platform will be more useful

## Acceptance criteria and must have scope
- [ ] Users can easily import canvases from the community and the innovation Library 
- [ ] Able to control the choice of image to use as preview
- [ ] Able to display the full contents easily and / or automatically

TBD: able to clone a canvas created by another user that is locked

## Stakeholders
Platform champions who provide content for the library

## Timeline
asap

## Design
Figma: https://www.figma.com/file/LNuYfQWbq12zLWNmUPNHHw/Canvas-dialog?node-id=201%3A17&t=t9ZBQwX7hr4gQ9JH-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/d52735b0-033b-4b82-8bca-68cdee31152a)

**Comment by techsmyth** [comment]
Closing in favor of other whiteboard epics
