### ISSUE TITLE
Data Integrity - CLOSED

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#886]
## Description
Ensuring that the data managed by the platform is robust is critical to both trust in the platform and operational effectiveness

## Initiative / goal
Platform management

### Hypothesis
Having more confidence in the data allows for easier deployment flows + detection of issues

## Acceptance criteria and must have scope
- [ ] Ensuring migrations are run separately in production from the containers for the server api provision
- [ ] Database schema review, looking at FKs used, data field types, indexes, null / not null etc

Data deletion
- [ ] Ensure no unintended data is remaining after creation + deletation of a Hub
- ...

Note: analysis work - https://hackmd.io/i2gYGceLQ2G3GevWcugzgg

## Stakeholders
DevOps / platform administrators

## Timeline
Q4 2022
