### ISSUE TITLE
Landing page v1

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#895]
## Description
Currently if a user enters the platform, they see some hubs, ways to sign in or sign up, and some unknown terminology. It is however not immediately clear what you can do, why you are here, what should be the first step. For example how can I create a hub, what is the value, what are the functionalities 

Also related to remark Cronan: One thought - without the explanation that you gave me in person, I would find it harder to understand what the real benefits of it are. Perhaps a few short videos on the front page to explain what it's about - for companies, for individuals, for NGOs, etc... - would be a good way to get users more informed and engaged. 

## Initiative / goal
Provide users with a landing page when they land on the platform

### Hypothesis
More explanation on the platform help page will keep new user more engaged and guide them in what they can do

## Acceptance criteria and must have scope
- [ ] UX design for new home page
- [ ] Private repository for landing page 
- [ ] Prototype based on NextJS
- [ ] TBD: Categorizing hubs?

## Stakeholders
New users

## Figma Design
Working space: https://app.excalidraw.com/l/4BCnkZqaP0t/2MITBBXbPBH

https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?node-id=0%3A1&t=7kzwzAUHAUpPbWJF-1

**Comment by techsmyth** [comment]
Moving this back to new until it is written up, think we should make this an agreement that we only take epics into being elaborated when the text is written up etc...
