### ISSUE TITLE
Accessibility: Keyboard navigation

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#903]
## Description
For various users, eg people with a visual impairment or physical disability, it is important that they can navigate the application using the keyboard

## Initiative / goal
Accessibility

### Hypothesis
Being able to navigate the application via the keyboard is a key interaction mechanism for visually impaired users

## Acceptance criteria and must have scope
- [ ] Proper tabbing
- [ ] Skiplinks
- [ ] Labels for all icon buttons

## Stakeholders
Partners in Workforce Participation project

## Timeline
Q4

# About labeling all buttons
Currently, there are many buttons on the platform without a label. When using a screen reader, a label is necessary to understand what you're doing or where you're going.
An example on the sign in page:

A user finds the input field for their ID and enters it
Next field is password, all is fine
Next is a button without a name. Probably to enter?
User activates this button but isn't signed in or something, instead, his/her password is visible to everyone who might be walking by.. It was the show password button.

**Note that arealabelby might be nice to use here**

# About keyboard navigation/ tabbing

People who can't use a mouse or trackpad, often (if not always) navigate by using their keyboard. You can experience this yourself by using the tab-key and your arrow-keys. You might notice that although the order on most pages of the platform is correct, you often can't actually see where you are. Some browsers indicate this better than other browsers do, but there are many buttons/links that do not have any indication that they're ''highlighted''.
Moreover, you might also notice that you can't access some of the content, for example the info icons and some of the tooltips. 

### Examples of clear indications of where you are:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e047de5229913b309d08fd9a524a45f57c19e14/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abead04e0c7446c2289d52807d8215fd4b0e1f82/image.png)

### Examples of no or vague indications where you are:
I see nothing while I'm actually focusing on the Challenges button:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--127b813e8fa14cc5c92b77e639dd54d654430d9b/image.png)

Quite difficult to see that my focus is currently on German (Landing page)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzhRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef2b76abc0fc64ce4c2b7c8a19a77c0ec7435a9e/image.png)

## Initiative / goal

When using the keyboard, it should be clear where you are on the page. Would be great if we can also style it a bit, so it aligns nicely with the rest of the content (while of course still standing out to be clearly visible)

### Hypothesis

Adding indications of where you are on the page will improve the accessibility for keyboard users.

## Acceptance criteria and must have scope

- [ ] Analysis on what content can't be accessed
- [ ] Analysis on the order of the tabbing, if this aligns with the visual order
- [ ] Fixing findings
- [ ] All items to have an indication

# About Skiplinks
When using a screen reader or keyboard control, it takes forever to get through the recent contributions block, because you cant skip from one contribution to the other or from one block to the other. The same holds for the navigation, every time you come across a tab menu, each item is mentioned. Skiplinks help to skip over these items so people go directly to the next section instead.
