### ISSUE TITLE
User to user communication via notifications

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#907]
## Description
It is currently not possible for a user to interact with another user or admin/host via the platform. However, there may be various cases where a user wants to send another user a personal message, wants to share an interesting callout with them via email or mention them in one of the comments. Allowing users to tag / mention other users on the platform is key functionality in pretty much every community platofrm: github, linkedin, twitter, ...

## Initiative / goal
Allowing users to connect on the platform in three ways: personal message, sharing content via email + message, and mentioning in comments.

### Hypothesis
By making it much easier to tag + connect other users on the platform is key to getting the community interacting on the platform,

## Acceptance criteria and must have scope
- [ ] Tagging/mentioning of users and organizations
- [ ] Sharing content directly with another user by filling in their email address
- [ ] Sending personal message via the message icon on user cards / button on dashboard (& about page?) for leads
- [ ] Additional set of preferences and notification emails

TBD: GDPR implications of e.g. allowing any user to trigger a message to other users

TBD - messaging to community leads!
TBD - remove "interested in collaborating notification"?

## Stakeholders
All users

## Timeline
tbd

## Issues:
- [ ] Server/notifications: New event type added for sharing & personal message for user or hosts + API to trigger events
- [ ] Client: sharing dialog to be extended with the option to share content with email address
- [ ] Server/notifications: New event type added for mention in cards & discussion callout + API to trigger events + parse incoming message text to detect mentions, and trigger notification event with list of users that were mentioned
- [ ] Client/server: New set of preferences to allow users to receive notifications. Default is true, in both migration to add it and in new user profiles. 
     - Allow other users to send you a personal email (difference if you are a host or not/via what community?)
     - Allow other users to share platform  content with you via email
     - Receive notification when another user mentions you (what happens if the Hub is private?)
     - Receive notification if the organization you are a lead of is mentioned
     - Other preferences for the admin?
- [ ] Notifications: New notification email template + logic for sharing, mentioning & personal message
- [ ] Notifications: Email templates refresh of other emails
- [ ] Client: user + organization mentions, clicking on link navigates to profile
- [ ] Client: email icons added on user cards + button to contact the leads + dialog for personal message
- [ ] Client: Sharing dialog extended with option to choose user from a list
- [ ] TBD Provide controls to avoid opening up spamming possibilities (e.g. user can send only 5 per xx minutes?)
Client: https://www.figma.com/file/7PWb3hcoPAWmnHC8PqGy0A/User-2-user-messaging?node-id=0%3A1&t=FLi83Ae4pLZPoy5G-1
Email templates: https://www.figma.com/file/YtaAcCasSx9FoYSH5lTve3/Alkemio-User-2-User-Emails?node-id=0%3A1&t=KS9hEsI5Jhrm9xli-1

## Additional context
Notifications to be used for these interactions. This means that the messages are sent out of band i.e. not directly within Alkemio. Later these notifications would ideally also be visible within Alkemio, but not in this epic. There are already two relevant notifications that can be re-used / adapted:
- interested in collaborating
- feedback on challenge (only was used for SSI demo but is there)

TBD To avoid confusion, we want to keep the options as simple as possible. So, also out of scope:
- [ ] Allow users to give feedback in multiple places within a journey (suggestion, feedback etc)
- [ ] Allow users to request help (send a flare, messages sent to community leads / admins)

**Comment by larssondenise** [comment]
@techsmyth good if we combine this one with user to user messaging #833? as it is al related/requires similar email designs

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/b0efe82a-3d0e-4708-8d62-9511c51a8bf2)

should we prompt users to sign in to contact someone?
