### ISSUE TITLE
Journey Refresh MVP (v1)

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#910]
## Description
Having a user-friendly, compelling, responsive design that catches the eye, is easy to use and explains itself.

## Initiative / goal
Usability

### Hypothesis
By making a modern, user-friendly UI we will lower the `entry barrier` of the application and will have a higher success of the adoption and retention of new users

### Dashboard tab
- [ ] Infoblock
- [ ] Facilitating organization + Host
- [ ] News = updates + option to open dialog with `more`
- [ ] (Top) Contributors + option to open dialog with `more`
- [ ] Recent contributions = latest activities
- [ ] (Top) Challenges

### Contribute tab 
- [ ] Infoblock
- [ ] List of callouts + dialog to say if want to sort, `contact us`
- [ ] Callout updated layout + cards

### Challenges / Opportunities tab
- [ ] Infoblock
- [ ] List of Challenges / Opportunities
- [ ] All Challenges / Opportunities

### About tab
- [ ] Infoblock
- [ ] Facilitating organization + host
- [ ] References
- [ ] Statistics
- [ ] Blocks with background, vision, impact, who
- [ ] Contributors

### Contribution Cards
- [ ] Canvases
- [ ] Cards

https://www.figma.com/file/yTQkqDOwJCPTBSpX9ZS0CS/Version-1---December-2022?t=UehwzLFtXPbqghyD-0

## Stakeholders
All users

## Timeline
December 2022
