### ISSUE TITLE
Journey pages - for release

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#914]
## Description
After the first updates of the UI refresh, we see several points that have to be addressed before releasing this refresh. Two reasons: (1) to polish the designs that were implemented and (2) to avoid lossing functionalities for our users. Currently VNG uses cards to navigate its members to the right place in the Hub. As we will be removing Cards from the dashboard in the UI Refresh, we need to add recommendations before releasing. 

## Initiative / goal
- Polish the design for mobile version, headers, and other design related issues
- Avoid loosing functionalities for our users, we will implement recommendations + top callouts

### Hypothesis
By implementing the 'recommendations' and 'top callouts' to the dashboard, we will help hub admins guide their members as well as giving them the freedom to personalize the dashboard page. + updating the rest of the design is needed for a complete UI refresh. 

## Acceptance criteria and must have scope
Recommendations + top callouts
- [ ] Recommendations by the host (similar to references component/structure but with different icon)
- [ ] Option to provide recommendations in the admin settings
- [ ] 3 Top Callouts (based on the amount of contributions)

UI refresh refinements:
- [ ] Mobile improvements
- [ ] Header image beyond largest breakpoint
- [ ] Images ratio update
- [ ] Global challenges: challenges / contributors / settings / user and organization profiles

Callout publisher:
- [ ] Additional fields on the Callout entity: publishedBy, publishedDate
- [ ] Logic updated to set both fields when a Callout is published
- [ ] Fields used on the client to display this information
- [ ] Mutation that global admins (+ global hub admins) can update the publisher / date

Note: if a callout is moved back to draft + published again then the information will be updated.

## Stakeholders
T3D Hub

## Additional context
![Schermafbeelding 2022-12-09 om 16.18.18.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/764474bf-d2e7-4c16-8289-b494300d854d)
