### ISSUE TITLE
Test Suites Tech Debt

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#917]
## Description
Investing in the code quality, maintainability + documentation for Test Suites will make the tests ready for the long term

## Initiative / goal
Maintainability

### Hypothesis
By improving the code quality / setup of test suites the overall usage + effectiveness will be increased

## Acceptance criteria and must have scope
- [ ] Cleaned up code structure
- [ ] Lint rules applied + enforced
- [ ] Design document / overview of the setup
- ...

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.
