### ISSUE TITLE
Release mgmt: optimization

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#925]
## Description
Ensuring that the release management process is repeatable, documented, with clear roles  and separated from infrastructure management

## Initiative / goal
Platform management

### Hypothesis
Investing in release management allows for wider and more robust release mgmt process

## Acceptance criteria and must have scope
- [ ] Database restores are effective and documented
- [ ] Translation management process reviewed and automated
- [ ] Github actions refreshed e.g. release action
- [ ] NPM packages are published and using develop / main branches
- [ ] Authorization tests are extended and executed
- [ ] releases to restart all key services and check values returned by k8s
- [ ] Expand automation of release mgmt process

## Stakeholders
Admin
Security officer

## Timeline
tbd
