### ISSUE TITLE
Matrix adapter as a separate service

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#928]
## Description
Matrix adapter logic to be split out into a separate service to reduce the size of the code in the alkemio server repo and to improve server startup time

## Initiative / goal
Maintainability
Performance

### Hypothesis
By isolating the matrix adapter logic into a separate service the startup time of the server is reduce, the memory footprint of the combined set of alkemio servers is reduced and the code base is split

## Acceptance criteria and must have scope
- [ ] separate repository to hold the matrix adapter logic
- [ ] matrix-adapter-lib package to hold the event types and DTOs
- [ ] matrix adapter service that is packaged up as a docker image
- [ ] alkemio server repo updated to use the new matrix-adapter service and exchange messages using matrix-adapter-lib
- [ ] matrix configuration removed from the alkemio.yaml file when it is part of the matrix-adapter service yaml file
- [ ] production envrionment updated to add new container + adjust resource usage limits on server / new matrix-adpater container(s)

Note: the pattern is almost identical to that now in place with the notifications service.

Note: there is no data migration as it is just code that accesses the seprate synapse server that is being moved. 

## Stakeholders
Development
Ops re maintenance

## Timeline
tbd
