### ISSUE TITLE
Contribute Page 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#938]
## Description
The set of concepts needed to engage needs to be lower. The Contribute page requires at the moment some concepts that can be removed.

## Initiative / goal
Engaging the user

### Hypothesis
Removing choices and thinking from people is key to adoption. 

## Acceptance criteria and must have scope
- [ ] Fixed boxes on left hand column for a) introductions b) suggestions, ideas etc
- [ ] Fixed boxes cannot be removed by admins, though they can be edited
- [ ] Fixed boxes can be popped out to see the full details of them
- [ ] No notion of publishing etc, no notifications

Callout creation
- [ ] Offer two types of callouts: Ideas & Insights, Co-creation
- [ ] If the creator chooses Ideas & INsights then ask the user to choose how they want contributions i.e. comments or cards

Callout display
- [ ] Group the callouts by type i.e. Ideas & Insights, Co-creation

Naming
- [ ] Switch to whiteboard instead of Canvas
- [ ] Define a Callout as being an active exchange of views

## Stakeholders
Contributors

## Timeline
asap

## Design

Mockup from Fintan:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/953354eb-978c-4b06-97e0-5527adda9579)

Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
