### ISSUE TITLE
Data Integrity: Migrations reset; schema definition; orphaned data

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#943]
## Description

The goal is to have referential integrity in our database, have all relations properly defined and to have the SQL / migrations match the typeORM entities. That way we'll decrease number of data-related bugs, amount of redundant / orphant data in database and thus increase performance. As an additional benefit, we may be able to reduce the codebase.

## Initiative / goal

This initiative / epic will make the application more stable and will reduce user misery.

### Hypothesis

The hypothesis is that there is a large number of known and also a large number of unknown issues related to data integrity. We have hit many issues in the space of:

- storage buckets
- storage aggregators
- callouts
- profile
- journeys

Frequently aggregating queries in the business logic querying multiple entities should build / be part of a tree of dependencies. When a part of that tree has missing relationships the whole logic is broken and we do a lot of patching to fix it, show / no show errors and end up bypassing the root cause of the problem.

Additionally, with a lot of extra rows of the database, that increases its capacity --> cost + reduces the speed of query execution in the tables with orphan data.

Missing relationships on database level also prevent automation / scripting to have a generic solution created for iterating over all the relationships and cleaning up orphaned data.

Performance gain is expected, depending on the size of the orphaned. Mostly on Read due to the indexes.

## Acceptance criteria and must have scope

- [x] Reseting to a single migration script, but making sure that the previous migrations are still there in the code base
- [ ] Detection of orphaned data within an Alkemio database + ability to remove
- [ ] Test suite to validate the data integrity of an Alkemio database
- [ ] Referential integrity at database level
- [ ] Check for orphaned authorization policies: look for last updated date to see ones that have not been updated after a full all entity auth reset?

Later:
- [ ] TypeORM definitions to match the database schema

## Stakeholders

Dev team.

QA

## Timeline

Target: Q1 2024

## Design

Figma file:

Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us

--------------------------------
old:

## Description
Ensuring that the data managed by the platform is robust is critical to both trust in the platform and operational effectiveness

## Initiative / goal
Platform management

### Hypothesis
Having more confidence in the data allows for easier deployment flows + detection of issues

## Acceptance criteria and must have scope

Data deletion
- [ ] Ensure no unintended data is remaining after creation + deletion of a Hub
- ...

Note: analysis work - https://hackmd.io/i2gYGceLQ2G3GevWcugzgg

## Stakeholders
DevOps / platform administrators

## Timeline
Q1 2023
