### ISSUE TITLE
Excalidraw feedback

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#949]
## Description
After the switch from Miro to Excalidraw it is good to capture all our feedback. 

## Initiative / goal
We can use this feedback to provide to the Excalidraw team as well as a better understanding for ourselves as to what our users experience. 

## Acceptance criteria and must have scope
- [ ] Unlock all components on the board
- [ ] Right mouse click to drag
- [ ] Text blocks 
- [ ] Hover over part of the text already results in selecting

## Stakeholders
Alkemio Team
