### ISSUE TITLE
Calendar Events V2

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#952]
## Description
After releasing the first version of the calendar, there are some additional features needed to make it more functional/useful.

## Initiative / goal
Ensure that the events triggers users to join and allow admins to use them properly

### Hypothesis
By improving the set of functionalities related to the calendar, the use of it will increase.

## Acceptance criteria and must have scope

- [ ] Increase event character limits
- [ ] Calendar view on dashboard
- [ ] Show past events
- [ ] Whole-day/multi-day discussion

## Stakeholders
UWV

## Timeline
Q1

## Design
Figma file:
...
