### ISSUE TITLE
Reporting: Additional reports, data extensions, operations

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#954]
## Description
The metrics and analysis results generated by our reporting framework  should be widely visible to the whole organization

## Initiative / goal
Ways of working

### Hypothesis
By having the metrics widely visible and shared that we all focus on driving those metrics

## Acceptance criteria and must have scope
Secure access
- [x] alkem-io/infrastructure-operations#984
- [ ] Service account for submission of data to elastic with limited privileges

Screen sizes used to access the platform:
- [ ] Client to send up the screen resolution information
- [ ] Report created based on that data

Northstar analysis
- [ ] Dashboard to have space displayname when filtering
- [ ] Elastic to have the mapping from spaceID to diplayName

Usage dashboard: 
- [ ] Number of logged in and non-logged in users per day / week
- [ ] Fix the geolocation

## Stakeholders
Stewards
Stakeholders / investors

## Timeline
asap

## Additional Context
For future work that can build on top of this:
https://github.com/alkem-io/operations/blob/develop/docs/metrics-tracking.md

**Comment by techsmyth** [comment]
@larssondenise do you have more details of the four reports we landed on as being priority?
