### ISSUE TITLE
Handling of Time

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#956]
## Description
Ensuring end-end handling of time / dates in a consistent and appropriate way

## Initiative / goal
Usability

### Hypothesis
Users expect that time is handled cleanly, not doing so breaks trust

## Acceptance criteria and must have scope
- [ ] Storage of all time related information in the db is robust to timezones: e.g. always UTC time / timestamp 
- [ ] All api interactions use one approach / entity type (Timestamp vs. Date) + using a custom Scalar if Timestamp
- [ ] Client handles time information in a consistent way 
- [ ] Client to be able to display in local time zone and displayed correctly
- [ ] Technical note on the handling of time in Alkemio repo

Related:
- Subscriptions + handling of time: Receiving a message in the handler, "this field is not-nullable but returning null value". It maybe addressed if switch to timestamps.

CalendarEvent: date + time
createdDate / updatedDate / activityLog: timestamp? is the local time of db server or UTC?

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/b6e148f4-ac5a-4b23-b33f-f65c4cbbd1d0)

createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)

## Stakeholders
All users
