### ISSUE TITLE
Domain model: Naming alignment

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#957]
## Description
ALigning the naming used across the platform

## Initiative / goal
Usage
Maintainability

### Hypothesis
By having naming clean we improve teh accessibility of the platform

## Acceptance criteria and must have scope
The following names should be updated:

- [ ] Canvas ==> Whiteboard
- [ ] Aspect ==> Post
- [ ] CanvasCheckout ==> WhiteboardCheckout

Done:
- [ ] AspectTemplate ==> PostTemplate
- [ ] LifecycleTemplate ==> InnovationFlowTemplate
- [ ] CanvasTemplate ==> WhiteboardTemplate

The following places should be updated:
- [ ] Database tables
- [ ] Server api
- [ ] Client code base
- [ ] Documentation alkemio repo

Operations backlog
- [ ] Help system on website 

## Stakeholders
Development
