### ISSUE TITLE
Ecosystem Analytics: prototype

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#958]
## Description
Understanding the potential and wishes of the community around ecosystem analytics: how to visualize, how to interact, who sees what data etc.

These analytics potentially include a visualization of:
- [ ] the location of the users displayed on a map
- [ ] the locations of challenges or opportunities displayed on a map
- [ ] the connections between contributors & hubs / challenges / opportunities
- [ ] the connections between contributors, associated organizations and hubs / challenges 
- [ ] ....

## Initiative / goal
Ecosystem Analytics

### Hypothesis
Being able to interact with the ecosystem graph allows for community and ecosystem insights

## Acceptance criteria and must have scope
- [ ] Initial version of ecosystem analytics integrated / available via Alkemio

## Inspiration
Kathryn. Lynch: did a project a year or so ago to map the publicly funded Irish innovation ecosystem (on an all-island basis). Ecosystem Network View. 300+ actors/agencies/sources of funding - but not moving the needle at all in terms of innovation scorecard. 

## Stakeholders
UWV
Digicampus

OU:
====
A few value propositions came to my mind when you showed the graphs:

In order to do justice to decision-makers and orchestrators of the affiliated organizations of ecosystems, it is very important to be able to approach the value of the collaborations / cooperations in the ecosystem analytically. What do they gain from the collaboration / cooperation, what does it actually bring them?

Insight into the ecosystem landscape. So, who is participating, why, and working on what ecosystem services? Who doesn't participate, why not? What cooperation is still needed to grow the ecosystem and its services (seen from the ecosystem vision)?

How do the ecosystem and the affiliated partners perform? How can Alkemio show the development of the services and products comparing to the ecosystem goals?

Very important: How can we put this in the dimension of time? Can you make moving images of data, so that one can actually see how an ecosystem is developing?
====

...

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
