### ISSUE TITLE
Differentiation + navigation between the journey levels

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#959]
## Description
In the latest UI refresh, we used the labels on the top left to help the user navigate through the Hub, challenges, opportunities. Still, users feel lost when they dive into the deeper levels. They find it hard to understand that they are still in the same Hub and how they navigate back from the Opportunity to the Hub for example. Or whether they are contributing in the hub or opportunity.

## Initiative / goal
New visual differences between Hub, Challenge and Opportunity + improved navigation on the dashboard

### Hypothesis
More visual differentiation and clearer navigation will improve the user experience and engagement

## Acceptance criteria and must have scope
- [ ] Improved management of visuals
- [ ] Avatar selection for the journeys
- [ ] New Challenge & Opportunity banner

## Stakeholders
UWV / VNG
