### ISSUE TITLE
Search++: Within a Hub, Contributions, UI

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#960]
## Description
As a User I also want to search within a particular Hub so that I can find relevant content 

## Acceptance criteria

Client:
- [x] UX Design for search bar in Hub
- [ ] Client extended to display of search bar + page for results within a particular Hub 
- [ ] Search results tab to have an additional section for content results, where cards would be displayed

API:
- [x] Search query updated to be able to search within a Hub
- [x] Journey results: return only Challenges + Opportunities
- [x] Contribution results: New category, with for now only Cards
- [x] Contributor results: only display the users / orgs that have roles within the Hub
- [x] Each search result type to return 10 entries, and this to be displayed on text on screen

## Associated issues

```[tasklist]
### Tasks
- [ ] https://github.com/alkem-io/client-web/issues/3454
- [ ] https://github.com/alkem-io/server/issues/2538
```

## Additional Context

Current design:  https://www.figma.com/file/rkPg9ud5OCPYAfEpVLaPRX/UX-Search-cards-behaviour-%2B-results?node-id=36%3A69
