### ISSUE TITLE
Calendar events Bucket: Importing/Exporting; flexible time; show events from related sub/space

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#966]
TBD 

## Description
After releasing the first version of the calendar, there are some additional features needed to make it more functional/useful.

## Initiative / goal
Ensure that the events triggers users to join and allow admins to use them properly

### Hypothesis
By improving the set of functionalities related to the calendar, the use of it will increase.

## Acceptance criteria and must have scope

Potential scope: 
- [ ] Flexible time 
- [ ] Multiple day events
- [ ] Show events from Subspaces on Space level and vice versa
- [ ] Calendar on my dashboard with events from my member spaces?
- [ ] Notifications for new events 
- [ ] Notifications for comments on an event
- [ ] Linked to outlook /google calendar > Importing/Exporting calendars
- [ ] Creating an event in draft/unpublished state
- [ ] Location entry added
- [ ] References form when creating/editing event. API supports references and Aspect visualization also does.
- [ ] Format dates regarding user locale. mm/dd/yyyy or dd/mm/yyyy, ampm or 24h...
- [ ] In event dialog, add user's timezone behind the time (eg 12.00 CET)
- [ ] Option to not show past events
- [ ] Have a look at this list: https://medevel.com/17-event-management/ Anything interesting for us?

Community feedback:

- Can we tag people in calendar events? And could there be an integration with services like Google Calendar? It would also be great to have an option to view the agenda by week/day/month.
- Can we add colors to calendar events so that differences are easier to discern? And would it be possible to select time zones when creating an event? Currently, it automatically translates, but when working in an international team, it’s sometimes helpful to fix it in a specific time zone (especially with daylight saving time!).

## Non functional / review of the current code 
- [ ] Serverside: Sort events by startDate serverside
- [ ] Serverside: Filter past events serverSide. - in order to retrieve the first next 3 events for the dashboard. atm all events are retrieved
- [ ] Code clean / Serverside: find events by nameId
- [ ] Pagination of events?
- [ ] Settings section: see and edit events from there. pagination, see past events
- [ ] Design: of the confirm-delete dialog
- [ ] Design: of the Aspect and Event display
- [ ] Code clean: Aspect and Event use the same display, Aspect
- [ ] Code clean: CalendarEventDetailContainer has a lot of copy&paset from `AspectDashboardContainer` maybe put something common.
- [ ] Code clean: Consider uncontrolled state on TimePickers open, onOpen, onClose
- [ ] Code clean: Functions in utils.core/utils/time/utils.ts receive a string sometimes, some other times Date
- [ ] Code clean: Maybe move to a common place like `FloatingAddButton` and the `DeleteButton` the add and the delete buttons.

## Stakeholders
...

## Timeline
tbd

## Design
Figma file:
...
