### ISSUE TITLE
Demo environment data migration + retirement

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#967]
## Description
Closing down the old Demo environment will reduce hosting costs and simplify overall operational maintenance

## Initiative / goal
Maintability
Usage

### Hypothesis
By having all Demo hubs on production there is only production environment to be maintained

## Acceptance criteria and must have scope
- [ ] Review of Hubs on Demo environment and make a list of what content should be migrated
- [ ] Migration plan and execution
- [ ] Demo environment decommissioned, including removing from backup schema, deployoment pipelines etc. 

## Stakeholders
Devops.
Customer Success

## Timeline
Q1
