### ISSUE TITLE
Search: Performant, scalable + smarter

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#973]
## Description

Alkemio search capabilities need to strengthen. Our current approach is coupled with the database and is slow for the amount of data it processes.
We need a more reliable solution, with less overhead to maintain and even some smarts in it for free (based on using Elastic for the main search tool enabler).

## Initiative / goal

The search capabilities impact the how the user is able to interact with the vast information on the platform.
It connects users-topic-user.

### Hypothesis

The search capability is extracted in an additional microservice.
Search results are retrieved faster and more accurately.
The solution is horizontally scalable

## Acceptance criteria and must have scope
- [ ] Search query: Use flag from server configuration to decide which search "results finder" implementation to use behind the existing search query
- [ ] Searchv2 query: new query added to the api that has the same signature + results ojects as the current search query
- [ ] Search results supported from elastic to be the datatypes in the current search api
<img width="301" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--628e1e9a12fdd195a62d6626d9c544b986e151d2/image.png" alt="image.png" />

Note: exclude UserGroup
- [ ] Relevant domain data as currently used in Search ingested into Elastic ==> e.g. not messages from Matrix, activity logs etc
- [ ] Search service uses elastic to identify the set of unfiltered search results, i.e. elastic does not do the authorization filtering
- [ ] Technical design approved
- [ ] Update existing api tests to work with new results
- [ ] Search adapter to elastic + search query to elastic in the server service

Note: existing search service stays in the codebase for local development effort, but we do not extend it further.

Open questions: 
- [ ] Where to do the scheduled ingestion - microservice OR in an adapter in Elastic?
- [ ] Review of default ranking algorithm applied by Elastic + then decide if need our own ranking algorithms?

Infrastructure setup:
- [ ] Configuration work for Elastic to be stored in Infra-Ops?
- [ ] Approach is documented, and/or managed in Infra-ops

## Stakeholders

Users
Development team

## Timeline

Q1 2024

## Design
<img width="1955" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDRkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3da7f7c01f6a1cb9497b4886b7cb2d3fe52d5e19/image.png" alt="image.png" />

# Additional Context (previous epic description)

## Description
The current search implementation is based on hard coded database queries, and does not scale. The response time grows as the content on the platform grows, so as usage grows the performance will continue to degrade - significantly. 

Performance is likely roughly proportional to the content on the platform, and the entities being searched. As of mid Q4 the response time for a simple search (climate) is approximately 3 seconds - at a time of almost no database activity. If we expect content to double by Q1 2024 then I would expect response times to also double. 

Further, searching with the current implementation heavily loads the database server. That means that searching will result in longer response times for most other platform interactions as well. Clustering the database helps to mitigate this, but the fundamental issue that it is a very inefficient searching approach remains. Ideally we would like the server interaction to not be impacted by searching. 

By moving to a sophisticated data warehouse we can have much more performance and scalable search capability. 
It also opens the possibility to have smarter search results, as there is built in support for light weight "fuzzy" search results.

Finally is also a capability that can be further built upon for recommendations and other analytics. 

### Initiative
Smart search

### Hypothesis
Users expect fast search results, and not getting that will be viewed negatively for usability - affecting uptake.

Improving the search experiences it will be easier for users to navigate to the most relevant content for them and possibly the place where they can and will contribute.

## Acceptance criteria and must have scope
- [ ] Existing database query approach to be maintained for simple cluster setups
- [ ] Search service to be split into two, with the api remaining in the server and the simple search engine split out into a separate microservice
- [ ] Additional search service to be added that has ElasticSearch behind it
- [ ] Each document (record) in the warehouse contains the relevant authorization policy (for later)
- [ ] Configuration at server level to specify the search service implementation to use

Note: having the simple search service maintained means that it can also be a fall back implementation at times when the search service is being maintained. 

Open discussion points:
- Where to host the elastic cluster? It should I think not be the production reporting cluster on first thoughts...
- Where to check the users rights to get access to results? i.e. where to do the authorization check.
- How to handle pagination of search results?
- ...

out of scope: 
-  ability to search on past state. i.e. no searching based on contents based on time. The contents of the warehouse represents the current status of the server database. Business requirements:
-  
- [ ] Ability to find Cards matching a particular term where the data searched includes comments. 
- [ ] Ability to find Discussion callouts matching a particular term where the search data includes comments. 
- [ ] Ranking for matches based on comments to be less than matching based on Card direct data (title, description, tags).

## Stakeholders
All users

## Design
Figma file:

## Additional context
- How are documents sent to the service?
- How are search results authorized?
- How are documents updated?
- How are documents deleted?
- Which entities do we want to track?
- What metadata do we want to attach per document?
- What queries do we want to perform?
- How can we cache queries (query results)?
- Do we want suggestions/recommendations by a [Suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html)?
- What is the performance of the Suggester?
- Do we want to perform [fuzzy search](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html)?
- What is the performance of the fuzzy search?
- Pagination can be performed via the [Scroll API ](https://www.elastic.co/guide/en/elasticsearch/reference/current/scroll-api.html) and [Scroll search results](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#scroll-search-results)

## Results
You can find system design of the different components in [Search v2 components & system design](https://alkem.io/building-alkemio-org/challenges/technicaldesigns-9853/collaboration/searchv2-1373)
