### ISSUE TITLE
Improved content editing

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#975]
## Description
The entering of content on Alkemio needs to be a smooth, productive experience. The setup used also needs to be expandable technically

## Initiative / goal
Usability

### Hypothesis
Having a clean and productive user experience for entering content is key to interaction.

## Acceptance criteria and must have scope
- [ ] Single wysiwyg editor across large markdown locations and also comments
- [ ] Ability to expand it to have e.g. mentions in large editors 
- [ ] Ability to upload / edit / delete images in both locations, insert emoticons etc
- [ ] The counter for used chars vs available, doesn't consider MD attributes (i.e. <b>bold text</b> doesn't count <b> and </b>)

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
