### ISSUE TITLE
New hub structure with callouts in context

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#978]
## Description
Users currently struggle with the structure and differentiation between the Hub / Challenge / Opportunity. On the Hub level it is all about connecting the community to the change and using a platform that can guide you in this innovation process. Therefore, the key menu tabs will become the dashboard, community, challenges, and knowledge base. 

Also, the About tab still remains a vague concept, and will only be visited a few times. Therefore this can be included into a clearly visible button + dialog on the dashboard page. 

Furthermore, it is often unclear where people have to put what callouts, insights, knowledge. Therefore the callouts in context can improve the intuitivity for the users that they can post + answer to callouts directly in the context. 

## Initiative / goal
Introduce the new structure on Hub level with a Community + Knowledge base tab as well as the callouts in context + additional callout types.

### Hypothesis
By asking the questions in context, users are more likely to understand where to engage and how

## Acceptance criteria and must have scope
- [ ] Redirecting old callout urls + simplifying new urls
- [ ] Client routing for Callout urls
- [ ] Tracking old links
- [ ] Callouts grouped for the different tabs (Dashboard, Community, Challenges, Knowledge)
- [ ] Ability to move Callouts to another dialog
- [ ] Activity logs grouped (Contributions on dashboard, community related on community tab
- [ ] Ability to differentiate between server and client terminology
- [ ] New Callout creation + edit flows
- [ ] Callout dialogs 
- [ ] New callout type: collection of links + migration of recommendations to this type
- [ ] New callout type: single whiteboard
- [ ] Populator edited

## Stakeholders
UWV / VNG / ...

## Timeline
Q2

## Design
Figma file:
https://www.figma.com/file/zw3ymZPkFkVqtMsVLRuLRR/Structure-refresh-Q1?node-id=169%3A1132&t=xLnHeDCOTSSEE4kY-1

**Comment by hero101** [comment]
- I image an Epic to answer questions like - why is this needed, who asked for it, what are the changes based on and no technical details. Right now it feels like the body has been used for taking notes, and drafting AC with the technical implementation.

- @valentinyanakiev, @me-andre  I believe the group names (e.g. HOME_*, COMMUNITY_*) are too tightly coupling the frontend to the backend (just for display purposes) - a more generic name (e.g. GROUP_*) would decouple them, then the group can be used in the frontend completely independent
- Activities don't have any notion of groups, but filtering by groups is asked for
- Recommendations need to be migrated - Callout of type Reference does not exist, What is the "right" group for them?
