### ISSUE TITLE
Community Application Questions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#979]
## Description
Allowing community administrators to control the set of questions that are provided to applicants.

## Initiative / goal
Community engagement

### Hypothesis
Allowing community managers to control the questions presented to applicants makes for a more tailored experience for the target community. It also clearly helps with internationalization. 

## Acceptance criteria and must have scope
- [ ] Allowing the set of questions at Hub and Challenge to be specified via admin setting
- [ ] Control over the set of questions to control a) the questino b) the default text for answers c) the order d) whether a question is required
- [ ] Maximum of 5 questions
- [ ] Language selection to be associated with the set of questions 

Note: language selection is a placeholder for expansion later, idea is to allow multiple question sets depending on which language a user has set - so in the data model at least now. 

## Stakeholders
Community managers
UWV, Gebruiker Central

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
