### ISSUE TITLE
Operationalise Development Stack + Process

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#98]
To cover:
- [ ] CI Builds for active repositories from develop branch
- [ ] Operation development enviornments (dev, test)
   - [ ] http(s)://dev.cherrytwist.org/graphql - points to cherrytwist/server
   - [ ] http(s)://dev.cherrytwist.org/ - points to cherrytwist/client.web
- [ ] k8s manifests
   - [ ] cherrytwist/server - service / deployment manifests in cherrytwist/server/manifests
   - [ ] cherrytwist/client.web - service / deployment manifests in cherrytwist/client.web/manifests
   - [ ] ingress, k8s configuration (e.g. RBAC), CRDs manifests in cherrytwist/infrastructure/manifests
- [ ] GitHub deployment of CT stack (client - server) from cherrytwist/infrastructure
- [ ] Agreed development process / ways of working
- [ ] Deployment enviornment documented
