### ISSUE TITLE
Bucket: Whiteboards

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#981]
## Description
This is a bucket to capture issues, low priority bugs, and ideas for the whiteboard functionality. 

## Initiative / goal
Usability

### Hypothesis
Whiteboards are a very powerful tool in collaboration. 

## Acceptance criteria and must have scope
- [ ] Integrating Excalidraw library in a better way
- [ ] Picture to whiteboard: make a picture, add to whiteboard, text and shapes are extracted (see additional context for description)
- [ ] Whiteboard usability (choosing custom colors, adjusting colors of borders vs. letters, fonts changed randomly)

## Stakeholders
Platform champions who provide content for the library

## Additional Context

**Picture to whiteboard**
Since COVID we've gotten increasingly used to hybrid working. For many teams, it's common to work partly in the office and partly online. Online working together has also expanded the possibilities for people across different organizations to join forces. Instead of always having to travel to work together, these people can for example start their project with an offline kickoff and then continue the work online. When facilitating such hybrid projects, there's a big challenge in collecting all the output of offline sessions online. What people currently often do is take pictures of the whiteboards, flipcharts, etc. and then store these in an online file storage system that everyone can access. This way, the actual content is not very accessible and it's difficult to continue working on it. Imagine the power in being able to upload this content to a whiteboard where people can continue the brainstorm or revisit the discussion, being able to reorder the notes and add new insights... That would bring hybrid working to a whole new level.
