### ISSUE TITLE
Operations: Platform health monitoring

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#986]
## Description
Bringing the platform monitoring and reporting to a level that we can much easier track down issues and be able to be notified proactively if any of the cluster infrastructure is running out of resources / has errors.

## Initiative / goal
Platform management

### Hypothesis
Being able to see real data on the performance of the platform is key to a reliable service

## Acceptance criteria and must have scope
- [ ]  Alerting on kubernetes / resource management, including health checks on the services
- [ ] Visibility of the health services in Kibana
- [ ] Prometheus / similar?
- [ ] Optimize the data that is generated + reported: review what k8s + azure data that is collected

## Stakeholders
DevOps

## Timeline
tbd

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
