### ISSUE TITLE
Innovation Hubs: Rounding out Functionality

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#989]
## Description
Programs such as Kenniscentrum Innovatie, Startup in Residence or Opschalingstickets aim to build a community around their methodology and projects. Innovation Hubs are an effective way to highlight ongoing work, engage new members, share methodologies, and support community-building.

This is the informal community around a set of formal collaborations. Formal collaborations can therefore also be linked to multiple communities? There is no hierarchy here.

## Initiative / goal
Improve the added value of the innovation hub by focusing on information sharing first and then expand the community building aspects.

### Hypothesis
- Demonstrates the power of Alkemio in Sales (scalability, cross-learning between Spaces, network, etc.).
- Helps users understand the role of a Space (community/informal vs. formal, and where the work actually happens).
- Gives facilitators a lightweight way to engage potential contributors.

## User Stories P1 (Information Sharing)
All of these stories do not trigger membership discussions (website++)

- [ ] As a portfolio owner, I want to show the work we do and where you can contribute (Spaces)
- [ ] As a portfolio owner, I want to show how we do it, what tools and best practices we've developed (Template library)
- [ ] As a portfolio owner, I want a low-threshold way for potential contributors to find important information about the program / initiative (Knowledge base)
- [ ] As a portfolio owner, I want to share interesting news, articles, podcasts, etc. (knowledge base?)
- [ ] As a portfolio owner, I want someone to be visible as the point of contact
- [ ] As a portfolio owner, I want to ensure my logo is visible as the hosting organisation

## User Stories P2 (Community Building)
- [ ] As a portfolio owner, I want to show who is part of this community (and their roles..) (User profiles)
- [ ] As a portfolio owner, I want to share interesting events with my community (Calendar)
- [ ] As a portfolio owner, I want a low-threshold way for potential contributors to ask questions (Forum)
- [ ] As a portfolio owner, I want to receive a notification when a potential contributor asks a question
- [ ] As a potential contributor, I want to follow updates in this innovation hub

## Additional Notes
For this hub, consider more static info (at the top) to improve the loading time
Also, content attached to the Hub, or bottom up from the Spaces

## Stakeholders
SiR, VNG (Groei Innovatieplatform), Opschalingstickets, ...
Sales / fundraising / customer success

## Design
https://www.figma.com/design/wZkvw4E1KhRq9Ga6L6HmSL/Innovation-Hubs?node-id=2202-119&t=8V8ezKL6LF4dwk9I-1

**Comment by hoyterutteman** [comment]
@larssondenise Could you work out this one?

**Comment by larssondenise** [comment]
is there more work on this epic required in one of the upcoming sprints? @SimoneZaza

**Comment by SimoneZaza** [comment]
@larssondenise I think we have the most important things for now, so we can bring this back to the backlog without a sprint attached. One thing that will come up at one point is to have better management of creating the URLS, but with all the taskforce work this will have to wait a bit.

**Comment by larssondenise** [comment]
@SimoneZaza agreed, thanks!
