### ISSUE TITLE
Update of Journey settings tab: v1

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#991]
## Description
Although an admin can do _way_ more on the platform than ~ a year ago, the settings tab is still sort of the same. New settings were added within the tabs and we added a few tabs since then, but a proper update of the settings page hasn't been done for a long time. This caused the settings page to be a bit unstructured and difficult to navigate, making it harder for (new) admins to shape their journey pages as they seem fit.

## Initiative / goal
Updating the admin settings will ease the flow of setting up a Journey, improving the early experience for new admins with the platfom. 

### Hypothesis
Simplifying the admin of spaces / challenges makes for more usage

## Acceptance criteria and must have scope
- [ ] Simplified setup of Space 
- [ ] Simplified community management + roles for each Member
- [ ] Platform level settings for a Space separated out
- [ ] 
- [ ] Space admins no longer able to directly add members to a space or challenge. Note: this requires a new privilege: COMMUNITY_ADD_MEMBER which should only be granted to global admins. The client should check for this privilege before displaying the ADD button.

## Stakeholders
Support team

## Timeline
Q2

## Design

Figma file:
https://www.figma.com/file/t3XQACWEsDa3r8YPyihmsp/Settings---refresh-Q2%2F3-2023?type=design&node-id=0%3A1&t=xgrnA3AifjMFwzDK-1
