### ISSUE TITLE
Innovation library management by admins

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#992]
## Description
There are a lot of conversations ongoing with getting communities onboard, research institutes with a lot of Knowledge, and knowledge around innovation from other champions.

They all see the value of / can contribute to the knowledge for innovation packs

## Initiative / goal
Ensuring that the Alkemio team can easily put up innovation packs

### Hypothesis
By making this process easier to manage, allows us to put up 

## Acceptance criteria and must have scope
- [ ] Section in the platform admin settings for innovation packs
- [ ] Ability to create or import canvases, innovation flows, or cards to this pack
- [ ] Innovation pack has a name, provider, description, tags

## Stakeholders
VNG
UWV
Rathenau Institute
Impact Institute
Universities
TheoryU
Innovate Community
etc.
