### ISSUE TITLE
Accessibility: Visuals alternative text

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#993]
## Description
Visually impaired are able to use Alkemio by ensuring that visuals (banners, avatars, card images) etc have alternative text.

## Initiative / goal
Accessibility
The Hague project

### Hypothesis
Visuals on the platform are currently lacking alternative text

## Acceptance criteria and must have scope
- [ ] Add alternative text field to Visual entity, with support for editing it in update mutations
- [ ] Editing of Visuals to allow entering the alternative text to use
- [ ] Display of Visual meta information on settings pages (e.g user profile, banner for journeys etc) shows the resulting alternative text
- [ ] Visual usage to have translation strings for alternative text which includes both general text and custom text from the Visual entity. E.g. "Banner for this Challenge: {{visual.alternativeText}}"

## Stakeholders
Envision
UWV

## Timeline
Workshop on May 17th, for which notifications go out week of April 17th.

**Comment by SimoneZaza** [comment]
Interesting information on this topic on the website of the Grand Valley State University (https://www.gvsu.edu/accessibility/alt-text-7.htm)

Alt Text
INTRODUCTION
The Alternative (Alt) Text is the invisible description of an image that is read out loud by a screen reader in place of an image. Appropriate and descriptive Alt Text contributes to the page becoming fully accessible to those using assistive technologies. The Alt Text will also be displayed in place of the image if the image fails to load properly.

BASICS
An Alt Text should strive to answer this question: What is the main point being conveyed by the image? The Alt Text should not only describe the superficial details of the image; instead, it should convey the information or emotion that you want a user to gain from looking at the image.

Of the seven types of images as defined by the World Wide Web Consortium (W3C), the GVSU CMS is concerned with the following four types; Informative Images, Functional Images, Images of Text, and Complex Images.

- Informative images: Images that represent concepts, information, or emotions, and are typically graphics, photos, and illustrations. The text alternative should be a short description conveying the essential information presented by the image. 

- Functional images: The text alternative of an image used as a link or as a button should describe the functionality of the link or button rather than the details of the image. Examples of such an image is a printer icon to represent the print function.

- Images of text: Readable text is sometimes presented within an image. If the image is not a logo, avoid text in images. However, if images of text are used, the text alternative must contain the same words as in the image.

- Complex images such as graphs and diagrams: To convey data or detailed information, provide a full-text equivalent of the data or information provided in the image as the text alternative.

When adding an Alt Text it's important to keep it concise (around of 140 characters) yet descriptive. With a 140 character limit, it is unnecessary to start the Alt Text with "image of", "graph of", "photo of", etc. A screen reader will recognize the file as an image and let the user know for you. It's not required that an Alt Text is under 140 characters but a screen reader will stop reading the text after 140 characters. If an image can't be described in 140 characters, it's considered a complex image and recommended to add a description of the image as a caption or link to a page with the full details of the image. In this instance, you still need to add an Alt Text, however, the Alt Text should describe the general point of the image.

 

An Alt Text should not be duplicated on a page unless the images are identical or the intent of the image is the same. Imagine that all of your images failed to load and were replaced with the Alt Text for those images. Duplicating the Alt Text would indicate to the user that the images are identical and are being repeated on the page, regardless if the image are actually different.
